-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "kanagawa"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "Constant" })
hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.error", { bg = "#c76357", bold = true, fg = "#cdc6a7" })
hi(0, "@comment.note", { bg = "#8f9190", bold = true, fg = "#14253b" })
hi(0, "@comment.todo", { link = "Todo" })
hi(0, "@comment.warning", { bg = "#e9b180", bold = true, fg = "#14253b" })
hi(0, "@constant.builtin", { link = "Special" })
hi(0, "@constructor", { fg = "#6ea4ba" })
hi(0, "@constructor.lua", { fg = "#8471a5" })
hi(0, "@diff.delta", { fg = "#cc944f" })
hi(0, "@diff.minus", { fg = "#b12d33" })
hi(0, "@diff.plus", { fg = "#66855a" })
hi(0, "@function.builtin", { link = "Special" })
hi(0, "@ibl.indent.char.1", { fg = "#5e5c48", nocombine = true })
hi(0, "@ibl.indent.char.2", { fg = "#4a374a", nocombine = true })
hi(0, "@ibl.indent.char.3", { fg = "#2b342b", nocombine = true })
hi(0, "@ibl.indent.char.4", { fg = "#31494a", nocombine = true })
hi(0, "@ibl.scope.char.1", { fg = "#837b96", nocombine = true })
hi(0, "@ibl.scope.underline.1", { sp = "#938aa9", underline = true })
hi(0, "@ibl.whitespace.char.1", { fg = "#46455f", nocombine = true })
hi(0, "@keyword.exception", { bold = true, fg = "#e25156" })
hi(0, "@keyword.import", { link = "PreProc" })
hi(0, "@keyword.luap", { link = "@string.regex" })
hi(0, "@keyword.operator", { bold = true, fg = "#b0935e" })
hi(0, "@keyword.return", { fg = "#e25156", italic = true })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.mod.readonly", { link = "Constant" })
hi(0, "@lsp.mod.typeHint", { link = "Type" })
hi(0, "@lsp.type.builtinConstant", { link = "@constant.builtin" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", {})
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.magicFunction", { link = "@function.builtin" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.selfParameter", { link = "@variable.builtin" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.function.builtin", { link = "@function.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.function.readonly", { bold = true, fg = "#708bc5" })
hi(0, "@lsp.typemod.keyword.documentation", { link = "Special" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.controlFlow", { link = "@keyword.exception" })
hi(0, "@lsp.typemod.operator.injected", { link = "Operator" })
hi(0, "@lsp.typemod.string.injected", { link = "String" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "Special" })
hi(0, "@lsp.typemod.variable.global", { link = "Constant" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@lsp.typemod.variable.static", { link = "Constant" })
hi(0, "@markup.environment", { link = "Keyword" })
hi(0, "@markup.heading", { link = "Function" })
hi(0, "@markup.link", { link = "Underlined" })
hi(0, "@markup.link.url", { link = "@string.special.url" })
hi(0, "@markup.math", { link = "Constant" })
hi(0, "@markup.quote", { link = "@variable.parameter" })
hi(0, "@markup.raw", { link = "String" })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@punctuation.bracket", { fg = "#8d9bb7" })
hi(0, "@punctuation.delimiter", { fg = "#8d9bb7" })
hi(0, "@punctuation.special", { fg = "#6ea4ba" })
hi(0, "@string.escape", { bold = true, fg = "#b0935e" })
hi(0, "@string.regexp", { fg = "#b0935e" })
hi(0, "@string.special", { link = "SpecialChar" })
hi(0, "@string.special.symbol", { fg = "#d5b273" })
hi(0, "@string.special.url", { fg = "#6ea4ba", undercurl = true })
hi(0, "@tag.attribute", { fg = "#d5b273" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { fg = "#8d9bb7" })
hi(0, "@type.builtin", { link = "Special" })
hi(0, "@variable", { fg = "#cdc6a7" })
hi(0, "@variable.builtin", { fg = "#d15767", italic = true })
hi(0, "@variable.member", { fg = "#d5b273" })
hi(0, "@variable.parameter", { fg = "#a7a4bc" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "Added", { ctermfg = 10, fg = "#a7e4b1" })
hi(0, "AerialArrayIcon", { link = "Type" })
hi(0, "AerialBooleanIcon", { link = "Boolean" })
hi(0, "AerialClassIcon", { link = "Type" })
hi(0, "AerialConstantIcon", { link = "Constant" })
hi(0, "AerialConstructorIcon", { link = "@constructor" })
hi(0, "AerialEnumIcon", { link = "Type" })
hi(0, "AerialEnumMemberIcon", { link = "Constant" })
hi(0, "AerialEventIcon", { link = "Structure" })
hi(0, "AerialFieldIcon", { link = "@variable.member" })
hi(0, "AerialFileIcon", { link = "Directory" })
hi(0, "AerialFunctionIcon", { link = "Function" })
hi(0, "AerialInterfaceIcon", { link = "Type" })
hi(0, "AerialKeyIcon", { link = "Identifier" })
hi(0, "AerialMethodIcon", { link = "@function.method" })
hi(0, "AerialModuleIcon", { link = "@module" })
hi(0, "AerialNamespaceIcon", { link = "@module" })
hi(0, "AerialNullIcon", { link = "Type" })
hi(0, "AerialNumberIcon", { link = "Number" })
hi(0, "AerialObjectIcon", { link = "Type" })
hi(0, "AerialOperatorIcon", { link = "Operator" })
hi(0, "AerialPackageIcon", { link = "@module" })
hi(0, "AerialPropertyIcon", { link = "@property" })
hi(0, "AerialStringIcon", { link = "String" })
hi(0, "AerialStructIcon", { link = "Structure" })
hi(0, "AerialTypeParameterIcon", { link = "Type" })
hi(0, "AerialVariableIcon", { link = "@variable" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { bold = true, fg = "#e5925d" })
hi(0, "Changed", { ctermfg = 14, fg = "#7be8e6" })
hi(0, "Character", { link = "String" })
hi(0, "ChatGPTCompletion", { fg = "#84899f", italic = true })
hi(0, "ChatGPTMessageAction", { bg = "#394e58", fg = "#eeeeee", italic = true })
hi(0, "ChatGPTQuestion", { fg = "#a4ade5", italic = true })
hi(0, "ChatGPTTotalTokens", { bg = "#484848", fg = "#eeeeee" })
hi(0, "ChatGPTTotalTokensBorder", { fg = "#363636" })
hi(0, "ChatGPTWelcome", { fg = "#84899f", italic = true })
hi(0, "CmpCompletion", { link = "Pmenu" })
hi(0, "CmpCompletionBorder", { bg = "#353536", fg = "#1d4059" })
hi(0, "CmpCompletionSbar", { link = "PmenuSbar" })
hi(0, "CmpCompletionSel", { bg = "#465159" })
hi(0, "CmpCompletionThumb", { link = "PmenuThumb" })
hi(0, "CmpDocumentation", { link = "NormalFloat" })
hi(0, "CmpDocumentationBorder", { link = "FloatBorder" })
hi(0, "CmpItemAbbr", { fg = "#cdc6a7" })
hi(0, "CmpItemAbbrDefault", { fg = "#cdc6a7" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#66605a", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#66605a" })
hi(0, "CmpItemAbbrMatch", { fg = "#708bc5" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#cdc6a7" })
hi(0, "CmpItemAbbrMatchFuzzy", { link = "CmpItemAbbrMatch" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#cdc6a7" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColor", { link = "Special" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { link = "Constant" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { link = "@constructor" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindCopilot", { link = "String" })
hi(0, "CmpItemKindDefault", { fg = "#6ea4ba" })
hi(0, "CmpItemKindEnum", { link = "Type" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { link = "Constant" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { link = "Type" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { link = "@variable.member" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFile", { link = "Directory" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolder", { link = "Directory" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "Type" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { link = "Keyword" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "@function.method" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { link = "@module" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { link = "@property" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { link = "Special" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { link = "Special" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { link = "Type" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindText", { fg = "#cdc6a7" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { link = "Type" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { link = "Number" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { link = "String" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = "#b7af83" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = "#66605a" })
hi(0, "CmpItemMenuDefault", { fg = "#cdc6a7" })
hi(0, "ColorColumn", { bg = "#2f2f2f" })
hi(0, "Comment", { fg = "#66605a", italic = true })
hi(0, "Conceal", { bold = true, fg = "#837b96" })
hi(0, "Constant", { fg = "#e5925d" })
hi(0, "CratesNvimPopupEnabled", { ctermfg = 2, fg = "#2d9845" })
hi(0, "CratesNvimPopupPillBorder", { ctermfg = 242, fg = "#2c2c2c" })
hi(0, "CratesNvimPopupPillText", { bg = "#3e3e3e", ctermbg = 242, ctermfg = 15, fg = "#d0d0d0" })
hi(0, "CratesNvimPopupTransitive", { ctermfg = 4, fg = "#267ba2" })
hi(0, "CurSearch", { bg = "#465159", bold = true, fg = "#cdc6a7" })
hi(0, "Cursor", { bg = "#dbdbdb", fg = "#110f1a" })
hi(0, "CursorColumn", { link = "CursorLine" })
hi(0, "CursorLine", { bg = "#3c3c3c" })
hi(0, "CursorLineNr", { bold = true, fg = "#e7913b" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#d5b273" })
hi(0, "DapUIBreakpointsDisabledLine", { link = "Comment" })
hi(0, "DapUIBreakpointsInfo", { fg = "#557585" })
hi(0, "DapUIBreakpointsPath", { link = "Directory" })
hi(0, "DapUIDecoration", { fg = "#46455f" })
hi(0, "DapUIFloatBorder", { fg = "#46455f" })
hi(0, "DapUILineNumber", { fg = "#6ea4ba" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#6ea4ba" })
hi(0, "DapUINormalNC", { bg = "#242424", fg = "#cdc6a7" })
hi(0, "DapUIPlayPause", { fg = "#88aa5b" })
hi(0, "DapUIPlayPauseNC", { bg = "#0e0e0e", fg = "#9cec62" })
hi(0, "DapUIRestart", { fg = "#88aa5b" })
hi(0, "DapUIRestartNC", { bg = "#0e0e0e", fg = "#9cec62" })
hi(0, "DapUIScope", { link = "Special" })
hi(0, "DapUISource", { fg = "#d15767" })
hi(0, "DapUIStepBack", { fg = "#6ea4ba" })
hi(0, "DapUIStepBackNC", { bg = "#0e0e0e", fg = "#46dbdf" })
hi(0, "DapUIStepInto", { fg = "#6ea4ba" })
hi(0, "DapUIStepIntoNC", { bg = "#0e0e0e", fg = "#46dbdf" })
hi(0, "DapUIStepOut", { fg = "#6ea4ba" })
hi(0, "DapUIStepOutNC", { bg = "#0e0e0e", fg = "#46dbdf" })
hi(0, "DapUIStepOver", { fg = "#6ea4ba" })
hi(0, "DapUIStepOverNC", { bg = "#0e0e0e", fg = "#46dbdf" })
hi(0, "DapUIStop", { fg = "#c92c27" })
hi(0, "DapUIStopNC", { bg = "#0e0e0e", fg = "#d12d5f" })
hi(0, "DapUIStoppedThread", { fg = "#6ea4ba" })
hi(0, "DapUIThread", { fg = "#d5b273" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIUnavailable", { fg = "#66605a" })
hi(0, "DapUIUnavailableNC", { bg = "#0e0e0e", fg = "#343434" })
hi(0, "DapUIWatchesEmpty", { fg = "#c92c27" })
hi(0, "DapUIWatchesError", { fg = "#c92c27" })
hi(0, "DapUIWatchesValue", { fg = "#d5b273" })
hi(0, "DapUIWinSelect", { bold = true, ctermfg = 14, fg = "#46dbdf" })
hi(0, "DashboardCenter", { fg = "#d5b273" })
hi(0, "DashboardDesc", { fg = "#d5b273" })
hi(0, "DashboardFooter", { fg = "#66605a" })
hi(0, "DashboardHeader", { fg = "#b12d33" })
hi(0, "DashboardIcon", { fg = "#837b96" })
hi(0, "DashboardKey", { fg = "#6ea4ba" })
hi(0, "DashboardShortCut", { fg = "#6ea4ba" })
hi(0, "Delimiter", { fg = "#8d9bb7" })
hi(0, "DiagnosticERRORReverse", { bg = "#c76357", fg = "#020202" })
hi(0, "DiagnosticError", { fg = "#c92c27" })
hi(0, "DiagnosticFloatingError", { fg = "#c92c27" })
hi(0, "DiagnosticFloatingHint", { fg = "#5a857a" })
hi(0, "DiagnosticFloatingInfo", { fg = "#557585" })
hi(0, "DiagnosticFloatingOk", { fg = "#88aa5b" })
hi(0, "DiagnosticFloatingWarn", { fg = "#e7913b" })
hi(0, "DiagnosticHINTReverse", { bg = "#8f9190", fg = "#020202" })
hi(0, "DiagnosticHint", { fg = "#5a857a" })
hi(0, "DiagnosticINFOReverse", { bg = "#858585", fg = "#020202" })
hi(0, "DiagnosticInfo", { fg = "#557585" })
hi(0, "DiagnosticOk", { fg = "#88aa5b" })
hi(0, "DiagnosticSignError", { fg = "#c92c27" })
hi(0, "DiagnosticSignHint", { fg = "#5a857a" })
hi(0, "DiagnosticSignInfo", { fg = "#557585" })
hi(0, "DiagnosticSignWarn", { fg = "#e7913b" })
hi(0, "DiagnosticUnderlineError", { sp = "#e82424", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#6a9589", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#658594", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#ff9e3b", undercurl = true })
hi(0, "DiagnosticWARNReverse", { bg = "#e9b180", fg = "#020202" })
hi(0, "DiagnosticWarn", { fg = "#e7913b" })
hi(0, "DiffAdd", { bg = "#343434" })
hi(0, "DiffChange", { bg = "#2b2b2b" })
hi(0, "DiffDelete", { bg = "#333333", fg = "#b12d33" })
hi(0, "DiffText", { bg = "#494949" })
hi(0, "DiffviewDiffAddAsDelete", { bg = "#333333", fg = "#b12d33" })
hi(0, "DiffviewDim1", { fg = "#66605a" })
hi(0, "DiffviewFilePanelCounter", { bold = true, fg = "#d5b273" })
hi(0, "DiffviewFilePanelFileName", { fg = "#cdc6a7" })
hi(0, "DiffviewFilePanelTitle", { bold = true, fg = "#8471a5" })
hi(0, "DiffviewPrimary", { fg = "#708bc5" })
hi(0, "DiffviewSecondary", { fg = "#88aa5b" })
hi(0, "Directory", { fg = "#708bc5" })
hi(0, "EndOfBuffer", { fg = "#110f1a" })
hi(0, "Error", { fg = "#c92c27" })
hi(0, "ErrorMsg", { fg = "#c92c27" })
hi(0, "Exception", { fg = "#d15767" })
hi(0, "FloatBorder", { bg = "#1c1c1c", fg = "#46455f" })
hi(0, "FloatFooter", { bg = "#1c1c1c", fg = "#46455f" })
hi(0, "FloatShadow", { bg = "#565656", blend = 80, ctermbg = 0 })
hi(0, "FloatShadowThrough", { bg = "#565656", blend = 100, ctermbg = 0 })
hi(0, "FloatTitle", { bg = "#1c1c1c", bold = true, fg = "#837b96" })
hi(0, "FloatermBorder", { bg = "#242424", fg = "#46455f" })
hi(0, "FoldColumn", { fg = "#46455f" })
hi(0, "Folded", { bg = "#2f2f2f", fg = "#837b96" })
hi(0, "Function", { fg = "#708bc5" })
hi(0, "GitSignsAdd", { fg = "#66855a" })
hi(0, "GitSignsChange", { fg = "#cc944f" })
hi(0, "GitSignsDelete", { fg = "#b12d33" })
hi(0, "GitSignsStagedAdd", { fg = "#2e3c27" })
hi(0, "GitSignsStagedAddLn", { bg = "#343434" })
hi(0, "GitSignsStagedAddNr", { fg = "#2e3c27" })
hi(0, "GitSignsStagedChange", { fg = "#5f4421" })
hi(0, "GitSignsStagedChangeLn", { bg = "#2b2b2b" })
hi(0, "GitSignsStagedChangeNr", { fg = "#5f4421" })
hi(0, "GitSignsStagedChangedelete", { fg = "#5f4421" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#2b2b2b" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#5f4421" })
hi(0, "GitSignsStagedDelete", { fg = "#520f13" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#520f13" })
hi(0, "GitSignsStagedTopdelete", { fg = "#520f13" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#520f13" })
hi(0, "GlanceBorderTop", { bg = "#383838", fg = "#46455f" })
hi(0, "GlanceFoldIcon", { fg = "#918c71" })
hi(0, "GlanceIndent", { fg = "#4c4b67" })
hi(0, "GlanceListBorderBottom", { bg = "#343434", fg = "#46455f" })
hi(0, "GlanceListCursorLine", { bg = "#4d4d4d" })
hi(0, "GlanceListEndOfBuffer", { bg = "#343434", fg = "#21212d" })
hi(0, "GlanceListFilepath", { fg = "#918c71" })
hi(0, "GlanceListNormal", { bg = "#343434", fg = "#cdc6a7" })
hi(0, "GlancePreviewBorderBottom", { bg = "#2e2e2e", fg = "#46455f" })
hi(0, "GlancePreviewCursorLine", { bg = "#474747" })
hi(0, "GlancePreviewEndOfBuffer", { bg = "#2e2e2e", fg = "#1b1b25" })
hi(0, "GlancePreviewLineNr", { fg = "#50516e" })
hi(0, "GlancePreviewMatch", { bg = "#465159", fg = "#cdc6a7" })
hi(0, "GlancePreviewNormal", { bg = "#2e2e2e" })
hi(0, "GlancePreviewSignColumn", { fg = "#1b1b25" })
hi(0, "GlanceWinBarFilename", { bg = "#383838", fg = "#cdc6a7" })
hi(0, "GlanceWinBarFilepath", { bg = "#383838", fg = "#938e73" })
hi(0, "GlanceWinBarTitle", { bg = "#383838", fg = "#cdc6a7" })
hi(0, "IblIndent", { fg = "#46455f" })
hi(0, "IblScope", { fg = "#837b96" })
hi(0, "IblWhitespace", { fg = "#46455f" })
hi(0, "Identifier", { fg = "#d5b273" })
hi(0, "Ignore", { link = "NonText" })
hi(0, "IncSearch", { bg = "#e9b180", fg = "#14253b" })
hi(0, "IndentBlanklineChar", { fg = "#46455f" })
hi(0, "IndentBlanklineContextChar", { fg = "#837b96" })
hi(0, "IndentBlanklineContextStart", { sp = "#938aa9", underline = true })
hi(0, "IndentBlanklineIndent1", { bg = "#2f2f2f", fg = "#1f1f10" })
hi(0, "IndentBlanklineIndent2", { bg = "#2b2b2b", fg = "#1f161f" })
hi(0, "IndentBlanklineIndent3", { bg = "#2e2e2e", fg = "#151e15" })
hi(0, "IndentBlanklineIndent4", { bg = "#2d2d2d", fg = "#121d1f" })
hi(0, "IndentBlanklineIndentChar1", { fg = "#5e5c48" })
hi(0, "IndentBlanklineIndentChar2", { fg = "#4a374a" })
hi(0, "IndentBlanklineIndentChar3", { fg = "#2b342b" })
hi(0, "IndentBlanklineIndentChar4", { fg = "#31494a" })
hi(0, "IndentBlanklineSpaceChar", { fg = "#46455f" })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#46455f" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#8471a5", italic = true })
hi(0, "LazyProgressTodo", { fg = "#46455f" })
hi(0, "LineNr", { fg = "#46455f" })
hi(0, "LspCodeLens", { fg = "#66605a" })
hi(0, "LspCodeLensSeparator", { link = "Boolean" })
hi(0, "LspReferenceText", { bg = "#494949" })
hi(0, "LspReferenceWrite", { bg = "#494949", underline = true })
hi(0, "LspSignatureActiveParameter", { fg = "#e7913b" })
hi(0, "MatchParen", { bold = true, fg = "#e7913b" })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { underline = true })
hi(0, "ModeMsg", { bold = true, fg = "#e7913b" })
hi(0, "MoreMsg", { fg = "#557585" })
hi(0, "MsgArea", { link = "StatusLine" })
hi(0, "MsgSeparator", { bg = "#242424" })
hi(0, "MultiCursor", { link = "VM_Cursor" })
hi(0, "NavicIconsArray", { link = "Type" })
hi(0, "NavicIconsBoolean", { link = "Boolean" })
hi(0, "NavicIconsClass", { link = "Type" })
hi(0, "NavicIconsConstant", { link = "Constant" })
hi(0, "NavicIconsConstructor", { link = "@constructor" })
hi(0, "NavicIconsEnum", { link = "Type" })
hi(0, "NavicIconsEnumMember", { link = "Constant" })
hi(0, "NavicIconsEvent", { link = "Structure" })
hi(0, "NavicIconsField", { link = "@variable.member" })
hi(0, "NavicIconsFile", { link = "Directory" })
hi(0, "NavicIconsFunction", { link = "Function" })
hi(0, "NavicIconsInterface", { link = "Type" })
hi(0, "NavicIconsKey", { link = "Identifier" })
hi(0, "NavicIconsMethod", { link = "@function.method" })
hi(0, "NavicIconsModule", { link = "@module" })
hi(0, "NavicIconsNamespace", { link = "@module" })
hi(0, "NavicIconsNull", { link = "Type" })
hi(0, "NavicIconsNumber", { link = "Number" })
hi(0, "NavicIconsObject", { link = "Type" })
hi(0, "NavicIconsOperator", { link = "Operator" })
hi(0, "NavicIconsPackage", { link = "@module" })
hi(0, "NavicIconsProperty", { link = "@property" })
hi(0, "NavicIconsString", { link = "String" })
hi(0, "NavicIconsStruct", { link = "Structure" })
hi(0, "NavicIconsTypeParameter", { link = "Type" })
hi(0, "NavicIconsVariable", { link = "@variable" })
hi(0, "NavicSeparator", { fg = "#cdc6a7" })
hi(0, "NavicText", { fg = "#cdc6a7" })
hi(0, "NeoTreeGitAdded", { fg = "#66855a" })
hi(0, "NeoTreeGitConflict", { fg = "#c92c27" })
hi(0, "NeoTreeGitDeleted", { fg = "#b12d33" })
hi(0, "NeoTreeGitModified", { fg = "#cc944f" })
hi(0, "NeoTreeGitStaged", { fg = "#66855a" })
hi(0, "NeoTreeIndentMarker", { link = "NonText" })
hi(0, "NeoTreeModified", { link = "String" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#d5b273" })
hi(0, "NeoTreeTabActive", { link = "TabLineSel" })
hi(0, "NeoTreeTabInactive", { link = "TabLine" })
hi(0, "NeoTreeTabSeparatorActive", { link = "NeoTreeTabActive" })
hi(0, "NeoTreeTabSeparatorInactive", { link = "NeoTreeTabInactive" })
hi(0, "NeogitBranch", { bold = true, fg = "#d15767" })
hi(0, "NeogitBranchHead", { bold = true, fg = "#d15767", underline = true })
hi(0, "NeogitChangeAdded", { bold = true, fg = "#6d8a49", italic = true })
hi(0, "NeogitChangeCopied", { bold = true, fg = "#8d764a", italic = true })
hi(0, "NeogitChangeDeleted", { bold = true, fg = "#a1211f", italic = true })
hi(0, "NeogitChangeModified", { bold = true, fg = "#ab4452", italic = true })
hi(0, "NeogitChangeNewFile", { bold = true, fg = "#6d8a49", italic = true })
hi(0, "NeogitChangeRenamed", { bold = true, fg = "#ab4452", italic = true })
hi(0, "NeogitChangeUnmerged", { bold = true, fg = "#ad4553", italic = true })
hi(0, "NeogitChangeUpdated", { bold = true, fg = "#598598", italic = true })
hi(0, "NeogitCommitViewHeader", { bg = "#948f85", fg = "#110f1a" })
hi(0, "NeogitDiffAdd", { bg = "#343434", fg = "#6d8a49" })
hi(0, "NeogitDiffAddCursor", { bg = "#282828", fg = "#88aa5b" })
hi(0, "NeogitDiffAddHighlight", { bg = "#343434" })
hi(0, "NeogitDiffAdditions", { fg = "#6d8a49" })
hi(0, "NeogitDiffContext", { bg = "#282828" })
hi(0, "NeogitDiffContextCursor", { bg = "#282828" })
hi(0, "NeogitDiffContextHighlight", { bg = "#2b2b2b" })
hi(0, "NeogitDiffDelete", { bg = "#333333", fg = "#a1211f" })
hi(0, "NeogitDiffDeleteCursor", { bg = "#282828", fg = "#c92c27" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#333333" })
hi(0, "NeogitDiffDeletions", { fg = "#a1211f" })
hi(0, "NeogitDiffHeader", { bg = "#3d3d3d", bold = true, fg = "#d15767" })
hi(0, "NeogitDiffHeaderHighlight", { bg = "#3d3d3d", bold = true, fg = "#6ea4ba" })
hi(0, "NeogitFilePath", { fg = "#d15767", italic = true })
hi(0, "NeogitFloatHeader", { bg = "#242424", bold = true })
hi(0, "NeogitFloatHeaderHighlight", { bg = "#333333", bold = true, fg = "#b0935e" })
hi(0, "NeogitGraphAuthor", { fg = "#6ea4ba" })
hi(0, "NeogitGraphBlue", { fg = "#d15767" })
hi(0, "NeogitGraphBoldBlue", { bold = true, fg = "#d15767" })
hi(0, "NeogitGraphBoldCyan", { bold = true, fg = "#b0935e" })
hi(0, "NeogitGraphBoldGray", { bold = true, fg = "#6a6a6a" })
hi(0, "NeogitGraphBoldGreen", { bold = true, fg = "#88aa5b" })
hi(0, "NeogitGraphBoldOrange", { bold = true, fg = "#6ea4ba" })
hi(0, "NeogitGraphBoldPurple", { bold = true, fg = "#d15767" })
hi(0, "NeogitGraphBoldRed", { bold = true, fg = "#c92c27" })
hi(0, "NeogitGraphBoldWhite", { bold = true, fg = "#ebebeb" })
hi(0, "NeogitGraphBoldYellow", { bold = true, fg = "#d15767" })
hi(0, "NeogitGraphCyan", { fg = "#b0935e" })
hi(0, "NeogitGraphGray", { fg = "#6a6a6a" })
hi(0, "NeogitGraphGreen", { fg = "#88aa5b" })
hi(0, "NeogitGraphOrange", { fg = "#6ea4ba" })
hi(0, "NeogitGraphPurple", { fg = "#d15767" })
hi(0, "NeogitGraphRed", { fg = "#c92c27" })
hi(0, "NeogitGraphWhite", { fg = "#ebebeb" })
hi(0, "NeogitGraphYellow", { fg = "#d15767" })
hi(0, "NeogitHunkHeader", { fg = "#708bc5" })
hi(0, "NeogitHunkHeaderCursor", { bg = "#c5a0a3", bold = true, fg = "#110f1a" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#2b2b2b", fg = "#e5925d" })
hi(0, "NeogitHunkMergeHeader", { bg = "#7f7f7f", bold = true, fg = "#20202a" })
hi(0, "NeogitHunkMergeHeaderCursor", { bg = "#948f85", bold = true, fg = "#110f1a" })
hi(0, "NeogitHunkMergeHeaderHighlight", { bg = "#948f85", bold = true, fg = "#110f1a" })
hi(0, "NeogitPopupActionKey", { fg = "#d15767" })
hi(0, "NeogitPopupBold", { bold = true })
hi(0, "NeogitPopupConfigKey", { fg = "#d15767" })
hi(0, "NeogitPopupOptionKey", { fg = "#d15767" })
hi(0, "NeogitPopupSwitchKey", { fg = "#d15767" })
hi(0, "NeogitRemote", { bold = true, fg = "#88aa5b" })
hi(0, "NeogitSectionHeader", { bold = true, fg = "#ab4452" })
hi(0, "NeogitTagDistance", { fg = "#b0935e" })
hi(0, "NeogitTagName", { fg = "#d15767" })
hi(0, "NeogitUnmergedInto", { bold = true, fg = "#ab4452" })
hi(0, "NeogitUnpulledFrom", { bold = true, fg = "#ab4452" })
hi(0, "NeogitUnpushedTo", { bold = true, fg = "#ab4452" })
hi(0, "NoiceAttr119", { bold = true, fg = "#e7913b" })
hi(0, "NoiceAttr121", { fg = "#c92c27" })
hi(0, "NoiceAttr219", { bg = "#1c1c1c", fg = "#b7af83" })
hi(0, "NoiceAttr91", { bg = "#1c1c1c", fg = "#b7af83" })
hi(0, "NoiceFormatProgressDone", { bg = "#465159", fg = "#cdc6a7" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { fg = "#46455f" })
hi(0, "Normal", { bg = "#242424", fg = "#cdc6a7" })
hi(0, "NormalFloat", { bg = "#1c1c1c", fg = "#b7af83" })
hi(0, "NormalNC", { link = "Normal" })
hi(0, "NotifyBackground", { bg = "#242424" })
hi(0, "NotifyDEBUGBorder", { link = "Debug" })
hi(0, "NotifyDEBUGIcon", { link = "Debug" })
hi(0, "NotifyDEBUGTitle", { link = "Debug" })
hi(0, "NotifyERRORBorder", { link = "DiagnosticError" })
hi(0, "NotifyERRORIcon", { link = "DiagnosticError" })
hi(0, "NotifyERRORTitle", { link = "DiagnosticError" })
hi(0, "NotifyHINTBorder", { link = "DiagnosticHint" })
hi(0, "NotifyHINTIcon", { link = "DiagnosticHint" })
hi(0, "NotifyHINTTitle", { link = "DiagnosticHint" })
hi(0, "NotifyINFOBorder", { link = "DiagnosticInfo" })
hi(0, "NotifyINFOIcon", { link = "DiagnosticInfo" })
hi(0, "NotifyINFOTitle", { link = "DiagnosticInfo" })
hi(0, "NotifyTRACEBorder", { link = "Comment" })
hi(0, "NotifyTRACEIcon", { link = "Comment" })
hi(0, "NotifyTRACETitle", { link = "Comment" })
hi(0, "NotifyWARNBorder", { link = "DiagnosticWarn" })
hi(0, "NotifyWARNIcon", { link = "DiagnosticWarn" })
hi(0, "NotifyWARNTitle", { link = "DiagnosticWarn" })
hi(0, "Number", { fg = "#c06e8a" })
hi(0, "NvimInternalError", { bg = "#dd6254", ctermbg = 9, ctermfg = 9, fg = "#d82e24" })
hi(0, "NvimTreeCombinedHL8f967543afe85bf9bf45243a17a549b5549efd1976614dd9a76468b4239b4200", { fg = "#6ea4ba", italic = true })
hi(0, "NvimTreeCombinedHLba30d17e77ba9ffb01a002a06457713a840aa4cc31b74d845b797031eb0a60f6", { fg = "#6ea4ba", italic = true })
hi(0, "NvimTreeCombinedHLe292ba741725fba2a6e08de1418f742f3c6f92e3d113c9273dca3c10385b02cc", { fg = "#6ea4ba", italic = true })
hi(0, "NvimTreeExecFile", { bold = true, fg = "#88aa5b" })
hi(0, "NvimTreeFolderIcon", { ctermfg = 12, fg = "#7284a0" })
hi(0, "NvimTreeGitDeleted", { fg = "#b12d33" })
hi(0, "NvimTreeGitDeletedIcon", { link = "NvimTreeGitDeleted" })
hi(0, "NvimTreeGitDirty", { fg = "#cc944f" })
hi(0, "NvimTreeGitDirtyIcon", { link = "NvimTreeGitDirty" })
hi(0, "NvimTreeGitNew", { fg = "#66855a" })
hi(0, "NvimTreeGitNewIcon", { link = "NvimTreeGitNew" })
hi(0, "NvimTreeGitStaged", { fg = "#66855a" })
hi(0, "NvimTreeGitStagedIcon", { link = "NvimTreeGitStaged" })
hi(0, "NvimTreeImageFile", { fg = "#d15767" })
hi(0, "NvimTreeOpenedFile", { fg = "#6ea4ba", italic = true })
hi(0, "NvimTreeOpenedHL", { link = "NvimTreeOpenedFile" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#d5b273" })
hi(0, "NvimTreeSpecialFile", { fg = "#6ea4ba" })
hi(0, "NvimTreeSymlink", { link = "Type" })
hi(0, "NvimTreeWindowPicker", { bg = "#1f1f1f", bold = true, fg = "#6ea4ba" })
hi(0, "Operator", { fg = "#b0935e" })
hi(0, "Pmenu", { bg = "#353536", fg = "#cdc6a7" })
hi(0, "PmenuSbar", { bg = "#353536" })
hi(0, "PmenuSel", { bg = "#465159" })
hi(0, "PmenuThumb", { bg = "#465159" })
hi(0, "PreProc", { fg = "#d15767" })
hi(0, "Question", { link = "MoreMsg" })
hi(0, "QuickFixLine", { bg = "#2f2f2f" })
hi(0, "RainbowDelimiterBlue", { ctermfg = 12, fg = "#347578" })
hi(0, "RainbowDelimiterCyan", { ctermfg = 14, fg = "#998974" })
hi(0, "RainbowDelimiterGreen", { ctermfg = 10, fg = "#588e5a" })
hi(0, "RainbowDelimiterOrange", { ctermfg = 15, fg = "#b95724" })
hi(0, "RainbowDelimiterRed", { ctermfg = 9, fg = "#af251d" })
hi(0, "RainbowDelimiterViolet", { ctermfg = 13, fg = "#a15176" })
hi(0, "RainbowDelimiterYellow", { ctermfg = 11, fg = "#c08b2f" })
hi(0, "RedrawDebugClear", { bg = "#685935", ctermbg = 11, ctermfg = 0 })
hi(0, "RedrawDebugComposed", { bg = "#2e5336", ctermbg = 10, ctermfg = 0 })
hi(0, "RedrawDebugRecompose", { bg = "#4f1e1d", ctermbg = 9, ctermfg = 0 })
hi(0, "Removed", { ctermfg = 9, fg = "#e6b0aa" })
hi(0, "SagaActionTitle", { bg = "#608178", fg = "#020202" })
hi(0, "SagaBeacon", { bg = "#a66471" })
hi(0, "SagaButton", { fg = "#5a857a" })
hi(0, "SagaCount", { bg = "#868686", bold = true, fg = "#eeeeee" })
hi(0, "SagaVirtLine", { fg = "#363d3f" })
hi(0, "SatelliteCursor", { fg = "#46455f" })
hi(0, "SatelliteMark", { fg = "#cdc6a7" })
hi(0, "SatelliteSearch", { fg = "#1d4059" })
hi(0, "Search", { bg = "#465159", fg = "#cdc6a7" })
hi(0, "SignColumn", { fg = "#837b96" })
hi(0, "Special", { fg = "#6ea4ba" })
hi(0, "SpecialKey", { fg = "#837b96" })
hi(0, "SpectreBody", { link = "String" })
hi(0, "SpectreBorder", { link = "Comment" })
hi(0, "SpectreDir", { link = "Comment" })
hi(0, "SpectreFile", { link = "Keyword" })
hi(0, "SpectreHeader", { link = "Comment" })
hi(0, "SpectreReplace", { link = "DiffDelete" })
hi(0, "SpectreSearch", { link = "DiffChange" })
hi(0, "SpellBad", { sp = "#e82424", undercurl = true })
hi(0, "SpellCap", { sp = "#ff9e3b", undercurl = true })
hi(0, "SpellLocal", { sp = "#ff9e3b", undercurl = true })
hi(0, "SpellRare", { sp = "#ff9e3b", undercurl = true })
hi(0, "Statement", { bold = true, fg = "#8471a5" })
hi(0, "StatusLine", { bg = "#1c1c1c", fg = "#b7af83" })
hi(0, "StatusLineNC", { bg = "#1c1c1c", fg = "#46455f" })
hi(0, "String", { fg = "#88aa5b" })
hi(0, "Substitute", { bg = "#a36863", fg = "#cdc6a7" })
hi(0, "TabLine", { bg = "#1c1c1c", fg = "#837b96" })
hi(0, "TabLineFill", { bg = "#242424" })
hi(0, "TabLineSel", { bg = "#2f2f2f", fg = "#b7af83" })
hi(0, "TailwindConceal", { fg = "#3bc3ff" })
hi(0, "TelescopeBorder", { bg = "#242424", fg = "#46455f" })
hi(0, "TelescopeResultsClass", { link = "Structure" })
hi(0, "TelescopeResultsField", { link = "@field" })
hi(0, "TelescopeResultsMethod", { link = "Function" })
hi(0, "TelescopeResultsStruct", { link = "Structure" })
hi(0, "TelescopeResultsVariable", { link = "@variable" })
hi(0, "TelescopeSelection", { link = "CursorLine" })
hi(0, "TelescopeSelectionCaret", { link = "CursorLineNr" })
hi(0, "TelescopeTitle", { fg = "#837b96" })
hi(0, "Title", { bold = true, fg = "#708bc5" })
hi(0, "Todo", { bg = "#858585", bold = true, fg = "#14253b" })
hi(0, "TodoBgCURRENT", { bg = "#e9b180", bold = true, fg = "#110f1a" })
hi(0, "TodoBgFIX", { bg = "#c76357", bold = true, fg = "#cdc6a7" })
hi(0, "TodoBgHACK", { bg = "#e9b180", bold = true, fg = "#110f1a" })
hi(0, "TodoBgIMP", { bg = "#c76357", bold = true, fg = "#cdc6a7" })
hi(0, "TodoBgNOTE", { bg = "#8f9190", bold = true, fg = "#110f1a" })
hi(0, "TodoBgPERF", { bg = "#d4ccbf", bold = true, fg = "#110f1a" })
hi(0, "TodoBgSECURITY", { bg = "#c76357", bold = true, fg = "#cdc6a7" })
hi(0, "TodoBgTEST", { bg = "#d4ccbf", bold = true, fg = "#110f1a" })
hi(0, "TodoBgTODO", { bg = "#858585", bold = true, fg = "#cdc6a7" })
hi(0, "TodoBgUSERINPUT", { bg = "#c76357", bold = true, fg = "#cdc6a7" })
hi(0, "TodoBgVULNERABILITY", { bg = "#c76357", bold = true, fg = "#cdc6a7" })
hi(0, "TodoBgWARN", { bg = "#e9b180", bold = true, fg = "#110f1a" })
hi(0, "TodoFgCURRENT", { fg = "#e7913b" })
hi(0, "TodoFgFIX", { fg = "#c92c27" })
hi(0, "TodoFgHACK", { fg = "#e7913b" })
hi(0, "TodoFgIMP", { fg = "#c92c27" })
hi(0, "TodoFgNOTE", { fg = "#5a857a" })
hi(0, "TodoFgPERF", { fg = "#d5b273" })
hi(0, "TodoFgSECURITY", { fg = "#c92c27" })
hi(0, "TodoFgTEST", { fg = "#d5b273" })
hi(0, "TodoFgTODO", { fg = "#557585" })
hi(0, "TodoFgUSERINPUT", { fg = "#c92c27" })
hi(0, "TodoFgVULNERABILITY", { fg = "#c92c27" })
hi(0, "TodoFgWARN", { fg = "#e7913b" })
hi(0, "TodoSignCURRENT", { fg = "#e7913b" })
hi(0, "TodoSignFIX", { fg = "#c92c27" })
hi(0, "TodoSignHACK", { fg = "#e7913b" })
hi(0, "TodoSignIMP", { fg = "#c92c27" })
hi(0, "TodoSignNOTE", { fg = "#5a857a" })
hi(0, "TodoSignPERF", { fg = "#d5b273" })
hi(0, "TodoSignSECURITY", { fg = "#c92c27" })
hi(0, "TodoSignTEST", { fg = "#d5b273" })
hi(0, "TodoSignTODO", { fg = "#557585" })
hi(0, "TodoSignUSERINPUT", { fg = "#c92c27" })
hi(0, "TodoSignVULNERABILITY", { fg = "#c92c27" })
hi(0, "TodoSignWARN", { fg = "#e7913b" })
hi(0, "ToggleTerm1FloatBorder", { link = "Normal" })
hi(0, "ToggleTerm1NormalFloat", { link = "Normal" })
hi(0, "ToggleTerm99FloatBorder", { link = "Normal" })
hi(0, "ToggleTerm99NormalFloat", { link = "Normal" })
hi(0, "TreesitterContext", { link = "Folded" })
hi(0, "TreesitterContextLineNumber", { fg = "#837b96" })
hi(0, "TroubleIndent", { fg = "#46455f" })
hi(0, "TroublePos", { fg = "#837b96" })
hi(0, "Type", { fg = "#6a998f" })
hi(0, "UfoFoldedBg", { bg = "#2f2f2f" })
hi(0, "UfoFoldedFg", { fg = "#cdc6a7" })
hi(0, "Underlined", { fg = "#6ea4ba", underline = true })
hi(0, "Visual", { bg = "#353536" })
hi(0, "WarningMsg", { fg = "#e7913b" })
hi(0, "Whitespace", { fg = "#46455f" })
hi(0, "WildMenu", { link = "Pmenu" })
hi(0, "WinBar", { fg = "#b7af83" })
hi(0, "WinBarNC", { fg = "#b7af83" })
hi(0, "WinSeparator", { fg = "#07050e" })
hi(0, "WinShiftCursorLineNr", { bg = "#353536", bold = true, fg = "#e7913b" })
hi(0, "WinShiftEndOfBuffer", { bg = "#353536", fg = "#373742" })
hi(0, "WinShiftFoldColumn", { bg = "#353536", fg = "#46455f" })
hi(0, "WinShiftLineNr", { bg = "#353536", fg = "#46455f" })
hi(0, "WinShiftNormal", { bg = "#353536" })
hi(0, "WinShiftSignColumn", { bg = "#353536", fg = "#837b96" })
hi(0, "WinShiftWindowPicker", { bg = "#4796cb", bold = true, fg = "#f3f3f3" })
hi(0, "debugBreakpoint", { fg = "#6ea4ba" })
hi(0, "debugPC", { bg = "#333333" })
hi(0, "diffAdded", { fg = "#66855a" })
hi(0, "diffChanged", { fg = "#cc944f" })
hi(0, "diffDeleted", { fg = "#b12d33" })
hi(0, "diffNewFile", { fg = "#66855a" })
hi(0, "diffOldFile", { fg = "#b12d33" })
hi(0, "diffRemoved", { fg = "#b12d33" })
hi(0, "healthError", { fg = "#c92c27" })
hi(0, "healthSuccess", { fg = "#88aa5b" })
hi(0, "healthWarning", { fg = "#e7913b" })
hi(0, "htmlBold", { bold = true })
hi(0, "htmlBoldItalic", { bold = true, italic = true })
hi(0, "htmlBoldUnderline", { bold = true, underline = true })
hi(0, "htmlBoldUnderlineItalic", { bold = true, italic = true, underline = true })
hi(0, "htmlItalic", { italic = true })
hi(0, "htmlStrike", { strikethrough = true })
hi(0, "htmlUnderline", { underline = true })
hi(0, "htmlUnderlineItalic", { italic = true, underline = true })
hi(0, "lCursor", { link = "Cursor" })
hi(0, "lualine_a_18_command", { bg = "#e1c28a", fg = "#2a2a2a" })
hi(0, "lualine_a_18_inactive", { bg = "#4c5861", fg = "#a7a7a7" })
hi(0, "lualine_a_18_insert", { bg = "#96b66e", fg = "#2a2a2a" })
hi(0, "lualine_a_18_normal", { bg = "#4c5861", fg = "#a7a7a7" })
hi(0, "lualine_a_18_replace", { bg = "#c37f95", fg = "#2a2a2a" })
hi(0, "lualine_a_18_terminal", { bg = "#e1c28a", fg = "#2a2a2a" })
hi(0, "lualine_a_18_visual", { bg = "#81afc3", fg = "#2a2a2a" })
hi(0, "lualine_a_19_command", { bg = "#b3ada1", fg = "#110f1a" })
hi(0, "lualine_a_19_inactive", { bg = "#1c1c1c", fg = "#b7af83" })
hi(0, "lualine_a_19_insert", { bg = "#adb8a1", fg = "#110f1a" })
hi(0, "lualine_a_19_normal", { bg = "#9ba3b2", fg = "#07050e" })
hi(0, "lualine_a_19_replace", { bg = "#e9b495", fg = "#110f1a" })
hi(0, "lualine_a_19_terminal", { bg = "#9ba3b2", fg = "#07050e" })
hi(0, "lualine_a_19_visual", { bg = "#919191", fg = "#110f1a" })
hi(0, "lualine_a_7_command", { bg = "#e1c28a", fg = "#2a2a2a" })
hi(0, "lualine_a_7_inactive", { bg = "#4c5861", fg = "#a7a7a7" })
hi(0, "lualine_a_7_insert", { bg = "#96b66e", fg = "#2a2a2a" })
hi(0, "lualine_a_7_normal", { bg = "#4c5861", fg = "#a7a7a7" })
hi(0, "lualine_a_7_replace", { bg = "#c37f95", fg = "#2a2a2a" })
hi(0, "lualine_a_7_terminal", { bg = "#e1c28a", fg = "#2a2a2a" })
hi(0, "lualine_a_7_visual", { bg = "#81afc3", fg = "#2a2a2a" })
hi(0, "lualine_a_8_command", { bg = "#b3ada1", fg = "#110f1a" })
hi(0, "lualine_a_8_inactive", { bg = "#1c1c1c", fg = "#b7af83" })
hi(0, "lualine_a_8_insert", { bg = "#adb8a1", fg = "#110f1a" })
hi(0, "lualine_a_8_normal", { bg = "#9ba3b2", fg = "#07050e" })
hi(0, "lualine_a_8_replace", { bg = "#e9b495", fg = "#110f1a" })
hi(0, "lualine_a_8_terminal", { bg = "#9ba3b2", fg = "#07050e" })
hi(0, "lualine_a_8_visual", { bg = "#919191", fg = "#110f1a" })
hi(0, "lualine_a_command", { bg = "#e1c28a", bold = true, fg = "#2a2a2a" })
hi(0, "lualine_a_inactive", { bg = "#4c5861", bold = true, fg = "#a7a7a7" })
hi(0, "lualine_a_insert", { bg = "#96b66e", bold = true, fg = "#2a2a2a" })
hi(0, "lualine_a_normal", { bg = "#4c5861", bold = true, fg = "#a7a7a7" })
hi(0, "lualine_a_replace", { bg = "#c37f95", bold = true, fg = "#2a2a2a" })
hi(0, "lualine_a_terminal", { bg = "#e1c28a", bold = true, fg = "#2a2a2a" })
hi(0, "lualine_a_visual", { bg = "#81afc3", bold = true, fg = "#2a2a2a" })
hi(0, "lualine_b_17_command", { bg = "#272727", bold = true, fg = "#e9c47d" })
hi(0, "lualine_b_17_inactive", { bg = "#272727", bold = true, fg = "#667a89" })
hi(0, "lualine_b_17_insert", { bg = "#272727", bold = true, fg = "#94bb63" })
hi(0, "lualine_b_17_normal", { bg = "#272727", bold = true, fg = "#667a89" })
hi(0, "lualine_b_17_replace", { bg = "#272727", bold = true, fg = "#d17997" })
hi(0, "lualine_b_17_terminal", { bg = "#272727", bold = true, fg = "#e9c47d" })
hi(0, "lualine_b_17_visual", { bg = "#272727", bold = true, fg = "#78b3cd" })
hi(0, "lualine_b_18_command", { bg = "#242424", bold = true, fg = "#b0935e" })
hi(0, "lualine_b_18_inactive", { bg = "#1c1c1c", bold = true, fg = "#b7af83" })
hi(0, "lualine_b_18_insert", { bg = "#242424", bold = true, fg = "#88aa5b" })
hi(0, "lualine_b_18_normal", { bg = "#2b2b2b", bold = true, fg = "#708bc5" })
hi(0, "lualine_b_18_replace", { bg = "#242424", bold = true, fg = "#e5925d" })
hi(0, "lualine_b_18_terminal", { bg = "#2b2b2b", bold = true, fg = "#708bc5" })
hi(0, "lualine_b_18_visual", { bg = "#242424", bold = true, fg = "#8471a5" })
hi(0, "lualine_b_6_command", { bg = "#272727", bold = true, fg = "#e9c47d" })
hi(0, "lualine_b_6_inactive", { bg = "#272727", bold = true, fg = "#667a89" })
hi(0, "lualine_b_6_insert", { bg = "#272727", bold = true, fg = "#94bb63" })
hi(0, "lualine_b_6_normal", { bg = "#272727", bold = true, fg = "#667a89" })
hi(0, "lualine_b_6_replace", { bg = "#272727", bold = true, fg = "#d17997" })
hi(0, "lualine_b_6_terminal", { bg = "#272727", bold = true, fg = "#e9c47d" })
hi(0, "lualine_b_6_visual", { bg = "#272727", bold = true, fg = "#78b3cd" })
hi(0, "lualine_b_7_command", { bg = "#242424", bold = true, fg = "#b0935e" })
hi(0, "lualine_b_7_inactive", { bg = "#1c1c1c", bold = true, fg = "#b7af83" })
hi(0, "lualine_b_7_insert", { bg = "#242424", bold = true, fg = "#88aa5b" })
hi(0, "lualine_b_7_normal", { bg = "#2b2b2b", bold = true, fg = "#708bc5" })
hi(0, "lualine_b_7_replace", { bg = "#242424", bold = true, fg = "#e5925d" })
hi(0, "lualine_b_7_terminal", { bg = "#2b2b2b", bold = true, fg = "#708bc5" })
hi(0, "lualine_b_7_visual", { bg = "#242424", bold = true, fg = "#8471a5" })
hi(0, "lualine_b_command", { bg = "#272727", fg = "#e9c47d" })
hi(0, "lualine_b_inactive", { bg = "#272727", fg = "#667a89" })
hi(0, "lualine_b_insert", { bg = "#272727", fg = "#94bb63" })
hi(0, "lualine_b_normal", { bg = "#272727", fg = "#667a89" })
hi(0, "lualine_b_replace", { bg = "#272727", fg = "#d17997" })
hi(0, "lualine_b_terminal", { bg = "#272727", fg = "#e9c47d" })
hi(0, "lualine_b_visual", { bg = "#272727", fg = "#78b3cd" })
hi(0, "lualine_c_16_command", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_16_inactive", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_16_insert", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_16_normal", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_16_replace", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_16_terminal", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_16_visual", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_17_command", { bg = "#2f2f2f", fg = "#88ae52" })
hi(0, "lualine_c_17_inactive", { bg = "#1c1c1c", fg = "#88ae52" })
hi(0, "lualine_c_17_insert", { bg = "#2f2f2f", fg = "#88ae52" })
hi(0, "lualine_c_17_normal", { bg = "#2f2f2f", fg = "#88ae52" })
hi(0, "lualine_c_17_replace", { bg = "#2f2f2f", fg = "#88ae52" })
hi(0, "lualine_c_17_terminal", { bg = "#2f2f2f", fg = "#88ae52" })
hi(0, "lualine_c_17_visual", { bg = "#2f2f2f", fg = "#88ae52" })
hi(0, "lualine_c_5_command", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_5_inactive", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_5_insert", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_5_normal", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_5_replace", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_5_terminal", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_5_visual", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_6_command", { bg = "#2f2f2f", fg = "#88ae52" })
hi(0, "lualine_c_6_inactive", { bg = "#1c1c1c", fg = "#88ae52" })
hi(0, "lualine_c_6_insert", { bg = "#2f2f2f", fg = "#88ae52" })
hi(0, "lualine_c_6_normal", { bg = "#2f2f2f", fg = "#88ae52" })
hi(0, "lualine_c_6_replace", { bg = "#2f2f2f", fg = "#88ae52" })
hi(0, "lualine_c_6_terminal", { bg = "#2f2f2f", fg = "#88ae52" })
hi(0, "lualine_c_6_visual", { bg = "#2f2f2f", fg = "#88ae52" })
hi(0, "lualine_c_command", { bg = "#1e1e1e", fg = "#e0d9b7" })
hi(0, "lualine_c_diff_added_0_command", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_diff_added_0_inactive", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_diff_added_0_insert", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_diff_added_0_normal", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_diff_added_0_replace", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_diff_added_0_terminal", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_diff_added_0_visual", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_diff_added_command", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_diff_added_inactive", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_diff_added_insert", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_diff_added_normal", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_diff_added_replace", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_diff_added_terminal", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_diff_added_visual", { bg = "#1e1e1e", fg = "#99c65b" })
hi(0, "lualine_c_diff_modified_0_command", { bg = "#1e1e1e", fg = "#f8c272" })
hi(0, "lualine_c_diff_modified_0_inactive", { bg = "#1e1e1e", fg = "#f8c272" })
hi(0, "lualine_c_diff_modified_0_insert", { bg = "#1e1e1e", fg = "#f8c272" })
hi(0, "lualine_c_diff_modified_0_normal", { bg = "#1e1e1e", fg = "#f8c272" })
hi(0, "lualine_c_diff_modified_0_replace", { bg = "#1e1e1e", fg = "#f8c272" })
hi(0, "lualine_c_diff_modified_0_terminal", { bg = "#1e1e1e", fg = "#f8c272" })
hi(0, "lualine_c_diff_modified_0_visual", { bg = "#1e1e1e", fg = "#f8c272" })
hi(0, "lualine_c_diff_modified_command", { bg = "#1e1e1e", fg = "#f8c272" })
hi(0, "lualine_c_diff_modified_inactive", { bg = "#1e1e1e", fg = "#f8c272" })
hi(0, "lualine_c_diff_modified_insert", { bg = "#1e1e1e", fg = "#f8c272" })
hi(0, "lualine_c_diff_modified_normal", { bg = "#1e1e1e", fg = "#f8c272" })
hi(0, "lualine_c_diff_modified_replace", { bg = "#1e1e1e", fg = "#f8c272" })
hi(0, "lualine_c_diff_modified_terminal", { bg = "#1e1e1e", fg = "#f8c272" })
hi(0, "lualine_c_diff_modified_visual", { bg = "#1e1e1e", fg = "#f8c272" })
hi(0, "lualine_c_diff_removed_0_command", { bg = "#1e1e1e", fg = "#fc5965" })
hi(0, "lualine_c_diff_removed_0_inactive", { bg = "#1e1e1e", fg = "#fc5965" })
hi(0, "lualine_c_diff_removed_0_insert", { bg = "#1e1e1e", fg = "#fc5965" })
hi(0, "lualine_c_diff_removed_0_normal", { bg = "#1e1e1e", fg = "#fc5965" })
hi(0, "lualine_c_diff_removed_0_replace", { bg = "#1e1e1e", fg = "#fc5965" })
hi(0, "lualine_c_diff_removed_0_terminal", { bg = "#1e1e1e", fg = "#fc5965" })
hi(0, "lualine_c_diff_removed_0_visual", { bg = "#1e1e1e", fg = "#fc5965" })
hi(0, "lualine_c_diff_removed_command", { bg = "#1e1e1e", fg = "#fc5965" })
hi(0, "lualine_c_diff_removed_inactive", { bg = "#1e1e1e", fg = "#fc5965" })
hi(0, "lualine_c_diff_removed_insert", { bg = "#1e1e1e", fg = "#fc5965" })
hi(0, "lualine_c_diff_removed_normal", { bg = "#1e1e1e", fg = "#fc5965" })
hi(0, "lualine_c_diff_removed_replace", { bg = "#1e1e1e", fg = "#fc5965" })
hi(0, "lualine_c_diff_removed_terminal", { bg = "#1e1e1e", fg = "#fc5965" })
hi(0, "lualine_c_diff_removed_visual", { bg = "#1e1e1e", fg = "#fc5965" })
hi(0, "lualine_c_inactive", { bg = "#1e1e1e", fg = "#e0d9b7" })
hi(0, "lualine_c_insert", { bg = "#1e1e1e", fg = "#e0d9b7" })
hi(0, "lualine_c_normal", { bg = "#1e1e1e", fg = "#e0d9b7" })
hi(0, "lualine_c_replace", { bg = "#1e1e1e", fg = "#e0d9b7" })
hi(0, "lualine_c_terminal", { bg = "#1e1e1e", fg = "#e0d9b7" })
hi(0, "lualine_c_visual", { bg = "#1e1e1e", fg = "#e0d9b7" })
hi(0, "lualine_transitional_lualine_a_7_command_to_lualine_b_6_command", { bg = "#272727", fg = "#e9c47d" })
hi(0, "lualine_transitional_lualine_a_7_insert_to_lualine_b_6_insert", { bg = "#262626", fg = "#94bb63" })
hi(0, "lualine_transitional_lualine_a_7_insert_to_lualine_c_insert", { bg = "#1d1d1d", fg = "#94bb63" })
hi(0, "lualine_transitional_lualine_a_7_normal_to_lualine_b_6_normal", { bg = "#272727", fg = "#4a5c69" })
hi(0, "lualine_transitional_lualine_a_7_normal_to_lualine_c_normal", { bg = "#1e1e1e", fg = "#4a5c69" })
hi(0, "lualine_transitional_lualine_a_7_terminal_to_lualine_b_6_terminal", { bg = "#262626", fg = "#e9c57d" })
hi(0, "lualine_transitional_lualine_a_7_terminal_to_lualine_c_terminal", { bg = "#1d1d1d", fg = "#e9c57d" })
hi(0, "lualine_transitional_lualine_a_7_visual_to_lualine_b_6_visual", { bg = "#272727", fg = "#78b3cd" })
hi(0, "lualine_transitional_lualine_a_8_command_to_lualine_b_7_command", { bg = "#242424", fg = "#b0935e" })
hi(0, "lualine_transitional_lualine_a_8_normal_to_lualine_b_7_normal", { bg = "#2b2b2b", fg = "#708bc5" })
hi(0, "lualine_transitional_lualine_a_8_normal_to_lualine_c_normal", { bg = "#2f2f2f", fg = "#708bc5" })
hi(0, "lualine_transitional_lualine_b_6_command_to_lualine_c_command", { bg = "#1e1e1e", fg = "#2a2a2a" })
hi(0, "lualine_transitional_lualine_b_6_insert_to_lualine_c_insert", { bg = "#1d1d1d", fg = "#222222" })
hi(0, "lualine_transitional_lualine_b_6_normal_to_lualine_c_normal", { bg = "#1e1e1e", fg = "#2a2a2a" })
hi(0, "lualine_transitional_lualine_b_6_terminal_to_lualine_c_terminal", { bg = "#1d1d1d", fg = "#222222" })
hi(0, "lualine_transitional_lualine_b_6_visual_to_lualine_c_visual", { bg = "#1e1e1e", fg = "#2a2a2a" })
hi(0, "lualine_transitional_lualine_b_7_command_to_lualine_c_normal", { bg = "#2f2f2f", fg = "#110f1a" })
hi(0, "lualine_transitional_lualine_b_7_normal_to_lualine_c_normal", { bg = "#2f2f2f", fg = "#171628" })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_c_command", { bg = "#1e1e1e", fg = "#2a2a2a" })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_c_normal", { bg = "#2f2f2f", fg = "#110f1a" })
hi(0, "lualine_transitional_lualine_b_insert_to_lualine_c_insert", { bg = "#1d1d1d", fg = "#222222" })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_normal", { bg = "#1e1e1e", fg = "#2a2a2a" })
hi(0, "lualine_transitional_lualine_b_terminal_to_lualine_c_terminal", { bg = "#1d1d1d", fg = "#222222" })
hi(0, "lualine_transitional_lualine_b_visual_to_lualine_c_visual", { bg = "#1e1e1e", fg = "#2a2a2a" })
hi(0, "lualine_transitional_lualine_z_progress_command_to_lualine_b_command", { bg = "#272727", fg = "#e9c47d" })
hi(0, "lualine_transitional_lualine_z_progress_insert_to_lualine_b_insert", { bg = "#262626", fg = "#94bb63" })
hi(0, "lualine_transitional_lualine_z_progress_normal_to_lualine_b_normal", { bg = "#272727", fg = "#4a5c69" })
hi(0, "lualine_transitional_lualine_z_progress_terminal_to_lualine_b_terminal", { bg = "#262626", fg = "#e9c57d" })
hi(0, "lualine_transitional_lualine_z_progress_visual_to_lualine_b_visual", { bg = "#272727", fg = "#78b3cd" })
hi(0, "lualine_x_10_command", { bg = "#2f2f2f", bold = true, fg = "#cdc6a7" })
hi(0, "lualine_x_10_inactive", { bg = "#1c1c1c", bold = true, fg = "#b7af83" })
hi(0, "lualine_x_10_insert", { bg = "#2f2f2f", bold = true, fg = "#cdc6a7" })
hi(0, "lualine_x_10_normal", { bg = "#2f2f2f", bold = true, fg = "#cdc6a7" })
hi(0, "lualine_x_10_replace", { bg = "#2f2f2f", bold = true, fg = "#cdc6a7" })
hi(0, "lualine_x_10_terminal", { bg = "#2f2f2f", bold = true, fg = "#cdc6a7" })
hi(0, "lualine_x_10_visual", { bg = "#2f2f2f", bold = true, fg = "#cdc6a7" })
hi(0, "lualine_x_20_command", { bg = "#1e1e1e", bold = true, fg = "#e0d9b7" })
hi(0, "lualine_x_20_inactive", { bg = "#1e1e1e", bold = true, fg = "#e0d9b7" })
hi(0, "lualine_x_20_insert", { bg = "#1e1e1e", bold = true, fg = "#e0d9b7" })
hi(0, "lualine_x_20_normal", { bg = "#1e1e1e", bold = true, fg = "#e0d9b7" })
hi(0, "lualine_x_20_replace", { bg = "#1e1e1e", bold = true, fg = "#e0d9b7" })
hi(0, "lualine_x_20_terminal", { bg = "#1e1e1e", bold = true, fg = "#e0d9b7" })
hi(0, "lualine_x_20_visual", { bg = "#1e1e1e", bold = true, fg = "#e0d9b7" })
hi(0, "lualine_x_21_command", { bg = "#2f2f2f", bold = true, fg = "#cdc6a7" })
hi(0, "lualine_x_21_inactive", { bg = "#1c1c1c", bold = true, fg = "#b7af83" })
hi(0, "lualine_x_21_insert", { bg = "#2f2f2f", bold = true, fg = "#cdc6a7" })
hi(0, "lualine_x_21_normal", { bg = "#2f2f2f", bold = true, fg = "#cdc6a7" })
hi(0, "lualine_x_21_replace", { bg = "#2f2f2f", bold = true, fg = "#cdc6a7" })
hi(0, "lualine_x_21_terminal", { bg = "#2f2f2f", bold = true, fg = "#cdc6a7" })
hi(0, "lualine_x_21_visual", { bg = "#2f2f2f", bold = true, fg = "#cdc6a7" })
hi(0, "lualine_x_9_command", { bg = "#1e1e1e", bold = true, fg = "#e0d9b7" })
hi(0, "lualine_x_9_inactive", { bg = "#1e1e1e", bold = true, fg = "#e0d9b7" })
hi(0, "lualine_x_9_insert", { bg = "#1e1e1e", bold = true, fg = "#e0d9b7" })
hi(0, "lualine_x_9_normal", { bg = "#1e1e1e", bold = true, fg = "#e0d9b7" })
hi(0, "lualine_x_9_replace", { bg = "#1e1e1e", bold = true, fg = "#e0d9b7" })
hi(0, "lualine_x_9_terminal", { bg = "#1e1e1e", bold = true, fg = "#e0d9b7" })
hi(0, "lualine_x_9_visual", { bg = "#1e1e1e", bold = true, fg = "#e0d9b7" })
hi(0, "lualine_x_copilot_disabled_command", { bg = "#1e1e1e", fg = "#6175b8" })
hi(0, "lualine_x_copilot_disabled_inactive", { bg = "#1e1e1e", fg = "#6175b8" })
hi(0, "lualine_x_copilot_disabled_insert", { bg = "#1e1e1e", fg = "#6175b8" })
hi(0, "lualine_x_copilot_disabled_normal", { bg = "#1e1e1e", fg = "#6175b8" })
hi(0, "lualine_x_copilot_disabled_replace", { bg = "#1e1e1e", fg = "#6175b8" })
hi(0, "lualine_x_copilot_disabled_terminal", { bg = "#1e1e1e", fg = "#6175b8" })
hi(0, "lualine_x_copilot_disabled_visual", { bg = "#1e1e1e", fg = "#6175b8" })
hi(0, "lualine_x_copilot_enabled_command", { bg = "#1e1e1e", fg = "#55ff7f" })
hi(0, "lualine_x_copilot_enabled_inactive", { bg = "#1e1e1e", fg = "#55ff7f" })
hi(0, "lualine_x_copilot_enabled_insert", { bg = "#1e1e1e", fg = "#55ff7f" })
hi(0, "lualine_x_copilot_enabled_normal", { bg = "#1e1e1e", fg = "#55ff7f" })
hi(0, "lualine_x_copilot_enabled_replace", { bg = "#1e1e1e", fg = "#55ff7f" })
hi(0, "lualine_x_copilot_enabled_terminal", { bg = "#1e1e1e", fg = "#55ff7f" })
hi(0, "lualine_x_copilot_enabled_visual", { bg = "#1e1e1e", fg = "#55ff7f" })
hi(0, "lualine_x_copilot_offline_command", { bg = "#1e1e1e", fg = "#ffbe75" })
hi(0, "lualine_x_copilot_offline_inactive", { bg = "#1e1e1e", fg = "#ffbe75" })
hi(0, "lualine_x_copilot_offline_insert", { bg = "#1e1e1e", fg = "#ffbe75" })
hi(0, "lualine_x_copilot_offline_normal", { bg = "#1e1e1e", fg = "#ffbe75" })
hi(0, "lualine_x_copilot_offline_replace", { bg = "#1e1e1e", fg = "#ffbe75" })
hi(0, "lualine_x_copilot_offline_terminal", { bg = "#1e1e1e", fg = "#ffbe75" })
hi(0, "lualine_x_copilot_offline_visual", { bg = "#1e1e1e", fg = "#ffbe75" })
hi(0, "lualine_x_copilot_sleep_command", { bg = "#1e1e1e", fg = "#b0bcde" })
hi(0, "lualine_x_copilot_sleep_inactive", { bg = "#1e1e1e", fg = "#b0bcde" })
hi(0, "lualine_x_copilot_sleep_insert", { bg = "#1e1e1e", fg = "#b0bcde" })
hi(0, "lualine_x_copilot_sleep_normal", { bg = "#1e1e1e", fg = "#b0bcde" })
hi(0, "lualine_x_copilot_sleep_replace", { bg = "#1e1e1e", fg = "#b0bcde" })
hi(0, "lualine_x_copilot_sleep_terminal", { bg = "#1e1e1e", fg = "#b0bcde" })
hi(0, "lualine_x_copilot_sleep_visual", { bg = "#1e1e1e", fg = "#b0bcde" })
hi(0, "lualine_x_copilot_spinner_command", { bg = "#1e1e1e", fg = "#6175b8" })
hi(0, "lualine_x_copilot_spinner_inactive", { bg = "#1e1e1e", fg = "#6175b8" })
hi(0, "lualine_x_copilot_spinner_insert", { bg = "#1e1e1e", fg = "#6175b8" })
hi(0, "lualine_x_copilot_spinner_normal", { bg = "#1e1e1e", fg = "#6175b8" })
hi(0, "lualine_x_copilot_spinner_replace", { bg = "#1e1e1e", fg = "#6175b8" })
hi(0, "lualine_x_copilot_spinner_terminal", { bg = "#1e1e1e", fg = "#6175b8" })
hi(0, "lualine_x_copilot_spinner_visual", { bg = "#1e1e1e", fg = "#6175b8" })
hi(0, "lualine_x_copilot_unknown_command", { bg = "#1e1e1e", fg = "#ff5456" })
hi(0, "lualine_x_copilot_unknown_inactive", { bg = "#1e1e1e", fg = "#ff5456" })
hi(0, "lualine_x_copilot_unknown_insert", { bg = "#1e1e1e", fg = "#ff5456" })
hi(0, "lualine_x_copilot_unknown_normal", { bg = "#1e1e1e", fg = "#ff5456" })
hi(0, "lualine_x_copilot_unknown_replace", { bg = "#1e1e1e", fg = "#ff5456" })
hi(0, "lualine_x_copilot_unknown_terminal", { bg = "#1e1e1e", fg = "#ff5456" })
hi(0, "lualine_x_copilot_unknown_visual", { bg = "#1e1e1e", fg = "#ff5456" })
hi(0, "lualine_x_diagnostics_error_0_command", { bg = "#1e1e1e", fg = "#c92c27" })
hi(0, "lualine_x_diagnostics_error_0_inactive", { bg = "#1e1e1e", fg = "#c92c27" })
hi(0, "lualine_x_diagnostics_error_0_insert", { bg = "#1e1e1e", fg = "#c92c27" })
hi(0, "lualine_x_diagnostics_error_0_normal", { bg = "#1e1e1e", fg = "#c92c27" })
hi(0, "lualine_x_diagnostics_error_0_replace", { bg = "#1e1e1e", fg = "#c92c27" })
hi(0, "lualine_x_diagnostics_error_0_terminal", { bg = "#1e1e1e", fg = "#c92c27" })
hi(0, "lualine_x_diagnostics_error_0_visual", { bg = "#1e1e1e", fg = "#c92c27" })
hi(0, "lualine_x_diagnostics_error_command", { bg = "#1e1e1e", fg = "#c92c27" })
hi(0, "lualine_x_diagnostics_error_inactive", { bg = "#1e1e1e", fg = "#c92c27" })
hi(0, "lualine_x_diagnostics_error_insert", { bg = "#1e1e1e", fg = "#c92c27" })
hi(0, "lualine_x_diagnostics_error_normal", { bg = "#1e1e1e", fg = "#c92c27" })
hi(0, "lualine_x_diagnostics_error_replace", { bg = "#1e1e1e", fg = "#c92c27" })
hi(0, "lualine_x_diagnostics_error_terminal", { bg = "#1e1e1e", fg = "#c92c27" })
hi(0, "lualine_x_diagnostics_error_visual", { bg = "#1e1e1e", fg = "#c92c27" })
hi(0, "lualine_x_diagnostics_hint_0_command", { bg = "#1e1e1e", fg = "#5a857a" })
hi(0, "lualine_x_diagnostics_hint_0_inactive", { bg = "#1e1e1e", fg = "#5a857a" })
hi(0, "lualine_x_diagnostics_hint_0_insert", { bg = "#1e1e1e", fg = "#5a857a" })
hi(0, "lualine_x_diagnostics_hint_0_normal", { bg = "#1e1e1e", fg = "#5a857a" })
hi(0, "lualine_x_diagnostics_hint_0_replace", { bg = "#1e1e1e", fg = "#5a857a" })
hi(0, "lualine_x_diagnostics_hint_0_terminal", { bg = "#1e1e1e", fg = "#5a857a" })
hi(0, "lualine_x_diagnostics_hint_0_visual", { bg = "#1e1e1e", fg = "#5a857a" })
hi(0, "lualine_x_diagnostics_hint_command", { bg = "#1e1e1e", fg = "#5a857a" })
hi(0, "lualine_x_diagnostics_hint_inactive", { bg = "#1e1e1e", fg = "#5a857a" })
hi(0, "lualine_x_diagnostics_hint_insert", { bg = "#1e1e1e", fg = "#5a857a" })
hi(0, "lualine_x_diagnostics_hint_normal", { bg = "#1e1e1e", fg = "#5a857a" })
hi(0, "lualine_x_diagnostics_hint_replace", { bg = "#1e1e1e", fg = "#5a857a" })
hi(0, "lualine_x_diagnostics_hint_terminal", { bg = "#1e1e1e", fg = "#5a857a" })
hi(0, "lualine_x_diagnostics_hint_visual", { bg = "#1e1e1e", fg = "#5a857a" })
hi(0, "lualine_x_diagnostics_info_0_command", { bg = "#1e1e1e", fg = "#557585" })
hi(0, "lualine_x_diagnostics_info_0_inactive", { bg = "#1e1e1e", fg = "#557585" })
hi(0, "lualine_x_diagnostics_info_0_insert", { bg = "#1e1e1e", fg = "#557585" })
hi(0, "lualine_x_diagnostics_info_0_normal", { bg = "#1e1e1e", fg = "#557585" })
hi(0, "lualine_x_diagnostics_info_0_replace", { bg = "#1e1e1e", fg = "#557585" })
hi(0, "lualine_x_diagnostics_info_0_terminal", { bg = "#1e1e1e", fg = "#557585" })
hi(0, "lualine_x_diagnostics_info_0_visual", { bg = "#1e1e1e", fg = "#557585" })
hi(0, "lualine_x_diagnostics_info_command", { bg = "#1e1e1e", fg = "#557585" })
hi(0, "lualine_x_diagnostics_info_inactive", { bg = "#1e1e1e", fg = "#557585" })
hi(0, "lualine_x_diagnostics_info_insert", { bg = "#1e1e1e", fg = "#557585" })
hi(0, "lualine_x_diagnostics_info_normal", { bg = "#1e1e1e", fg = "#557585" })
hi(0, "lualine_x_diagnostics_info_replace", { bg = "#1e1e1e", fg = "#557585" })
hi(0, "lualine_x_diagnostics_info_terminal", { bg = "#1e1e1e", fg = "#557585" })
hi(0, "lualine_x_diagnostics_info_visual", { bg = "#1e1e1e", fg = "#557585" })
hi(0, "lualine_x_diagnostics_warn_0_command", { bg = "#1e1e1e", fg = "#e7913b" })
hi(0, "lualine_x_diagnostics_warn_0_inactive", { bg = "#1e1e1e", fg = "#e7913b" })
hi(0, "lualine_x_diagnostics_warn_0_insert", { bg = "#1e1e1e", fg = "#e7913b" })
hi(0, "lualine_x_diagnostics_warn_0_normal", { bg = "#1e1e1e", fg = "#e7913b" })
hi(0, "lualine_x_diagnostics_warn_0_replace", { bg = "#1e1e1e", fg = "#e7913b" })
hi(0, "lualine_x_diagnostics_warn_0_terminal", { bg = "#1e1e1e", fg = "#e7913b" })
hi(0, "lualine_x_diagnostics_warn_0_visual", { bg = "#1e1e1e", fg = "#e7913b" })
hi(0, "lualine_x_diagnostics_warn_command", { bg = "#1e1e1e", fg = "#e7913b" })
hi(0, "lualine_x_diagnostics_warn_inactive", { bg = "#1e1e1e", fg = "#e7913b" })
hi(0, "lualine_x_diagnostics_warn_insert", { bg = "#1e1e1e", fg = "#e7913b" })
hi(0, "lualine_x_diagnostics_warn_normal", { bg = "#1e1e1e", fg = "#e7913b" })
hi(0, "lualine_x_diagnostics_warn_replace", { bg = "#1e1e1e", fg = "#e7913b" })
hi(0, "lualine_x_diagnostics_warn_terminal", { bg = "#1e1e1e", fg = "#e7913b" })
hi(0, "lualine_x_diagnostics_warn_visual", { bg = "#1e1e1e", fg = "#e7913b" })
hi(0, "lualine_x_filetype_DevIconDefault_command", { bg = "#1d1d1d", fg = "#798484" })
hi(0, "lualine_x_filetype_DevIconDefault_inactive", { bg = "#1d1d1d", fg = "#798484" })
hi(0, "lualine_x_filetype_DevIconDefault_insert", { bg = "#1d1d1d", fg = "#798484" })
hi(0, "lualine_x_filetype_DevIconDefault_normal", { bg = "#1d1d1d", fg = "#798484" })
hi(0, "lualine_x_filetype_DevIconDefault_replace", { bg = "#1d1d1d", fg = "#798484" })
hi(0, "lualine_x_filetype_DevIconDefault_terminal", { bg = "#1d1d1d", fg = "#798484" })
hi(0, "lualine_x_filetype_DevIconDefault_visual", { bg = "#1d1d1d", fg = "#798484" })
hi(0, "lualine_x_filetype_DevIconGo_command", { bg = "#2f2f2f", fg = "#408aa9" })
hi(0, "lualine_x_filetype_DevIconGo_inactive", { bg = "#1c1c1c", fg = "#408aa9" })
hi(0, "lualine_x_filetype_DevIconGo_insert", { bg = "#2f2f2f", fg = "#408aa9" })
hi(0, "lualine_x_filetype_DevIconGo_normal", { bg = "#2f2f2f", fg = "#408aa9" })
hi(0, "lualine_x_filetype_DevIconGo_replace", { bg = "#2f2f2f", fg = "#408aa9" })
hi(0, "lualine_x_filetype_DevIconGo_terminal", { bg = "#2f2f2f", fg = "#408aa9" })
hi(0, "lualine_x_filetype_DevIconGo_visual", { bg = "#2f2f2f", fg = "#408aa9" })
hi(0, "lualine_x_filetype_DevIconRs_command", { bg = "#1d1d1d", fg = "#dcad92" })
hi(0, "lualine_x_filetype_DevIconRs_inactive", { bg = "#1d1d1d", fg = "#dcad92" })
hi(0, "lualine_x_filetype_DevIconRs_insert", { bg = "#1d1d1d", fg = "#dcad92" })
hi(0, "lualine_x_filetype_DevIconRs_normal", { bg = "#1d1d1d", fg = "#dcad92" })
hi(0, "lualine_x_filetype_DevIconRs_replace", { bg = "#1d1d1d", fg = "#dcad92" })
hi(0, "lualine_x_filetype_DevIconRs_terminal", { bg = "#1d1d1d", fg = "#dcad92" })
hi(0, "lualine_x_filetype_DevIconRs_visual", { bg = "#1d1d1d", fg = "#dcad92" })
hi(0, "lualine_x_filetype_DevIconToml_command", { bg = "#1d1d1d", fg = "#9b4c31" })
hi(0, "lualine_x_filetype_DevIconToml_inactive", { bg = "#1d1d1d", fg = "#9b4c31" })
hi(0, "lualine_x_filetype_DevIconToml_insert", { bg = "#1d1d1d", fg = "#9b4c31" })
hi(0, "lualine_x_filetype_DevIconToml_normal", { bg = "#1d1d1d", fg = "#9b4c31" })
hi(0, "lualine_x_filetype_DevIconToml_replace", { bg = "#1d1d1d", fg = "#9b4c31" })
hi(0, "lualine_x_filetype_DevIconToml_terminal", { bg = "#1d1d1d", fg = "#9b4c31" })
hi(0, "lualine_x_filetype_DevIconToml_visual", { bg = "#1d1d1d", fg = "#9b4c31" })
hi(0, "lualine_x_filetype_DevIconTypeScript_command", { bg = "#1e1e1e", fg = "#49a0c6" })
hi(0, "lualine_x_filetype_DevIconTypeScript_inactive", { bg = "#1e1e1e", fg = "#49a0c6" })
hi(0, "lualine_x_filetype_DevIconTypeScript_insert", { bg = "#1e1e1e", fg = "#49a0c6" })
hi(0, "lualine_x_filetype_DevIconTypeScript_normal", { bg = "#1e1e1e", fg = "#49a0c6" })
hi(0, "lualine_x_filetype_DevIconTypeScript_replace", { bg = "#1e1e1e", fg = "#49a0c6" })
hi(0, "lualine_x_filetype_DevIconTypeScript_terminal", { bg = "#1e1e1e", fg = "#49a0c6" })
hi(0, "lualine_x_filetype_DevIconTypeScript_visual", { bg = "#1e1e1e", fg = "#49a0c6" })
hi(0, "lualine_z_progress_0_command", { bg = "#e1c28a", fg = "#2a2a2a" })
hi(0, "lualine_z_progress_0_inactive", { bg = "#4c5861", fg = "#a7a7a7" })
hi(0, "lualine_z_progress_0_insert", { bg = "#96b66e", fg = "#2a2a2a" })
hi(0, "lualine_z_progress_0_normal", { bg = "#4c5861", fg = "#a7a7a7" })
hi(0, "lualine_z_progress_0_replace", { bg = "#c37f95", fg = "#2a2a2a" })
hi(0, "lualine_z_progress_0_terminal", { bg = "#e1c28a", fg = "#2a2a2a" })
hi(0, "lualine_z_progress_0_visual", { bg = "#81afc3", fg = "#2a2a2a" })
hi(0, "lualine_z_progress_command", { bg = "#e1c28a", fg = "#2a2a2a" })
hi(0, "lualine_z_progress_inactive", { bg = "#4c5861", fg = "#a7a7a7" })
hi(0, "lualine_z_progress_insert", { bg = "#96b66e", fg = "#2a2a2a" })
hi(0, "lualine_z_progress_normal", { bg = "#4c5861", fg = "#a7a7a7" })
hi(0, "lualine_z_progress_replace", { bg = "#c37f95", fg = "#2a2a2a" })
hi(0, "lualine_z_progress_terminal", { bg = "#e1c28a", fg = "#2a2a2a" })
hi(0, "lualine_z_progress_visual", { bg = "#81afc3", fg = "#2a2a2a" })
hi(0, "markdownCode", { fg = "#88aa5b" })
hi(0, "markdownCodeBlock", { fg = "#88aa5b" })
hi(0, "qfFileName", { link = "Directory" })
hi(0, "qfLineNr", { link = "LineNr" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#16161d"
g.terminal_color_1 = "#c34043"
g.terminal_color_2 = "#76946a"
g.terminal_color_3 = "#c0a36e"
g.terminal_color_4 = "#7e9cd8"
g.terminal_color_5 = "#957fb8"
g.terminal_color_6 = "#6a9589"
g.terminal_color_7 = "#c8c093"
g.terminal_color_8 = "#727169"
g.terminal_color_9 = "#e82424"
g.terminal_color_10 = "#98bb6c"
g.terminal_color_11 = "#e6c384"
g.terminal_color_12 = "#7fb4ca"
g.terminal_color_13 = "#938aa9"
g.terminal_color_14 = "#7aa89f"
g.terminal_color_15 = "#dcd7ba"
