-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "rose-pine"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@attribute.diff", { fg = "#d4a868" })
hi(0, "@character.special", { link = "Character" })
hi(0, "@class", { fg = "#8db1b7" })
hi(0, "@comment.error", { fg = "#c45d7a" })
hi(0, "@comment.hint", { bg = "#3e3744", blend = 20, fg = "#a78fc3" })
hi(0, "@comment.info", { bg = "#383e44", blend = 20, fg = "#8db1b7" })
hi(0, "@comment.note", { bg = "#212d36", blend = 20, fg = "#215a70" })
hi(0, "@comment.todo", { bg = "#403d3f", blend = 20, fg = "#c8a4a2" })
hi(0, "@comment.warning", { fg = "#d4a868" })
hi(0, "@conceal", { link = "Conceal" })
hi(0, "@conceal.markdown", { fg = "#767484" })
hi(0, "@conditional", { link = "Conditional" })
hi(0, "@constant", { fg = "#d4a868" })
hi(0, "@constant.builtin", { bold = true, fg = "#d4a868" })
hi(0, "@constant.macro", { fg = "#d4a868" })
hi(0, "@constructor", { fg = "#8db1b7" })
hi(0, "@diff.delta", { bg = "#403d3f", blend = 20 })
hi(0, "@diff.minus", { bg = "#432e37", blend = 20, fg = "#c45d7a" })
hi(0, "@diff.plus", { bg = "#383e44", blend = 20, fg = "#8db1b7" })
hi(0, "@field", { fg = "#8db1b7" })
hi(0, "@float", { link = "Number" })
hi(0, "@function", { fg = "#c8a4a2" })
hi(0, "@function.builtin", { bold = true, fg = "#c8a4a2" })
hi(0, "@function.macro", { link = "Function" })
hi(0, "@function.method", { fg = "#c8a4a2" })
hi(0, "@function.method.call", { fg = "#a78fc3" })
hi(0, "@ibl.indent.char.1", { fg = "#525246", nocombine = true })
hi(0, "@ibl.indent.char.2", { fg = "#2e3f3f", nocombine = true })
hi(0, "@ibl.indent.char.3", { fg = "#3a323a", nocombine = true })
hi(0, "@ibl.indent.char.4", { fg = "#262826", nocombine = true })
hi(0, "@ibl.scope.char.1", { fg = "#c8a4a2", nocombine = true })
hi(0, "@ibl.scope.char.2", { fg = "#8db1b7", nocombine = true })
hi(0, "@ibl.scope.underline.1", { sp = "#ebbcba", underline = true })
hi(0, "@ibl.scope.underline.2", { sp = "#9ccfd8", underline = true })
hi(0, "@ibl.whitespace.char.1", { fg = "#0d0c19", nocombine = true })
hi(0, "@include", { link = "Include" })
hi(0, "@interface", { fg = "#8db1b7" })
hi(0, "@keyword.conditional", { fg = "#215a70" })
hi(0, "@keyword.conditional.ternary", { fg = "#215a70" })
hi(0, "@keyword.debug", { fg = "#c8a4a2" })
hi(0, "@keyword.directive", { fg = "#a78fc3" })
hi(0, "@keyword.directive.define", { fg = "#a78fc3" })
hi(0, "@keyword.exception", { fg = "#215a70" })
hi(0, "@keyword.import", { fg = "#215a70" })
hi(0, "@keyword.operator", { fg = "#767484" })
hi(0, "@keyword.repeat", { fg = "#215a70" })
hi(0, "@keyword.return", { fg = "#215a70" })
hi(0, "@keyword.storage", { fg = "#8db1b7" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", vim.empty_dict())
hi(0, "@lsp.type.comment.c", { link = "@comment" })
hi(0, "@lsp.type.comment.cpp", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@interface" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.namespace.python", { link = "@variable" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", vim.empty_dict())
hi(0, "@lsp.type.variable.svelte", { link = "@variable" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.variable.constant", { link = "@constant" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@macro", { link = "Macro" })
hi(0, "@markup.environment", { link = "Macro" })
hi(0, "@markup.environment.name", { link = "@type" })
hi(0, "@markup.heading", { bold = true, fg = "#8db1b7" })
hi(0, "@markup.heading.1.delimiter.vimdoc", { bg = "#1c1a21", fg = "#000001", nocombine = true, sp = "#e0def4", underdouble = true })
hi(0, "@markup.heading.1.markdown", { link = "markdownH1" })
hi(0, "@markup.heading.1.marker.markdown", { link = "markdownH1Delimiter" })
hi(0, "@markup.heading.2.delimiter.vimdoc", { bg = "#1c1a21", fg = "#000001", nocombine = true, sp = "#e0def4", underline = true })
hi(0, "@markup.heading.2.markdown", { link = "markdownH2" })
hi(0, "@markup.heading.2.marker.markdown", { link = "markdownH2Delimiter" })
hi(0, "@markup.heading.3.markdown", { link = "markdownH3" })
hi(0, "@markup.heading.3.marker.markdown", { link = "markdownH3Delimiter" })
hi(0, "@markup.heading.4.markdown", { link = "markdownH4" })
hi(0, "@markup.heading.4.marker.markdown", { link = "markdownH4Delimiter" })
hi(0, "@markup.heading.5.markdown", { link = "markdownH5" })
hi(0, "@markup.heading.5.marker.markdown", { link = "markdownH5Delimiter" })
hi(0, "@markup.heading.6.markdown", { link = "markdownH6" })
hi(0, "@markup.heading.6.marker.markdown", { link = "markdownH6Delimiter" })
hi(0, "@markup.link", { link = "Underlined" })
hi(0, "@markup.link.label.markdown_inline", { fg = "#8db1b7" })
hi(0, "@markup.link.markdown_inline", { fg = "#767484" })
hi(0, "@markup.link.url", { fg = "#a78fc3" })
hi(0, "@markup.list", { fg = "#215a70" })
hi(0, "@markup.list.checked", { bg = "#2b2c2f", blend = 10, fg = "#8db1b7" })
hi(0, "@markup.list.unchecked", { fg = "#c4c3d4" })
hi(0, "@markup.math", { link = "Special" })
hi(0, "@markup.quote", { fg = "#c4c3d4" })
hi(0, "@markup.raw.delimiter.markdown", { fg = "#767484" })
hi(0, "@method", { fg = "#c8a4a2" })
hi(0, "@module", { fg = "#c4c3d4" })
hi(0, "@module.builtin", { bold = true, fg = "#c4c3d4" })
hi(0, "@namespace", { link = "Include" })
hi(0, "@number.float", { link = "Number" })
hi(0, "@parameter", { fg = "#a78fc3", italic = true })
hi(0, "@preproc", { link = "PreProc" })
hi(0, "@property", { fg = "#8db1b7", italic = true })
hi(0, "@punctuation", { fg = "#767484" })
hi(0, "@punctuation.bracket", { fg = "#767484" })
hi(0, "@punctuation.delimiter", { fg = "#767484" })
hi(0, "@punctuation.special", { fg = "#767484" })
hi(0, "@regexp", { link = "String" })
hi(0, "@repeat", { link = "Repeat" })
hi(0, "@storageclass", { link = "StorageClass" })
hi(0, "@string.escape", { fg = "#215a70" })
hi(0, "@string.regexp", { fg = "#a78fc3" })
hi(0, "@string.special", { link = "String" })
hi(0, "@string.special.symbol", { link = "Identifier" })
hi(0, "@string.special.url", { fg = "#a78fc3" })
hi(0, "@symbol", { link = "Identifier" })
hi(0, "@tag.attribute", { fg = "#a78fc3" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { fg = "#767484" })
hi(0, "@text", { fg = "#c4c3d4" })
hi(0, "@text.danger", { fg = "#c45d7a" })
hi(0, "@text.diff.add", { bg = "#383e44", blend = 20, fg = "#8db1b7" })
hi(0, "@text.diff.delete", { bg = "#432e37", blend = 20, fg = "#c45d7a" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.environment", { link = "Macro" })
hi(0, "@text.environment.name", { link = "Type" })
hi(0, "@text.math", { link = "Special" })
hi(0, "@text.note", { link = "SpecialComment" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.title.1.markdown", { link = "markdownH1" })
hi(0, "@text.title.1.marker.markdown", { link = "markdownH1Delimiter" })
hi(0, "@text.title.2.markdown", { link = "markdownH2" })
hi(0, "@text.title.2.marker.markdown", { link = "markdownH2Delimiter" })
hi(0, "@text.title.3.markdown", { link = "markdownH3" })
hi(0, "@text.title.3.marker.markdown", { link = "markdownH3Delimiter" })
hi(0, "@text.title.4.markdown", { link = "markdownH4" })
hi(0, "@text.title.4.marker.markdown", { link = "markdownH4Delimiter" })
hi(0, "@text.title.5.markdown", { link = "markdownH5" })
hi(0, "@text.title.5.marker.markdown", { link = "markdownH5Delimiter" })
hi(0, "@text.title.6.markdown", { link = "markdownH6" })
hi(0, "@text.title.6.marker.markdown", { link = "markdownH6Delimiter" })
hi(0, "@text.underline", { underline = true })
hi(0, "@text.uri", { fg = "#a78fc3" })
hi(0, "@text.warning", { fg = "#d4a868" })
hi(0, "@todo", { link = "Todo" })
hi(0, "@type", { fg = "#8db1b7" })
hi(0, "@type.builtin", { bold = true, fg = "#8db1b7" })
hi(0, "@variable", { fg = "#c4c3d4", italic = true })
hi(0, "@variable.builtin", { bold = true, fg = "#c45d7a" })
hi(0, "@variable.member", { fg = "#8db1b7" })
hi(0, "@variable.parameter", { fg = "#a78fc3", italic = true })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "Added", { ctermfg = 10, fg = "#a1d7ab" })
hi(0, "AlphaButtons", { fg = "#8db1b7" })
hi(0, "AlphaFooter", { fg = "#d4a868" })
hi(0, "AlphaHeader", { fg = "#215a70" })
hi(0, "AlphaShortcut", { fg = "#c8a4a2" })
hi(0, "AvanteAnnotation", { link = "Comment" })
hi(0, "AvanteConflictAncestor", { bg = "#6e286d", bold = true })
hi(0, "AvanteConflictAncestorLabel", { bg = "#af3ead" })
hi(0, "AvanteConflictCurrent", { bg = "#655f60", bold = true })
hi(0, "AvanteConflictCurrentLabel", { bg = "#a59799" })
hi(0, "AvanteConflictIncoming", { bg = "#383e44", bold = true })
hi(0, "AvanteConflictIncomingLabel", { bg = "#57626c" })
hi(0, "AvanteInlineHint", { link = "Keyword" })
hi(0, "AvantePopupHint", { link = "NormalFloat" })
hi(0, "AvanteReversedSubtitle", { fg = "#8db1b7" })
hi(0, "AvanteReversedThirdTitle", { fg = "#a78fc3" })
hi(0, "AvanteReversedTitle", { fg = "#c8a4a2" })
hi(0, "AvanteSubtitle", { bg = "#abd0d2", fg = "#292830" })
hi(0, "AvanteSuggestion", { link = "Comment" })
hi(0, "AvanteThirdTitle", { bg = "#cdabdc", fg = "#292830" })
hi(0, "AvanteTitle", { bg = "#e7c3bb", fg = "#3a3942" })
hi(0, "BlinkCmpDefault", { fg = "#292830" })
hi(0, "BlinkCmpDoc", { fg = "#c4c3d4" })
hi(0, "BlinkCmpDocBorder", { fg = "#3a3942" })
hi(0, "BlinkCmpGhostText", { fg = "#55545e" })
hi(0, "BlinkCmpKindClass", { fg = "#d4a868" })
hi(0, "BlinkCmpKindCodeium", { fg = "#8db1b7" })
hi(0, "BlinkCmpKindColor", { fg = "#c45d7a" })
hi(0, "BlinkCmpKindConstant", { fg = "#d4a868" })
hi(0, "BlinkCmpKindConstructor", { fg = "#8db1b7" })
hi(0, "BlinkCmpKindCopilot", { fg = "#8db1b7" })
hi(0, "BlinkCmpKindEnum", { fg = "#8db1b7" })
hi(0, "BlinkCmpKindEnumMember", { fg = "#8db1b7" })
hi(0, "BlinkCmpKindEvent", { fg = "#8db1b7" })
hi(0, "BlinkCmpKindField", { fg = "#215a70" })
hi(0, "BlinkCmpKindFile", { fg = "#8db1b7" })
hi(0, "BlinkCmpKindFolder", { fg = "#8db1b7" })
hi(0, "BlinkCmpKindFunction", { fg = "#8db1b7" })
hi(0, "BlinkCmpKindInterface", { fg = "#d4a868" })
hi(0, "BlinkCmpKindKeyword", { fg = "#a78fc3" })
hi(0, "BlinkCmpKindMethod", { fg = "#8db1b7" })
hi(0, "BlinkCmpKindModule", { fg = "#8db1b7" })
hi(0, "BlinkCmpKindOperator", { fg = "#8db1b7" })
hi(0, "BlinkCmpKindProperty", { fg = "#8db1b7" })
hi(0, "BlinkCmpKindReference", { fg = "#c45d7a" })
hi(0, "BlinkCmpKindSnippet", { fg = "#c8a4a2" })
hi(0, "BlinkCmpKindStruct", { fg = "#8db1b7" })
hi(0, "BlinkCmpKindSupermaven", { fg = "#8db1b7" })
hi(0, "BlinkCmpKindTabNine", { fg = "#8db1b7" })
hi(0, "BlinkCmpKindText", { fg = "#215a70" })
hi(0, "BlinkCmpKindTypeParameter", { fg = "#a78fc3" })
hi(0, "BlinkCmpKindUnit", { fg = "#215a70" })
hi(0, "BlinkCmpKindValue", { fg = "#c45d7a" })
hi(0, "BlinkCmpKindVariable", { fg = "#c8a4a2" })
hi(0, "BlinkCmpLabel", { fg = "#55545e" })
hi(0, "BlinkCmpLabelDeprecated", { fg = "#55545e", strikethrough = true })
hi(0, "BlinkCmpLabelMatch", { bold = true, fg = "#c4c3d4" })
hi(0, "Boolean", { fg = "#c8a4a2" })
hi(0, "BufferCurrent", { bg = "#2a2634", fg = "#c4c3d4" })
hi(0, "BufferCurrentIndex", { bg = "#2a2634", fg = "#c4c3d4" })
hi(0, "BufferCurrentMod", { bg = "#2a2634", fg = "#8db1b7" })
hi(0, "BufferCurrentSign", { bg = "#2a2634", fg = "#767484" })
hi(0, "BufferCurrentTarget", { bg = "#2a2634", fg = "#d4a868" })
hi(0, "BufferInactive", { fg = "#767484" })
hi(0, "BufferInactiveIndex", { fg = "#767484" })
hi(0, "BufferInactiveMod", { fg = "#8db1b7" })
hi(0, "BufferInactiveSign", { fg = "#55545e" })
hi(0, "BufferInactiveTarget", { fg = "#d4a868" })
hi(0, "BufferVisible", { fg = "#767484" })
hi(0, "BufferVisibleIndex", { fg = "#767484" })
hi(0, "BufferVisibleMod", { fg = "#8db1b7" })
hi(0, "BufferVisibleSign", { fg = "#55545e" })
hi(0, "BufferVisibleTarget", { fg = "#d4a868" })
hi(0, "Changed", { ctermfg = 14, fg = "#7fd8d8" })
hi(0, "Character", { fg = "#d4a868" })
hi(0, "CmpItemAbbr", { fg = "#767484" })
hi(0, "CmpItemAbbrDefault", { fg = "#767484" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#767484", strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#55545e" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#c4c3d4" })
hi(0, "CmpItemAbbrMatchDefault", { fg = "#767484" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#c4c3d4" })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#767484" })
hi(0, "CmpItemKind", { fg = "#767484" })
hi(0, "CmpItemKindClass", { link = "StorageClass" })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = "#8db1b7" })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { link = "Type" })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { link = "PreProc" })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { link = "String" })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { link = "Identifier" })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenuDefault", { fg = "#767484" })
hi(0, "ColorColumn", { bg = "#231f29" })
hi(0, "Comment", { fg = "#55545e", italic = true })
hi(0, "Conceal", vim.empty_dict())
hi(0, "Conditional", { fg = "#215a70" })
hi(0, "Constant", { fg = "#d4a868" })
hi(0, "CopilotSuggestion", { fg = "#55545e", italic = true })
hi(0, "CratesNvimPopupEnabled", { ctermfg = 2, fg = "#148d39" })
hi(0, "CratesNvimPopupPillBorder", { ctermfg = 242, fg = "#232323" })
hi(0, "CratesNvimPopupPillText", { bg = "#3c3c3c", ctermbg = 242, ctermfg = 15, fg = "#c4c4c4" })
hi(0, "CratesNvimPopupTransitive", { ctermfg = 4, fg = "#127098" })
hi(0, "CurSearch", { bg = "#ecca84", fg = "#000001" })
hi(0, "Cursor", { bg = "#55535b", fg = "#c4c3d4" })
hi(0, "CursorColumn", { bg = "#2a2634" })
hi(0, "CursorLine", { bg = "#2a2634" })
hi(0, "CursorLineNr", { bold = true, fg = "#c4c3d4" })
hi(0, "CursorLineSign", { bg = "#2a2634" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#d4a868" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#55545e" })
hi(0, "DapUIBreakpointsInfo", { link = "DapUIThread" })
hi(0, "DapUIBreakpointsLine", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIBreakpointsPath", { fg = "#8db1b7" })
hi(0, "DapUIDecoration", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIFloatBorder", { fg = "#55545e" })
hi(0, "DapUIFrameName", { fg = "#c4c3d4" })
hi(0, "DapUILineNumber", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#8db1b7" })
hi(0, "DapUIScope", { link = "DapUIBreakpointsPath" })
hi(0, "DapUISource", { fg = "#a78fc3" })
hi(0, "DapUIStoppedThread", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIThread", { fg = "#d4a868" })
hi(0, "DapUIValue", { fg = "#c4c3d4" })
hi(0, "DapUIVariable", { fg = "#c4c3d4" })
hi(0, "DapUIWatchesEmpty", { fg = "#c45d7a" })
hi(0, "DapUIWatchesError", { link = "DapUIWatchesEmpty" })
hi(0, "DapUIWatchesValue", { link = "DapUIThread" })
hi(0, "DashboardCenter", { fg = "#d4a868" })
hi(0, "DashboardFooter", { fg = "#a78fc3" })
hi(0, "DashboardHeader", { fg = "#215a70" })
hi(0, "DashboardShortcut", { fg = "#c45d7a" })
hi(0, "Debug", { fg = "#c8a4a2" })
hi(0, "Define", { fg = "#a78fc3" })
hi(0, "DefinitionCount", { fg = "#c8a4a2" })
hi(0, "DefinitionIcon", { fg = "#c8a4a2" })
hi(0, "DefinitionPreviewTitle", { bold = true, fg = "#c8a4a2" })
hi(0, "Delimiter", { fg = "#767484" })
hi(0, "DiagnosticDefaultError", { link = "DiagnosticError" })
hi(0, "DiagnosticDefaultHint", { link = "DiagnosticHint" })
hi(0, "DiagnosticDefaultInfo", { link = "DiagnosticInfo" })
hi(0, "DiagnosticDefaultOk", { link = "DiagnosticOk" })
hi(0, "DiagnosticDefaultWarn", { link = "DiagnosticWarn" })
hi(0, "DiagnosticERRORReverse", { bg = "#e87a87", fg = "#000000" })
hi(0, "DiagnosticError", { fg = "#c45d7a" })
hi(0, "DiagnosticHINTReverse", { bg = "#cdabdc", fg = "#000000" })
hi(0, "DiagnosticHint", { fg = "#a78fc3" })
hi(0, "DiagnosticINFOReverse", { bg = "#abd0d2", fg = "#000000" })
hi(0, "DiagnosticInfo", { fg = "#8db1b7" })
hi(0, "DiagnosticOk", { fg = "#849390" })
hi(0, "DiagnosticUnderlineError", { sp = "#eb6f92", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#c4a7e7", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#9ccfd8", undercurl = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#95b1ac", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#f6c177", undercurl = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#2e242c", blend = 10, fg = "#c45d7a" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#2d2832", blend = 10, fg = "#a78fc3" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#2b2c2f", blend = 10, fg = "#8db1b7" })
hi(0, "DiagnosticVirtualTextOk", { bg = "#28292c", blend = 10, fg = "#849390" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#2c2c2c", blend = 10, fg = "#d4a868" })
hi(0, "DiagnosticWARNReverse", { bg = "#ecca84", fg = "#000000" })
hi(0, "DiagnosticWarn", { fg = "#d4a868" })
hi(0, "DiffAdd", { bg = "#383e44", blend = 20 })
hi(0, "DiffChange", { bg = "#403d3f", blend = 20 })
hi(0, "DiffDelete", { bg = "#432e37", blend = 20 })
hi(0, "DiffText", { bg = "#655f60", blend = 40 })
hi(0, "DiffviewDiffAddAsDelete", { bg = "#432e37" })
hi(0, "DiffviewDim1", { fg = "#55545e" })
hi(0, "DiffviewFilePanelCounter", { bold = true, fg = "#c4c3d4" })
hi(0, "DiffviewFilePanelFileName", { fg = "#c4c3d4" })
hi(0, "DiffviewFilePanelTitle", { bold = true, fg = "#8db1b7" })
hi(0, "DiffviewPrimary", { fg = "#c8a4a2" })
hi(0, "DiffviewSecondary", { fg = "#d4a868" })
hi(0, "Directory", { bold = true, fg = "#8db1b7" })
hi(0, "DressingSelectIdx", { link = "Special" })
hi(0, "Error", { fg = "#c45d7a" })
hi(0, "ErrorMsg", { bold = true, fg = "#c45d7a" })
hi(0, "Exception", { fg = "#215a70" })
hi(0, "FlashLabel", { bg = "#e87a87", fg = "#000001" })
hi(0, "Float", { fg = "#d4a868" })
hi(0, "FloatBorder", { fg = "#c8a4a2" })
hi(0, "FloatShadow", { bg = "#545454", blend = 80, ctermbg = 0 })
hi(0, "FloatShadowThrough", { bg = "#545454", blend = 100, ctermbg = 0 })
hi(0, "FloatTitle", { bg = "#231f29", bold = true, fg = "#8db1b7" })
hi(0, "FoldColumn", { fg = "#55545e" })
hi(0, "Folded", { bg = "#231f29", fg = "#c4c3d4" })
hi(0, "Function", { fg = "#c8a4a2" })
hi(0, "FzfLuaBorder", { fg = "#55545e" })
hi(0, "FzfLuaBufFlagAlt", { fg = "#767484" })
hi(0, "FzfLuaBufFlagCur", { fg = "#767484" })
hi(0, "FzfLuaCursorLine", { bg = "#2a2634", fg = "#c4c3d4" })
hi(0, "FzfLuaFilePart", { fg = "#c4c3d4" })
hi(0, "FzfLuaHeaderBind", { fg = "#c8a4a2" })
hi(0, "FzfLuaHeaderText", { fg = "#c45d7a" })
hi(0, "FzfLuaNormal", { link = "NormalFloat" })
hi(0, "FzfLuaTitle", { link = "FloatTitle" })
hi(0, "GitSignsAdd", { link = "SignAdd" })
hi(0, "GitSignsChange", { link = "SignChange" })
hi(0, "GitSignsDelete", { link = "SignDelete" })
hi(0, "GitSignsStagedAdd", { fg = "#3c4d50" })
hi(0, "GitSignsStagedAddCul", { fg = "#3c4d50" })
hi(0, "GitSignsStagedAddLn", { bg = "#383e44" })
hi(0, "GitSignsStagedAddNr", { fg = "#3c4d50" })
hi(0, "GitSignsStagedChange", { fg = "#514a4a" })
hi(0, "GitSignsStagedChangeCul", { fg = "#514a4a" })
hi(0, "GitSignsStagedChangeLn", { bg = "#403d3f" })
hi(0, "GitSignsStagedChangeNr", { fg = "#514a4a" })
hi(0, "GitSignsStagedChangedelete", { fg = "#514a4a" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#514a4a" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#403d3f" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#514a4a" })
hi(0, "GitSignsStagedDelete", { fg = "#532432" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#532432" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#532432" })
hi(0, "GitSignsStagedTopdelete", { fg = "#532432" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#532432" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#532432" })
hi(0, "GlanceBorderTop", { bg = "#302e33", fg = "#c8a4a2" })
hi(0, "GlanceFoldIcon", { fg = "#8b8a92" })
hi(0, "GlanceIndent", { fg = "#5c5b65" })
hi(0, "GlanceListBorderBottom", { bg = "#2c2a30", fg = "#c8a4a2" })
hi(0, "GlanceListCursorLine", { bg = "#3b3644" })
hi(0, "GlanceListEndOfBuffer", { bg = "#2c2a30", fg = "#111015" })
hi(0, "GlanceListFilepath", { fg = "#8b8a92" })
hi(0, "GlanceListNormal", { bg = "#2c2a30", fg = "#c4c3d4" })
hi(0, "GlancePreviewBorderBottom", { bg = "#26242a", fg = "#c8a4a2" })
hi(0, "GlancePreviewCursorLine", { bg = "#35313e" })
hi(0, "GlancePreviewEndOfBuffer", { bg = "#26242a", fg = "#09080e" })
hi(0, "GlancePreviewLineNr", { fg = "#62616b" })
hi(0, "GlancePreviewMatch", { bg = "#423d3b", fg = "#c4c3d4" })
hi(0, "GlancePreviewNormal", { bg = "#26242a" })
hi(0, "GlancePreviewSignColumn", { fg = "#09080e" })
hi(0, "GlanceWinBarFilename", { bg = "#302e33", fg = "#c4c3d4" })
hi(0, "GlanceWinBarFilepath", { bg = "#302e33", fg = "#8d8c95" })
hi(0, "GlanceWinBarTitle", { bg = "#302e33", fg = "#c4c3d4" })
hi(0, "GrugFarHelpHeader", { fg = "#215a70" })
hi(0, "GrugFarHelpHeaderKey", { fg = "#d4a868" })
hi(0, "GrugFarHelpWinActionKey", { fg = "#d4a868" })
hi(0, "GrugFarHelpWinActionPrefix", { fg = "#8db1b7" })
hi(0, "GrugFarHelpWinActionText", { fg = "#215a70" })
hi(0, "GrugFarHelpWinHeader", { link = "FloatTitle" })
hi(0, "GrugFarInputLabel", { fg = "#8db1b7" })
hi(0, "GrugFarInputPlaceholder", { link = "Comment" })
hi(0, "GrugFarResultsActionMessage", { fg = "#8db1b7" })
hi(0, "GrugFarResultsChangeIndicator", { fg = "#c8a4a2" })
hi(0, "GrugFarResultsHeader", { fg = "#215a70" })
hi(0, "GrugFarResultsLineColumn", { link = "GrugFarResultsLineNo" })
hi(0, "GrugFarResultsLineNo", { fg = "#a78fc3" })
hi(0, "GrugFarResultsMatch", { link = "CurSearch" })
hi(0, "GrugFarResultsPath", { fg = "#8db1b7" })
hi(0, "GrugFarResultsStats", { fg = "#a78fc3" })
hi(0, "HopNextKey", { bg = "#432e37", blend = 20, fg = "#c45d7a" })
hi(0, "HopNextKey1", { bg = "#383e44", blend = 20, fg = "#8db1b7" })
hi(0, "HopNextKey2", { bg = "#212d36", blend = 20, fg = "#215a70" })
hi(0, "HopUnmatched", { fg = "#55545e" })
hi(0, "IblIndent", { fg = "#0d0c19" })
hi(0, "IblScope", { fg = "#8db1b7" })
hi(0, "IblWhitespace", { fg = "#0d0c19" })
hi(0, "Identifier", { fg = "#c4c3d4" })
hi(0, "IlluminatedWordRead", { link = "LspReferenceRead" })
hi(0, "IlluminatedWordText", { link = "LspReferenceText" })
hi(0, "IlluminatedWordWrite", { link = "LspReferenceWrite" })
hi(0, "Include", { fg = "#215a70" })
hi(0, "IndentBlanklineChar", { fg = "#55545e", nocombine = true })
hi(0, "IndentBlanklineIndent1", { bg = "#312e25", fg = "#15150c" })
hi(0, "IndentBlanklineIndent2", { bg = "#252d2c", fg = "#0b1212" })
hi(0, "IndentBlanklineIndent3", { bg = "#2d282b", fg = "#110d11" })
hi(0, "IndentBlanklineIndent4", { bg = "#2a2e28", fg = "#0f140f" })
hi(0, "IndentBlanklineIndentChar1", { fg = "#525246" })
hi(0, "IndentBlanklineIndentChar2", { fg = "#2e3f3f" })
hi(0, "IndentBlanklineIndentChar3", { fg = "#3a323a" })
hi(0, "IndentBlanklineIndentChar4", { fg = "#262826" })
hi(0, "IndentBlanklineSpaceChar", { fg = "#55545e", nocombine = true })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#55545e", nocombine = true })
hi(0, "Keyword", { fg = "#215a70" })
hi(0, "Label", { fg = "#8db1b7" })
hi(0, "LeapLabelPrimary", { link = "IncSearch" })
hi(0, "LeapLabelSecondary", { link = "StatusLineTerm" })
hi(0, "LeapMatch", { link = "MatchParen" })
hi(0, "LineNr", { fg = "#55545e" })
hi(0, "LspCodeLens", { fg = "#767484" })
hi(0, "LspCodeLensSeparator", { fg = "#55545e" })
hi(0, "LspFloatWinBorder", { fg = "#55545e" })
hi(0, "LspFloatWinNormal", { bg = "#231f29" })
hi(0, "LspInlayHint", { bg = "#252229", blend = 10, fg = "#55545e" })
hi(0, "LspReferenceRead", { bg = "#434149" })
hi(0, "LspReferenceText", { bg = "#434149" })
hi(0, "LspReferenceWrite", { bg = "#434149" })
hi(0, "LspSagaAutoPreview", { fg = "#767484" })
hi(0, "LspSagaCodeActionBorder", { fg = "#c8a4a2" })
hi(0, "LspSagaCodeActionContent", { fg = "#8db1b7" })
hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#d4a868" })
hi(0, "LspSagaCodeActionTruncateLine", { link = "LspSagaCodeActionBorder" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#55545e" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#d4a868" })
hi(0, "LspSagaDiagnosticHeader", { bold = true, fg = "#8db1b7" })
hi(0, "LspSagaDiagnosticTruncateLine", { link = "LspSagaDiagnosticBorder" })
hi(0, "LspSagaDocTruncateLine", { link = "LspSagaHoverBorder" })
hi(0, "LspSagaFinderSelection", { fg = "#d4a868" })
hi(0, "LspSagaHoverBorder", { link = "LspFloatWinBorder" })
hi(0, "LspSagaLspFinderBorder", { link = "LspFloatWinBorder" })
hi(0, "LspSagaRenameBorder", { fg = "#215a70" })
hi(0, "LspSagaRenamePromptPrefix", { fg = "#c45d7a" })
hi(0, "LspSagaShTruncateLine", { link = "LspSagaSignatureHelpBorder" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#8db1b7" })
hi(0, "LspSignatureActiveParameter", { bg = "#2a2634" })
hi(0, "Macro", { fg = "#a78fc3" })
hi(0, "MatchParen", { bg = "#23313c", blend = 25, fg = "#215a70" })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { bg = "#231f29", bold = true })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniDepsChangeAdded", { fg = "#8db1b7" })
hi(0, "MiniDepsChangeRemoved", { fg = "#c45d7a" })
hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
hi(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
hi(0, "MiniDepsPlaceholder", { link = "Comment" })
hi(0, "MiniDepsTitle", { link = "Title" })
hi(0, "MiniDepsTitleError", { link = "DiffDelete" })
hi(0, "MiniDepsTitleSame", { link = "DiffText" })
hi(0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
hi(0, "MiniDiffOverAdd", { bg = "#383e44", blend = 20, fg = "#8db1b7" })
hi(0, "MiniDiffOverChange", { bg = "#403d3f", blend = 20, fg = "#c8a4a2" })
hi(0, "MiniDiffOverContext", { bg = "#231f29" })
hi(0, "MiniDiffOverDelete", { bg = "#432e37", blend = 20, fg = "#c45d7a" })
hi(0, "MiniDiffSignAdd", { fg = "#8db1b7" })
hi(0, "MiniDiffSignChange", { fg = "#c8a4a2" })
hi(0, "MiniDiffSignDelete", { fg = "#c45d7a" })
hi(0, "MiniFilesBorder", { link = "FloatBorder" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesCursorLine", { link = "CursorLine" })
hi(0, "MiniFilesDirectory", { link = "Directory" })
hi(0, "MiniFilesFile", { fg = "#c4c3d4" })
hi(0, "MiniFilesNormal", { link = "NormalFloat" })
hi(0, "MiniFilesTitle", { link = "FloatTitle" })
hi(0, "MiniFilesTitleFocused", { bg = "#231f29", bold = true, fg = "#c8a4a2" })
hi(0, "MiniHipatternsFixme", { bg = "#e87a87", bold = true, fg = "#000001" })
hi(0, "MiniHipatternsHack", { bg = "#ecca84", bold = true, fg = "#000001" })
hi(0, "MiniHipatternsNote", { bg = "#abd0d2", bold = true, fg = "#000001" })
hi(0, "MiniHipatternsTodo", { bg = "#cdabdc", bold = true, fg = "#000001" })
hi(0, "MiniIconsAzure", { fg = "#8db1b7" })
hi(0, "MiniIconsBlue", { fg = "#215a70" })
hi(0, "MiniIconsCyan", { fg = "#8db1b7" })
hi(0, "MiniIconsGreen", { fg = "#849390" })
hi(0, "MiniIconsGrey", { fg = "#767484" })
hi(0, "MiniIconsOrange", { fg = "#c8a4a2" })
hi(0, "MiniIconsPurple", { fg = "#a78fc3" })
hi(0, "MiniIconsRed", { fg = "#c45d7a" })
hi(0, "MiniIconsYellow", { fg = "#d4a868" })
hi(0, "MiniIndentscopeSymbol", { fg = "#55545e" })
hi(0, "MiniIndentscopeSymbolOff", { fg = "#d4a868" })
hi(0, "MiniJump", { sp = "#f6c177", undercurl = true })
hi(0, "MiniJump2dDim", { fg = "#767484" })
hi(0, "MiniJump2dSpot", { bold = true, fg = "#d4a868", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#231f29", fg = "#8db1b7", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { bold = true, fg = "#c8a4a2", nocombine = true })
hi(0, "MiniMapNormal", { link = "NormalFloat" })
hi(0, "MiniMapSymbolCount", { link = "Special" })
hi(0, "MiniMapSymbolLine", { link = "Title" })
hi(0, "MiniMapSymbolView", { link = "Delimiter" })
hi(0, "MiniNotifyBorder", { link = "FloatBorder" })
hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
hi(0, "MiniNotifyTitle", { link = "FloatTitle" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { link = "FloatBorder" })
hi(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniPickBorderText", { bg = "#231f29" })
hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { link = "MiniPickNormal" })
hi(0, "MiniPickMatchCurrent", { link = "CursorLine" })
hi(0, "MiniPickMatchMarked", { link = "Visual" })
hi(0, "MiniPickMatchRanges", { fg = "#8db1b7" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPreviewLine", { link = "CursorLine" })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { bg = "#231f29", bold = true })
hi(0, "MiniStarterCurrent", { nocombine = true })
hi(0, "MiniStarterFooter", { fg = "#767484" })
hi(0, "MiniStarterHeader", { link = "Title" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItem", { link = "Normal" })
hi(0, "MiniStarterItemBullet", { link = "Delimiter" })
hi(0, "MiniStarterItemPrefix", { link = "WarningMsg" })
hi(0, "MiniStarterQuery", { link = "MoreMsg" })
hi(0, "MiniStarterSection", { fg = "#c8a4a2" })
hi(0, "MiniStatuslineDevinfo", { bg = "#2a2634", fg = "#767484" })
hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
hi(0, "MiniStatuslineFilename", { bg = "#231f29", fg = "#55545e" })
hi(0, "MiniStatuslineInactive", { link = "MiniStatuslineFilename" })
hi(0, "MiniStatuslineModeCommand", { bg = "#e87a87", bold = true, fg = "#000001" })
hi(0, "MiniStatuslineModeInsert", { bg = "#abd0d2", bold = true, fg = "#000001" })
hi(0, "MiniStatuslineModeNormal", { bg = "#e7c3bb", bold = true, fg = "#000001" })
hi(0, "MiniStatuslineModeOther", { bg = "#e7c3bb", bold = true, fg = "#000001" })
hi(0, "MiniStatuslineModeReplace", { bg = "#3a7888", bold = true, fg = "#000001" })
hi(0, "MiniStatuslineModeVisual", { bg = "#cdabdc", bold = true, fg = "#000001" })
hi(0, "MiniSurround", { link = "IncSearch" })
hi(0, "MiniTablineCurrent", { bg = "#2a2634", bold = true, fg = "#c4c3d4" })
hi(0, "MiniTablineFill", { link = "TabLineFill" })
hi(0, "MiniTablineHidden", { bg = "#231f29", fg = "#767484" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#e6e1f2", bold = true, fg = "#0d0c19" })
hi(0, "MiniTablineModifiedHidden", { bg = "#9690a0", fg = "#05040b" })
hi(0, "MiniTablineModifiedVisible", { bg = "#e6e1f2", fg = "#05040b" })
hi(0, "MiniTablineTabpagesection", { link = "Search" })
hi(0, "MiniTablineVisible", { bg = "#231f29", fg = "#c4c3d4" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#c45d7a" })
hi(0, "MiniTestPass", { bold = true, fg = "#8db1b7" })
hi(0, "MiniTrailspace", { bg = "#e87a87" })
hi(0, "ModeMsg", { fg = "#767484" })
hi(0, "ModesCopy", { bg = "#ecca84" })
hi(0, "ModesCopyCursorLine", { bg = "#353535" })
hi(0, "ModesCopyCursorLineFold", { bg = "#353535" })
hi(0, "ModesCopyCursorLineNr", { bg = "#353535" })
hi(0, "ModesCopyCursorLineSign", { bg = "#353535" })
hi(0, "ModesDelete", { bg = "#e87a87" })
hi(0, "ModesDeleteCursorLine", { bg = "#382932" })
hi(0, "ModesDeleteCursorLineFold", { bg = "#382932" })
hi(0, "ModesDeleteCursorLineNr", { bg = "#382932" })
hi(0, "ModesDeleteCursorLineSign", { bg = "#382932" })
hi(0, "ModesInsert", { bg = "#abd0d2" })
hi(0, "ModesInsertCursorLine", { bg = "#353535" })
hi(0, "ModesInsertCursorLineFold", { bg = "#353535" })
hi(0, "ModesInsertCursorLineNr", { bg = "#353535" })
hi(0, "ModesInsertCursorLineSign", { bg = "#353535" })
hi(0, "ModesInsertModeMsg", { fg = "#8db1b7" })
hi(0, "ModesReplace", { bg = "#3a7888" })
hi(0, "ModesVisual", { bg = "#cdabdc" })
hi(0, "ModesVisualCursorLine", { bg = "#36303b" })
hi(0, "ModesVisualCursorLineFold", { bg = "#36303b" })
hi(0, "ModesVisualCursorLineNr", { bg = "#36303b" })
hi(0, "ModesVisualCursorLineSign", { bg = "#36303b" })
hi(0, "ModesVisualModeMsg", { fg = "#a78fc3" })
hi(0, "ModesVisualVisual", { bg = "#36303b" })
hi(0, "MoreMsg", { fg = "#a78fc3" })
hi(0, "MultiCursor", { link = "VM_Cursor" })
hi(0, "NavicIconsArray", { fg = "#d4a868" })
hi(0, "NavicIconsBoolean", { fg = "#c8a4a2" })
hi(0, "NavicIconsClass", { fg = "#8db1b7" })
hi(0, "NavicIconsConstant", { fg = "#d4a868" })
hi(0, "NavicIconsConstructor", { fg = "#d4a868" })
hi(0, "NavicIconsEnum", { fg = "#d4a868" })
hi(0, "NavicIconsEnumMember", { fg = "#8db1b7" })
hi(0, "NavicIconsEvent", { fg = "#d4a868" })
hi(0, "NavicIconsField", { fg = "#8db1b7" })
hi(0, "NavicIconsFile", { fg = "#55545e" })
hi(0, "NavicIconsFunction", { fg = "#215a70" })
hi(0, "NavicIconsInterface", { fg = "#8db1b7" })
hi(0, "NavicIconsKey", { fg = "#a78fc3" })
hi(0, "NavicIconsKeyword", { fg = "#215a70" })
hi(0, "NavicIconsMethod", { fg = "#a78fc3" })
hi(0, "NavicIconsModule", { fg = "#c8a4a2" })
hi(0, "NavicIconsNamespace", { fg = "#55545e" })
hi(0, "NavicIconsNull", { fg = "#c45d7a" })
hi(0, "NavicIconsNumber", { fg = "#d4a868" })
hi(0, "NavicIconsObject", { fg = "#d4a868" })
hi(0, "NavicIconsOperator", { fg = "#767484" })
hi(0, "NavicIconsPackage", { fg = "#55545e" })
hi(0, "NavicIconsProperty", { fg = "#8db1b7" })
hi(0, "NavicIconsString", { fg = "#d4a868" })
hi(0, "NavicIconsStruct", { fg = "#8db1b7" })
hi(0, "NavicIconsTypeParameter", { fg = "#8db1b7" })
hi(0, "NavicIconsVariable", { fg = "#c4c3d4" })
hi(0, "NavicSeparator", { fg = "#767484" })
hi(0, "NavicText", { fg = "#767484" })
hi(0, "NeoTreeGitAdded", { fg = "#8db1b7" })
hi(0, "NeoTreeGitConflict", { fg = "#a78fc3" })
hi(0, "NeoTreeGitDeleted", { fg = "#c45d7a" })
hi(0, "NeoTreeGitIgnored", { fg = "#55545e" })
hi(0, "NeoTreeGitModified", { fg = "#c8a4a2" })
hi(0, "NeoTreeGitRenamed", { fg = "#215a70" })
hi(0, "NeoTreeGitUntracked", { fg = "#767484" })
hi(0, "NeoTreeTabActive", { bg = "#2a2634", fg = "#c4c3d4" })
hi(0, "NeoTreeTabInactive", { fg = "#767484" })
hi(0, "NeoTreeTabSeparatorActive", { link = "WinSeparator" })
hi(0, "NeoTreeTabSeparatorInactive", { link = "WinSeparator" })
hi(0, "NeoTreeTitleBar", { link = "StatusLineTerm" })
hi(0, "NeogitActiveItem", { bg = "#8eaeae", bold = true, fg = "#000001" })
hi(0, "NeogitBranch", { bold = true, fg = "#a78fc3" })
hi(0, "NeogitBranchHead", { bold = true, fg = "#a78fc3", underline = true })
hi(0, "NeogitChangeAdded", { bold = true, fg = "#8db1b7", italic = true })
hi(0, "NeogitChangeBothModified", { bold = true, fg = "#c8a4a2", italic = true })
hi(0, "NeogitChangeCopied", { bold = true, fg = "#767484", italic = true })
hi(0, "NeogitChangeDeleted", { bold = true, fg = "#c45d7a", italic = true })
hi(0, "NeogitChangeModified", { bold = true, fg = "#c8a4a2", italic = true })
hi(0, "NeogitChangeNewFile", { bold = true, fg = "#a78fc3", italic = true })
hi(0, "NeogitChangeRenamed", { bold = true, fg = "#215a70", italic = true })
hi(0, "NeogitChangeUnmerged", { bold = true, fg = "#86759a", italic = true })
hi(0, "NeogitChangeUpdated", { bold = true, fg = "#c8a4a2", italic = true })
hi(0, "NeogitCommitViewHeader", { bg = "#7a787e", fg = "#000001" })
hi(0, "NeogitDiffAdd", { bg = "#383e44", fg = "#a88655" })
hi(0, "NeogitDiffAddCursor", { bg = "#201e24", fg = "#d4a868" })
hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
hi(0, "NeogitDiffAdditions", { fg = "#a88655" })
hi(0, "NeogitDiffContext", { bg = "#201e24" })
hi(0, "NeogitDiffContextCursor", { bg = "#201e24" })
hi(0, "NeogitDiffContextHighlight", { bg = "#231f29" })
hi(0, "NeogitDiffDelete", { bg = "#432e37", fg = "#9a4b61" })
hi(0, "NeogitDiffDeleteCursor", { bg = "#201e24", fg = "#c45d7a" })
hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
hi(0, "NeogitDiffDeletions", { fg = "#9a4b61" })
hi(0, "NeogitDiffHeader", { bg = "#343435", bold = true, fg = "#a78fc3" })
hi(0, "NeogitDiffHeaderHighlight", { bg = "#343435", bold = true, fg = "#8db1b7" })
hi(0, "NeogitFilePath", { fg = "#8db1b7", italic = true })
hi(0, "NeogitFloatHeader", { bg = "#1c1a21", bold = true })
hi(0, "NeogitFloatHeaderHighlight", { bg = "#2b292d", bold = true, fg = "#767484" })
hi(0, "NeogitGraphAuthor", { fg = "#8db1b7" })
hi(0, "NeogitGraphBlue", { fg = "#a78fc3" })
hi(0, "NeogitGraphBoldBlue", { bold = true, fg = "#a78fc3" })
hi(0, "NeogitGraphBoldCyan", { bold = true, fg = "#767484" })
hi(0, "NeogitGraphBoldGray", { bold = true, fg = "#5c5c5c" })
hi(0, "NeogitGraphBoldGreen", { bold = true, fg = "#d4a868" })
hi(0, "NeogitGraphBoldOrange", { bold = true, fg = "#8db1b7" })
hi(0, "NeogitGraphBoldPurple", { bold = true, fg = "#215a70" })
hi(0, "NeogitGraphBoldRed", { bold = true, fg = "#c45d7a" })
hi(0, "NeogitGraphBoldWhite", { bold = true, fg = "#e0e0e0" })
hi(0, "NeogitGraphBoldYellow", { bold = true, fg = "#a78fc3" })
hi(0, "NeogitGraphCyan", { fg = "#767484" })
hi(0, "NeogitGraphGray", { fg = "#5c5c5c" })
hi(0, "NeogitGraphGreen", { fg = "#d4a868" })
hi(0, "NeogitGraphOrange", { fg = "#8db1b7" })
hi(0, "NeogitGraphPurple", { fg = "#215a70" })
hi(0, "NeogitGraphRed", { fg = "#c45d7a" })
hi(0, "NeogitGraphWhite", { fg = "#e0e0e0" })
hi(0, "NeogitGraphYellow", { fg = "#a78fc3" })
hi(0, "NeogitHunkHeader", { bg = "#231f29" })
hi(0, "NeogitHunkHeaderCursor", { bg = "#60909d", bold = true, fg = "#000001" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#231f29" })
hi(0, "NeogitHunkMergeHeader", { bg = "#787878", bold = true, fg = "#0f0e12" })
hi(0, "NeogitHunkMergeHeaderCursor", { bg = "#7a787e", bold = true, fg = "#000001" })
hi(0, "NeogitHunkMergeHeaderHighlight", { bg = "#7a787e", bold = true, fg = "#000001" })
hi(0, "NeogitPopupActionKey", { fg = "#215a70" })
hi(0, "NeogitPopupBold", { bold = true })
hi(0, "NeogitPopupConfigKey", { fg = "#215a70" })
hi(0, "NeogitPopupOptionKey", { fg = "#215a70" })
hi(0, "NeogitPopupSwitchKey", { fg = "#215a70" })
hi(0, "NeogitRemote", { bold = true, fg = "#d4a868" })
hi(0, "NeogitSectionHeader", { bold = true, fg = "#174557" })
hi(0, "NeogitTagDistance", { fg = "#767484" })
hi(0, "NeogitTagName", { fg = "#a78fc3" })
hi(0, "NeogitUnmergedInto", { bold = true, fg = "#174557" })
hi(0, "NeogitUnpulledFrom", { bold = true, fg = "#174557" })
hi(0, "NeogitUnpushedTo", { bold = true, fg = "#174557" })
hi(0, "NeorgHeading1Prefix", { link = "markdownH1Delimiter" })
hi(0, "NeorgHeading1Title", { link = "markdownH1" })
hi(0, "NeorgHeading2Prefix", { link = "markdownH2Delimiter" })
hi(0, "NeorgHeading2Title", { link = "markdownH2" })
hi(0, "NeorgHeading3Prefix", { link = "markdownH3Delimiter" })
hi(0, "NeorgHeading3Title", { link = "markdownH3" })
hi(0, "NeorgHeading4Prefix", { link = "markdownH4Delimiter" })
hi(0, "NeorgHeading4Title", { link = "markdownH4" })
hi(0, "NeorgHeading5Prefix", { link = "markdownH5Delimiter" })
hi(0, "NeorgHeading5Title", { link = "markdownH5" })
hi(0, "NeorgHeading6Prefix", { link = "markdownH6Delimiter" })
hi(0, "NeorgHeading6Title", { link = "markdownH6" })
hi(0, "NeorgMarkerTitle", { bold = true, fg = "#8db1b7" })
hi(0, "NeoscrollHiddenCursor", { blend = 100, reverse = true })
hi(0, "NeotestAdapterName", { fg = "#a78fc3" })
hi(0, "NeotestBorder", { fg = "#292830" })
hi(0, "NeotestDir", { fg = "#8db1b7" })
hi(0, "NeotestExpandMarker", { fg = "#292830" })
hi(0, "NeotestFailed", { fg = "#c45d7a" })
hi(0, "NeotestFile", { fg = "#c4c3d4" })
hi(0, "NeotestFocused", { bg = "#434149", fg = "#d4a868" })
hi(0, "NeotestIndent", { fg = "#292830" })
hi(0, "NeotestMarked", { bold = true, fg = "#c8a4a2" })
hi(0, "NeotestNamespace", { fg = "#d4a868" })
hi(0, "NeotestPassed", { fg = "#215a70" })
hi(0, "NeotestRunning", { fg = "#d4a868" })
hi(0, "NeotestSkipped", { fg = "#767484" })
hi(0, "NeotestTarget", { fg = "#c45d7a" })
hi(0, "NeotestTest", { fg = "#d4a868" })
hi(0, "NeotestUnknown", { fg = "#767484" })
hi(0, "NeotestWatching", { fg = "#a78fc3" })
hi(0, "NeotestWinSelect", { fg = "#55545e" })
hi(0, "NoiceCursor", { bg = "#e6e1f2", fg = "#3a3942" })
hi(0, "NoiceFormatProgressDone", { bg = "#423d3b", blend = 20, fg = "#c4c3d4" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { fg = "#55545e" })
hi(0, "Normal", { bg = "#1c1a21", fg = "#c4c3d4" })
hi(0, "NormalFloat", { bg = "#231f29" })
hi(0, "NormalNC", { bg = "#1c1a21", fg = "#c4c3d4" })
hi(0, "NotifyBackground", { bg = "#231f29" })
hi(0, "NotifyDEBUGBorder", { fg = "#55545e" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGTitle" })
hi(0, "NotifyDEBUGTitle", { fg = "#55545e" })
hi(0, "NotifyERRORBorder", { fg = "#c45d7a" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORTitle" })
hi(0, "NotifyERRORTitle", { fg = "#c45d7a" })
hi(0, "NotifyINFOBorder", { fg = "#8db1b7" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOTitle" })
hi(0, "NotifyINFOTitle", { fg = "#8db1b7" })
hi(0, "NotifyTRACEBorder", { fg = "#a78fc3" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACETitle" })
hi(0, "NotifyTRACETitle", { fg = "#a78fc3" })
hi(0, "NotifyWARNBorder", { fg = "#d4a868" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNTitle" })
hi(0, "NotifyWARNTitle", { fg = "#d4a868" })
hi(0, "Number", { fg = "#d4a868" })
hi(0, "NvimInternalError", { link = "ErrorMsg" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#55545e" })
hi(0, "NvimTreeFileDeleted", { fg = "#c45d7a" })
hi(0, "NvimTreeFileDirty", { fg = "#c8a4a2" })
hi(0, "NvimTreeFileMerge", { fg = "#a78fc3" })
hi(0, "NvimTreeFileNew", { fg = "#8db1b7" })
hi(0, "NvimTreeFileRenamed", { fg = "#215a70" })
hi(0, "NvimTreeFileStaged", { fg = "#a78fc3" })
hi(0, "NvimTreeFolderIcon", { fg = "#767484" })
hi(0, "NvimTreeFolderName", { fg = "#8db1b7" })
hi(0, "NvimTreeGitDeleted", { fg = "#c45d7a" })
hi(0, "NvimTreeGitDeletedIcon", { link = "NvimTreeGitDeleted" })
hi(0, "NvimTreeGitDirty", { fg = "#c8a4a2" })
hi(0, "NvimTreeGitDirtyIcon", { link = "NvimTreeGitDirty" })
hi(0, "NvimTreeGitFileDeletedHL", { link = "NvimTreeFileDeleted" })
hi(0, "NvimTreeGitFileDirtyHL", { link = "NvimTreeFileDirty" })
hi(0, "NvimTreeGitFileMergeHL", { link = "NvimTreeFileMerge" })
hi(0, "NvimTreeGitFileNewHL", { link = "NvimTreeFileNew" })
hi(0, "NvimTreeGitFileRenamedHL", { link = "NvimTreeFileRenamed" })
hi(0, "NvimTreeGitFileStagedHL", { link = "NvimTreeFileStaged" })
hi(0, "NvimTreeGitIgnored", { fg = "#55545e" })
hi(0, "NvimTreeGitIgnoredIcon", { link = "NvimTreeGitIgnored" })
hi(0, "NvimTreeGitMerge", { fg = "#a78fc3" })
hi(0, "NvimTreeGitMergeIcon", { link = "NvimTreeGitMerge" })
hi(0, "NvimTreeGitNew", { fg = "#8db1b7" })
hi(0, "NvimTreeGitNewIcon", { link = "NvimTreeGitNew" })
hi(0, "NvimTreeGitRenamed", { fg = "#215a70" })
hi(0, "NvimTreeGitRenamedIcon", { link = "NvimTreeGitRenamed" })
hi(0, "NvimTreeGitStaged", { fg = "#a78fc3" })
hi(0, "NvimTreeGitStagedIcon", { link = "NvimTreeGitStaged" })
hi(0, "NvimTreeImageFile", { fg = "#c4c3d4" })
hi(0, "NvimTreeOpenedFile", { bg = "#2a2634", fg = "#c4c3d4" })
hi(0, "NvimTreeOpenedFolderName", { link = "NvimTreeFolderName" })
hi(0, "NvimTreeOpenedHL", { link = "NvimTreeOpenedFile" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#8db1b7" })
hi(0, "NvimTreeSpecialFile", { link = "NvimTreeNormal" })
hi(0, "NvimTreeWindowPicker", { link = "StatusLineTerm" })
hi(0, "Operator", { fg = "#767484" })
hi(0, "Pmenu", { bg = "#231f29", fg = "#767484" })
hi(0, "PmenuExtra", { bg = "#231f29", fg = "#55545e" })
hi(0, "PmenuExtraSel", { bg = "#2a2634", fg = "#767484" })
hi(0, "PmenuKind", { bg = "#231f29", fg = "#8db1b7" })
hi(0, "PmenuKindSel", { bg = "#2a2634", fg = "#767484" })
hi(0, "PmenuSbar", { bg = "#231f29" })
hi(0, "PmenuSel", { bg = "#2a2634", fg = "#c4c3d4" })
hi(0, "PmenuThumb", { bg = "#736f79" })
hi(0, "PounceAccept", { bg = "#432e37", blend = 20, fg = "#c45d7a" })
hi(0, "PounceAcceptBest", { bg = "#423d3b", blend = 20, fg = "#d4a868" })
hi(0, "PounceGap", { link = "Search" })
hi(0, "PounceMatch", { link = "Search" })
hi(0, "PreCondit", { fg = "#a78fc3" })
hi(0, "PreProc", { link = "PreCondit" })
hi(0, "Question", { fg = "#d4a868" })
hi(0, "QuickFixLine", { ctermfg = 14, fg = "#7fd8d8" })
hi(0, "RainbowDelimiterBlue", { fg = "#215a70" })
hi(0, "RainbowDelimiterCyan", { fg = "#8db1b7" })
hi(0, "RainbowDelimiterGreen", { fg = "#849390" })
hi(0, "RainbowDelimiterOrange", { fg = "#c8a4a2" })
hi(0, "RainbowDelimiterRed", { fg = "#c45d7a" })
hi(0, "RainbowDelimiterViolet", { fg = "#a78fc3" })
hi(0, "RainbowDelimiterYellow", { fg = "#d4a868" })
hi(0, "RedrawDebugClear", { bg = "#ecca84", fg = "#000001" })
hi(0, "RedrawDebugComposed", { bg = "#3a7888", fg = "#000001" })
hi(0, "RedrawDebugRecompose", { bg = "#e87a87", fg = "#000001" })
hi(0, "ReferencesCount", { fg = "#c8a4a2" })
hi(0, "ReferencesIcon", { fg = "#c8a4a2" })
hi(0, "Removed", { ctermfg = 9, fg = "#dda7a1" })
hi(0, "RenderMarkdownBullet", { fg = "#c8a4a2" })
hi(0, "RenderMarkdownChecked", { fg = "#8db1b7" })
hi(0, "RenderMarkdownCode", { bg = "#2a2634" })
hi(0, "RenderMarkdownCodeInline", { bg = "#2a2634", fg = "#c4c3d4" })
hi(0, "RenderMarkdownDash", { fg = "#55545e" })
hi(0, "RenderMarkdownH1Bg", { bg = "#3e3744", blend = 20 })
hi(0, "RenderMarkdownH2Bg", { bg = "#383e44", blend = 20 })
hi(0, "RenderMarkdownH3Bg", { bg = "#403d3f", blend = 20 })
hi(0, "RenderMarkdownH4Bg", { bg = "#423d3b", blend = 20 })
hi(0, "RenderMarkdownH5Bg", { bg = "#212d36", blend = 20 })
hi(0, "RenderMarkdownH6Bg", { bg = "#383838", blend = 20 })
hi(0, "RenderMarkdownQuote", { fg = "#767484" })
hi(0, "RenderMarkdownTableFill", { link = "Conceal" })
hi(0, "RenderMarkdownTableHead", { fg = "#767484" })
hi(0, "RenderMarkdownTableRow", { fg = "#767484" })
hi(0, "RenderMarkdownUnchecked", { fg = "#767484" })
hi(0, "Repeat", { fg = "#215a70" })
hi(0, "SagaActionTitle", { bg = "#cdabdc", fg = "#000000" })
hi(0, "SagaBeacon", { bg = "#c04955" })
hi(0, "SagaButton", { fg = "#a78fc3" })
hi(0, "SagaCount", { bg = "#838383", bold = true, fg = "#e2e2e2" })
hi(0, "SagaShadow", { bg = "#2a2634" })
hi(0, "SagaVirtLine", { fg = "#303131" })
hi(0, "Search", { bg = "#423d3b", blend = 20, fg = "#c4c3d4" })
hi(0, "SignAdd", { fg = "#8db1b7" })
hi(0, "SignChange", { fg = "#c8a4a2" })
hi(0, "SignColumn", { fg = "#c4c3d4" })
hi(0, "SignDelete", { fg = "#c45d7a" })
hi(0, "Special", { fg = "#8db1b7" })
hi(0, "SpecialComment", { fg = "#a78fc3" })
hi(0, "SpecialKey", { fg = "#8db1b7" })
hi(0, "SpectreBody", { link = "String" })
hi(0, "SpectreBorder", { link = "Comment" })
hi(0, "SpectreDir", { link = "Comment" })
hi(0, "SpectreFile", { link = "Keyword" })
hi(0, "SpectreHeader", { link = "Comment" })
hi(0, "SpectreReplace", { link = "DiffDelete" })
hi(0, "SpectreSearch", { link = "DiffChange" })
hi(0, "SpellBad", { sp = "#908caa", undercurl = true })
hi(0, "SpellCap", { sp = "#908caa", undercurl = true })
hi(0, "SpellLocal", { sp = "#908caa", undercurl = true })
hi(0, "SpellRare", { sp = "#908caa", undercurl = true })
hi(0, "Statement", { bold = true, fg = "#215a70" })
hi(0, "StatusLine", { bg = "#231f29", fg = "#767484" })
hi(0, "StatusLineNC", { bg = "#201e25", blend = 60, fg = "#55545e" })
hi(0, "StatusLineTerm", { bg = "#3a7888", fg = "#000001" })
hi(0, "StatusLineTermNC", { bg = "#2c5160", blend = 60, fg = "#000001" })
hi(0, "StorageClass", { fg = "#8db1b7" })
hi(0, "String", { fg = "#d4a868" })
hi(0, "Structure", { fg = "#8db1b7" })
hi(0, "Substitute", { link = "IncSearch" })
hi(0, "TabLine", { bg = "#231f29", fg = "#767484" })
hi(0, "TabLineFill", { bg = "#231f29" })
hi(0, "TabLineSel", { bg = "#2a2634", bold = true, fg = "#c4c3d4" })
hi(0, "Tag", { fg = "#8db1b7" })
hi(0, "TargetWord", { fg = "#a78fc3" })
hi(0, "TelescopeBorder", { fg = "#55545e" })
hi(0, "TelescopeMatching", { bg = "#423d3b", blend = 20, fg = "#c4c3d4" })
hi(0, "TelescopeNormal", { link = "NormalFloat" })
hi(0, "TelescopePreviewLine", { link = "Search" })
hi(0, "TelescopePromptNormal", { link = "TelescopeNormal" })
hi(0, "TelescopePromptPrefix", { fg = "#767484" })
hi(0, "TelescopeSelection", { bg = "#2a2634", fg = "#c4c3d4" })
hi(0, "TelescopeSelectionCaret", { bg = "#2a2634", fg = "#c8a4a2" })
hi(0, "TelescopeTitle", { bold = true, fg = "#8db1b7" })
hi(0, "Title", { bold = true, fg = "#8db1b7" })
hi(0, "Todo", { bg = "#403d3f", blend = 20, fg = "#c8a4a2" })
hi(0, "TodoBgCURRENT", { bg = "#ecca84", bold = true, fg = "#000001" })
hi(0, "TodoBgFIX", { bg = "#e87a87", bold = true, fg = "#000001" })
hi(0, "TodoBgHACK", { bg = "#ecca84", bold = true, fg = "#000001" })
hi(0, "TodoBgIMP", { bg = "#e87a87", bold = true, fg = "#000001" })
hi(0, "TodoBgNOTE", { bg = "#cdabdc", bold = true, fg = "#000001" })
hi(0, "TodoBgPERF", { bg = "#e6e1f2", bold = true, fg = "#000001" })
hi(0, "TodoBgSECURITY", { bg = "#e87a87", bold = true, fg = "#000001" })
hi(0, "TodoBgTEST", { bg = "#e6e1f2", bold = true, fg = "#000001" })
hi(0, "TodoBgTODO", { bg = "#abd0d2", bold = true, fg = "#000001" })
hi(0, "TodoBgUSERINPUT", { bg = "#e87a87", bold = true, fg = "#000001" })
hi(0, "TodoBgVULNERABILITY", { bg = "#e87a87", bold = true, fg = "#000001" })
hi(0, "TodoBgWARN", { bg = "#ecca84", bold = true, fg = "#000001" })
hi(0, "TodoFgCURRENT", { fg = "#d4a868" })
hi(0, "TodoFgFIX", { fg = "#c45d7a" })
hi(0, "TodoFgHACK", { fg = "#d4a868" })
hi(0, "TodoFgIMP", { fg = "#c45d7a" })
hi(0, "TodoFgNOTE", { fg = "#a78fc3" })
hi(0, "TodoFgPERF", { fg = "#c4c3d4" })
hi(0, "TodoFgSECURITY", { fg = "#c45d7a" })
hi(0, "TodoFgTEST", { fg = "#c4c3d4" })
hi(0, "TodoFgTODO", { fg = "#8db1b7" })
hi(0, "TodoFgUSERINPUT", { fg = "#c45d7a" })
hi(0, "TodoFgVULNERABILITY", { fg = "#c45d7a" })
hi(0, "TodoFgWARN", { fg = "#d4a868" })
hi(0, "TodoSignCURRENT", { fg = "#d4a868" })
hi(0, "TodoSignFIX", { fg = "#c45d7a" })
hi(0, "TodoSignHACK", { fg = "#d4a868" })
hi(0, "TodoSignIMP", { fg = "#c45d7a" })
hi(0, "TodoSignNOTE", { fg = "#a78fc3" })
hi(0, "TodoSignPERF", { fg = "#c4c3d4" })
hi(0, "TodoSignSECURITY", { fg = "#c45d7a" })
hi(0, "TodoSignTEST", { fg = "#c4c3d4" })
hi(0, "TodoSignTODO", { fg = "#8db1b7" })
hi(0, "TodoSignUSERINPUT", { fg = "#c45d7a" })
hi(0, "TodoSignVULNERABILITY", { fg = "#c45d7a" })
hi(0, "TodoSignWARN", { fg = "#d4a868" })
hi(0, "TreesitterContext", { bg = "#2a2634" })
hi(0, "TreesitterContextLineNumber", { bg = "#2a2634", fg = "#c8a4a2" })
hi(0, "TroubleCount", { bg = "#231f29", fg = "#a78fc3" })
hi(0, "TroubleNormal", { bg = "#231f29", fg = "#c4c3d4" })
hi(0, "TroubleText", { fg = "#767484" })
hi(0, "Type", { fg = "#8db1b7" })
hi(0, "Underlined", { fg = "#a78fc3", underline = true })
hi(0, "VertSplit", { fg = "#55545e" })
hi(0, "VimwikiHR", { fg = "#767484" })
hi(0, "VimwikiHeader1", { link = "markdownH1" })
hi(0, "VimwikiHeader2", { link = "markdownH2" })
hi(0, "VimwikiHeader3", { link = "markdownH3" })
hi(0, "VimwikiHeader4", { link = "markdownH4" })
hi(0, "VimwikiHeader5", { link = "markdownH5" })
hi(0, "VimwikiHeader6", { link = "markdownH6" })
hi(0, "VimwikiHeaderChar", { fg = "#767484" })
hi(0, "VimwikiLink", { link = "markdownUrl" })
hi(0, "VimwikiList", { fg = "#a78fc3" })
hi(0, "VimwikiNoExistsLink", { fg = "#c45d7a" })
hi(0, "Visual", { bg = "#434149" })
hi(0, "WarningMsg", { bold = true, fg = "#d4a868" })
hi(0, "WhichKey", { fg = "#a78fc3" })
hi(0, "WhichKeyBorder", { fg = "#55545e" })
hi(0, "WhichKeyDesc", { fg = "#d4a868" })
hi(0, "WhichKeyFloat", { bg = "#231f29" })
hi(0, "WhichKeyGroup", { fg = "#8db1b7" })
hi(0, "WhichKeyIcon", { fg = "#215a70" })
hi(0, "WhichKeyIconAzure", { fg = "#215a70" })
hi(0, "WhichKeyIconBlue", { fg = "#215a70" })
hi(0, "WhichKeyIconCyan", { fg = "#8db1b7" })
hi(0, "WhichKeyIconGreen", { fg = "#849390" })
hi(0, "WhichKeyIconGrey", { fg = "#767484" })
hi(0, "WhichKeyIconOrange", { fg = "#c8a4a2" })
hi(0, "WhichKeyIconPurple", { fg = "#a78fc3" })
hi(0, "WhichKeyIconRed", { fg = "#c45d7a" })
hi(0, "WhichKeyIconYellow", { fg = "#d4a868" })
hi(0, "WhichKeyNormal", { link = "NormalFloat" })
hi(0, "WhichKeySeparator", { fg = "#767484" })
hi(0, "WhichKeyTitle", { link = "FloatTitle" })
hi(0, "WhichKeyValue", { fg = "#c8a4a2" })
hi(0, "WildMenu", { link = "IncSearch" })
hi(0, "WinBar", { bg = "#231f29", fg = "#767484" })
hi(0, "WinBarNC", { bg = "#201e25", blend = 60, fg = "#55545e" })
hi(0, "WinSeparator", { fg = "#55545e" })
hi(0, "WinShiftCursorLineNr", { bg = "#434149", bold = true, fg = "#c4c3d4" })
hi(0, "WinShiftEndOfBuffer", { bg = "#434149", fg = "#292830" })
hi(0, "WinShiftFoldColumn", { bg = "#434149", fg = "#55545e" })
hi(0, "WinShiftLineNr", { bg = "#434149", fg = "#55545e" })
hi(0, "WinShiftNormal", { bg = "#434149" })
hi(0, "WinShiftSignColumn", { bg = "#434149", fg = "#c4c3d4" })
hi(0, "WinShiftWindowPicker", { bg = "#4898be", bold = true, fg = "#d1d1d1" })
hi(0, "diffAdded", { link = "DiffAdd" })
hi(0, "diffChanged", { link = "DiffChange" })
hi(0, "diffRemoved", { link = "DiffDelete" })
hi(0, "healthError", { fg = "#c45d7a" })
hi(0, "healthSuccess", { fg = "#8db1b7" })
hi(0, "healthWarning", { fg = "#d4a868" })
hi(0, "htmlArg", { fg = "#a78fc3" })
hi(0, "htmlBold", { bold = true })
hi(0, "htmlEndTag", { fg = "#767484" })
hi(0, "htmlH1", { link = "markdownH1" })
hi(0, "htmlH2", { link = "markdownH2" })
hi(0, "htmlH3", { link = "markdownH3" })
hi(0, "htmlH4", { link = "markdownH4" })
hi(0, "htmlH5", { link = "markdownH5" })
hi(0, "htmlItalic", { italic = true })
hi(0, "htmlLink", { link = "markdownUrl" })
hi(0, "htmlTag", { fg = "#767484" })
hi(0, "htmlTagN", { fg = "#c4c3d4" })
hi(0, "htmlTagName", { fg = "#8db1b7" })
hi(0, "lCursor", { bg = "#e6e1f2", fg = "#000001" })
hi(0, "lualine_a_13_command", { bg = "#e87a87", fg = "#000001" })
hi(0, "lualine_a_13_inactive", { bg = "#1c1a21", fg = "#55545e" })
hi(0, "lualine_a_13_insert", { bg = "#abd0d2", fg = "#000001" })
hi(0, "lualine_a_13_normal", { bg = "#e7c3bb", fg = "#000001" })
hi(0, "lualine_a_13_replace", { bg = "#3a7888", fg = "#000001" })
hi(0, "lualine_a_13_terminal", { bg = "#e7c3bb", fg = "#000001" })
hi(0, "lualine_a_13_visual", { bg = "#cdabdc", fg = "#000001" })
hi(0, "lualine_a_23_command", { bg = "#e87a87", fg = "#000001" })
hi(0, "lualine_a_23_inactive", { bg = "#1c1a21", fg = "#55545e" })
hi(0, "lualine_a_23_insert", { bg = "#abd0d2", fg = "#000001" })
hi(0, "lualine_a_23_normal", { bg = "#e7c3bb", fg = "#000001" })
hi(0, "lualine_a_23_replace", { bg = "#3a7888", fg = "#000001" })
hi(0, "lualine_a_23_terminal", { bg = "#e7c3bb", fg = "#000001" })
hi(0, "lualine_a_23_visual", { bg = "#cdabdc", fg = "#000001" })
hi(0, "lualine_a_command", { bg = "#e87a87", bold = true, fg = "#000001" })
hi(0, "lualine_a_inactive", { bg = "#1c1a21", bold = true, fg = "#55545e" })
hi(0, "lualine_a_insert", { bg = "#abd0d2", bold = true, fg = "#000001" })
hi(0, "lualine_a_normal", { bg = "#e7c3bb", bold = true, fg = "#000001" })
hi(0, "lualine_a_replace", { bg = "#3a7888", bold = true, fg = "#000001" })
hi(0, "lualine_a_visual", { bg = "#cdabdc", bold = true, fg = "#000001" })
hi(0, "lualine_b_12_command", { bg = "#2a2634", bold = true, fg = "#c45d7a" })
hi(0, "lualine_b_12_inactive", { bg = "#1c1a21", bold = true, fg = "#55545e" })
hi(0, "lualine_b_12_insert", { bg = "#2a2634", bold = true, fg = "#8db1b7" })
hi(0, "lualine_b_12_normal", { bg = "#2a2634", bold = true, fg = "#c8a4a2" })
hi(0, "lualine_b_12_replace", { bg = "#2a2634", bold = true, fg = "#215a70" })
hi(0, "lualine_b_12_terminal", { bg = "#2a2634", bold = true, fg = "#c8a4a2" })
hi(0, "lualine_b_12_visual", { bg = "#2a2634", bold = true, fg = "#a78fc3" })
hi(0, "lualine_b_22_command", { bg = "#2a2634", bold = true, fg = "#c45d7a" })
hi(0, "lualine_b_22_inactive", { bg = "#1c1a21", bold = true, fg = "#55545e" })
hi(0, "lualine_b_22_insert", { bg = "#2a2634", bold = true, fg = "#8db1b7" })
hi(0, "lualine_b_22_normal", { bg = "#2a2634", bold = true, fg = "#c8a4a2" })
hi(0, "lualine_b_22_replace", { bg = "#2a2634", bold = true, fg = "#215a70" })
hi(0, "lualine_b_22_terminal", { bg = "#2a2634", bold = true, fg = "#c8a4a2" })
hi(0, "lualine_b_22_visual", { bg = "#2a2634", bold = true, fg = "#a78fc3" })
hi(0, "lualine_b_command", { bg = "#2a2634", fg = "#c45d7a" })
hi(0, "lualine_b_inactive", { bg = "#1c1a21", fg = "#55545e" })
hi(0, "lualine_b_insert", { bg = "#2a2634", fg = "#8db1b7" })
hi(0, "lualine_b_normal", { bg = "#2a2634", fg = "#c8a4a2" })
hi(0, "lualine_b_replace", { bg = "#2a2634", fg = "#215a70" })
hi(0, "lualine_b_visual", { bg = "#2a2634", fg = "#a78fc3" })
hi(0, "lualine_c_11_command", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_11_inactive", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_11_insert", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_11_normal", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_11_replace", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_11_terminal", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_11_visual", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_21_command", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_21_inactive", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_21_insert", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_21_normal", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_21_replace", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_21_terminal", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_21_visual", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_command", { bg = "#1c1a21", fg = "#c4c3d4" })
hi(0, "lualine_c_diff_added_0_command", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_diff_added_0_inactive", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_diff_added_0_insert", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_diff_added_0_normal", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_diff_added_0_replace", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_diff_added_0_terminal", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_diff_added_0_visual", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_diff_added_command", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_diff_added_inactive", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_diff_added_insert", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_diff_added_normal", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_diff_added_replace", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_diff_added_terminal", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_diff_added_visual", { bg = "#1c1a21", fg = "#82a159" })
hi(0, "lualine_c_diff_modified_0_command", { bg = "#1c1a21", fg = "#caa56f" })
hi(0, "lualine_c_diff_modified_0_inactive", { bg = "#1c1a21", fg = "#caa56f" })
hi(0, "lualine_c_diff_modified_0_insert", { bg = "#1c1a21", fg = "#caa56f" })
hi(0, "lualine_c_diff_modified_0_normal", { bg = "#1c1a21", fg = "#caa56f" })
hi(0, "lualine_c_diff_modified_0_replace", { bg = "#1c1a21", fg = "#caa56f" })
hi(0, "lualine_c_diff_modified_0_terminal", { bg = "#1c1a21", fg = "#caa56f" })
hi(0, "lualine_c_diff_modified_0_visual", { bg = "#1c1a21", fg = "#caa56f" })
hi(0, "lualine_c_diff_modified_command", { bg = "#1c1a21", fg = "#caa56f" })
hi(0, "lualine_c_diff_modified_inactive", { bg = "#1c1a21", fg = "#caa56f" })
hi(0, "lualine_c_diff_modified_insert", { bg = "#1c1a21", fg = "#caa56f" })
hi(0, "lualine_c_diff_modified_normal", { bg = "#1c1a21", fg = "#caa56f" })
hi(0, "lualine_c_diff_modified_replace", { bg = "#1c1a21", fg = "#caa56f" })
hi(0, "lualine_c_diff_modified_terminal", { bg = "#1c1a21", fg = "#caa56f" })
hi(0, "lualine_c_diff_modified_visual", { bg = "#1c1a21", fg = "#caa56f" })
hi(0, "lualine_c_diff_removed_0_command", { bg = "#1c1a21", fg = "#c44e54" })
hi(0, "lualine_c_diff_removed_0_inactive", { bg = "#1c1a21", fg = "#c44e54" })
hi(0, "lualine_c_diff_removed_0_insert", { bg = "#1c1a21", fg = "#c44e54" })
hi(0, "lualine_c_diff_removed_0_normal", { bg = "#1c1a21", fg = "#c44e54" })
hi(0, "lualine_c_diff_removed_0_replace", { bg = "#1c1a21", fg = "#c44e54" })
hi(0, "lualine_c_diff_removed_0_terminal", { bg = "#1c1a21", fg = "#c44e54" })
hi(0, "lualine_c_diff_removed_0_visual", { bg = "#1c1a21", fg = "#c44e54" })
hi(0, "lualine_c_diff_removed_command", { bg = "#1c1a21", fg = "#c44e54" })
hi(0, "lualine_c_diff_removed_inactive", { bg = "#1c1a21", fg = "#c44e54" })
hi(0, "lualine_c_diff_removed_insert", { bg = "#1c1a21", fg = "#c44e54" })
hi(0, "lualine_c_diff_removed_normal", { bg = "#1c1a21", fg = "#c44e54" })
hi(0, "lualine_c_diff_removed_replace", { bg = "#1c1a21", fg = "#c44e54" })
hi(0, "lualine_c_diff_removed_terminal", { bg = "#1c1a21", fg = "#c44e54" })
hi(0, "lualine_c_diff_removed_visual", { bg = "#1c1a21", fg = "#c44e54" })
hi(0, "lualine_c_inactive", { bg = "#1c1a21", fg = "#55545e" })
hi(0, "lualine_c_insert", { bg = "#1c1a21", fg = "#c4c3d4" })
hi(0, "lualine_c_normal", { bg = "#1c1a21", fg = "#c4c3d4" })
hi(0, "lualine_c_replace", { bg = "#1c1a21", fg = "#c4c3d4" })
hi(0, "lualine_c_visual", { bg = "#1c1a21", fg = "#c4c3d4" })
hi(0, "lualine_transitional_lualine_a_13_command_to_lualine_b_12_command", { bg = "#2a2634", fg = "#c45d7a" })
hi(0, "lualine_transitional_lualine_a_13_insert_to_lualine_c_insert", { bg = "#1c1a21", fg = "#8db1b7" })
hi(0, "lualine_transitional_lualine_a_13_normal_to_lualine_b_12_normal", { bg = "#2a2634", fg = "#c8a4a2" })
hi(0, "lualine_transitional_lualine_a_13_normal_to_lualine_c_normal", { bg = "#1c1a21", fg = "#c8a4a2" })
hi(0, "lualine_transitional_lualine_b_12_command_to_lualine_c_command", { bg = "#1c1a21", fg = "#0d0c19" })
hi(0, "lualine_transitional_lualine_b_12_normal_to_lualine_c_normal", { bg = "#1c1a21", fg = "#0d0c19" })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_c_command", { bg = "#1c1a21", fg = "#0d0c19" })
hi(0, "lualine_transitional_lualine_b_insert_to_lualine_c_insert", { bg = "#1c1a21", fg = "#0d0c19" })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_normal", { bg = "#1c1a21", fg = "#0d0c19" })
hi(0, "lualine_transitional_lualine_z_progress_command_to_lualine_b_command", { bg = "#2a2634", fg = "#c45d7a" })
hi(0, "lualine_transitional_lualine_z_progress_insert_to_lualine_b_insert", { bg = "#2a2634", fg = "#8db1b7" })
hi(0, "lualine_transitional_lualine_z_progress_normal_to_lualine_b_normal", { bg = "#2a2634", fg = "#c8a4a2" })
hi(0, "lualine_x_16_command", { bg = "#1c1a21", bold = true, fg = "#c4c3d4" })
hi(0, "lualine_x_16_inactive", { bg = "#1c1a21", bold = true, fg = "#55545e" })
hi(0, "lualine_x_16_insert", { bg = "#1c1a21", bold = true, fg = "#c4c3d4" })
hi(0, "lualine_x_16_normal", { bg = "#1c1a21", bold = true, fg = "#c4c3d4" })
hi(0, "lualine_x_16_replace", { bg = "#1c1a21", bold = true, fg = "#c4c3d4" })
hi(0, "lualine_x_16_terminal", { bg = "#1c1a21", bold = true, fg = "#c4c3d4" })
hi(0, "lualine_x_16_visual", { bg = "#1c1a21", bold = true, fg = "#c4c3d4" })
hi(0, "lualine_x_4_command", { bg = "#1c1a21", bold = true, fg = "#c4c3d4" })
hi(0, "lualine_x_4_inactive", { bg = "#1c1a21", bold = true, fg = "#55545e" })
hi(0, "lualine_x_4_insert", { bg = "#1c1a21", bold = true, fg = "#c4c3d4" })
hi(0, "lualine_x_4_normal", { bg = "#1c1a21", bold = true, fg = "#c4c3d4" })
hi(0, "lualine_x_4_replace", { bg = "#1c1a21", bold = true, fg = "#c4c3d4" })
hi(0, "lualine_x_4_terminal", { bg = "#1c1a21", bold = true, fg = "#c4c3d4" })
hi(0, "lualine_x_4_visual", { bg = "#1c1a21", bold = true, fg = "#c4c3d4" })
hi(0, "lualine_x_copilot_disabled_command", { bg = "#1c1a21", fg = "#505a7b" })
hi(0, "lualine_x_copilot_disabled_inactive", { bg = "#1c1a21", fg = "#505a7b" })
hi(0, "lualine_x_copilot_disabled_insert", { bg = "#1c1a21", fg = "#505a7b" })
hi(0, "lualine_x_copilot_disabled_normal", { bg = "#1c1a21", fg = "#505a7b" })
hi(0, "lualine_x_copilot_disabled_replace", { bg = "#1c1a21", fg = "#505a7b" })
hi(0, "lualine_x_copilot_disabled_terminal", { bg = "#1c1a21", fg = "#505a7b" })
hi(0, "lualine_x_copilot_disabled_visual", { bg = "#1c1a21", fg = "#505a7b" })
hi(0, "lualine_x_copilot_enabled_command", { bg = "#1c1a21", fg = "#49d96c" })
hi(0, "lualine_x_copilot_enabled_inactive", { bg = "#1c1a21", fg = "#49d96c" })
hi(0, "lualine_x_copilot_enabled_insert", { bg = "#1c1a21", fg = "#49d96c" })
hi(0, "lualine_x_copilot_enabled_normal", { bg = "#1c1a21", fg = "#49d96c" })
hi(0, "lualine_x_copilot_enabled_replace", { bg = "#1c1a21", fg = "#49d96c" })
hi(0, "lualine_x_copilot_enabled_terminal", { bg = "#1c1a21", fg = "#49d96c" })
hi(0, "lualine_x_copilot_enabled_visual", { bg = "#1c1a21", fg = "#49d96c" })
hi(0, "lualine_x_copilot_offline_command", { bg = "#1c1a21", fg = "#dd9f5d" })
hi(0, "lualine_x_copilot_offline_inactive", { bg = "#1c1a21", fg = "#dd9f5d" })
hi(0, "lualine_x_copilot_offline_insert", { bg = "#1c1a21", fg = "#dd9f5d" })
hi(0, "lualine_x_copilot_offline_normal", { bg = "#1c1a21", fg = "#dd9f5d" })
hi(0, "lualine_x_copilot_offline_replace", { bg = "#1c1a21", fg = "#dd9f5d" })
hi(0, "lualine_x_copilot_offline_terminal", { bg = "#1c1a21", fg = "#dd9f5d" })
hi(0, "lualine_x_copilot_offline_visual", { bg = "#1c1a21", fg = "#dd9f5d" })
hi(0, "lualine_x_copilot_sleep_command", { bg = "#1c1a21", fg = "#969cad" })
hi(0, "lualine_x_copilot_sleep_inactive", { bg = "#1c1a21", fg = "#969cad" })
hi(0, "lualine_x_copilot_sleep_insert", { bg = "#1c1a21", fg = "#969cad" })
hi(0, "lualine_x_copilot_sleep_normal", { bg = "#1c1a21", fg = "#969cad" })
hi(0, "lualine_x_copilot_sleep_replace", { bg = "#1c1a21", fg = "#969cad" })
hi(0, "lualine_x_copilot_sleep_terminal", { bg = "#1c1a21", fg = "#969cad" })
hi(0, "lualine_x_copilot_sleep_visual", { bg = "#1c1a21", fg = "#969cad" })
hi(0, "lualine_x_copilot_spinner_command", { bg = "#1c1a21", fg = "#505a7b" })
hi(0, "lualine_x_copilot_spinner_inactive", { bg = "#1c1a21", fg = "#505a7b" })
hi(0, "lualine_x_copilot_spinner_insert", { bg = "#1c1a21", fg = "#505a7b" })
hi(0, "lualine_x_copilot_spinner_normal", { bg = "#1c1a21", fg = "#505a7b" })
hi(0, "lualine_x_copilot_spinner_replace", { bg = "#1c1a21", fg = "#505a7b" })
hi(0, "lualine_x_copilot_spinner_terminal", { bg = "#1c1a21", fg = "#505a7b" })
hi(0, "lualine_x_copilot_spinner_visual", { bg = "#1c1a21", fg = "#505a7b" })
hi(0, "lualine_x_copilot_unknown_command", { bg = "#1c1a21", fg = "#d74344" })
hi(0, "lualine_x_copilot_unknown_inactive", { bg = "#1c1a21", fg = "#d74344" })
hi(0, "lualine_x_copilot_unknown_insert", { bg = "#1c1a21", fg = "#d74344" })
hi(0, "lualine_x_copilot_unknown_normal", { bg = "#1c1a21", fg = "#d74344" })
hi(0, "lualine_x_copilot_unknown_replace", { bg = "#1c1a21", fg = "#d74344" })
hi(0, "lualine_x_copilot_unknown_terminal", { bg = "#1c1a21", fg = "#d74344" })
hi(0, "lualine_x_copilot_unknown_visual", { bg = "#1c1a21", fg = "#d74344" })
hi(0, "lualine_x_diagnostics_error_0_command", { bg = "#1c1a21", fg = "#c45d7a" })
hi(0, "lualine_x_diagnostics_error_0_inactive", { bg = "#1c1a21", fg = "#c45d7a" })
hi(0, "lualine_x_diagnostics_error_0_insert", { bg = "#1c1a21", fg = "#c45d7a" })
hi(0, "lualine_x_diagnostics_error_0_normal", { bg = "#1c1a21", fg = "#c45d7a" })
hi(0, "lualine_x_diagnostics_error_0_replace", { bg = "#1c1a21", fg = "#c45d7a" })
hi(0, "lualine_x_diagnostics_error_0_terminal", { bg = "#1c1a21", fg = "#c45d7a" })
hi(0, "lualine_x_diagnostics_error_0_visual", { bg = "#1c1a21", fg = "#c45d7a" })
hi(0, "lualine_x_diagnostics_error_command", { bg = "#1c1a21", fg = "#c45d7a" })
hi(0, "lualine_x_diagnostics_error_inactive", { bg = "#1c1a21", fg = "#c45d7a" })
hi(0, "lualine_x_diagnostics_error_insert", { bg = "#1c1a21", fg = "#c45d7a" })
hi(0, "lualine_x_diagnostics_error_normal", { bg = "#1c1a21", fg = "#c45d7a" })
hi(0, "lualine_x_diagnostics_error_replace", { bg = "#1c1a21", fg = "#c45d7a" })
hi(0, "lualine_x_diagnostics_error_terminal", { bg = "#1c1a21", fg = "#c45d7a" })
hi(0, "lualine_x_diagnostics_error_visual", { bg = "#1c1a21", fg = "#c45d7a" })
hi(0, "lualine_x_diagnostics_hint_0_command", { bg = "#1c1a21", fg = "#a78fc3" })
hi(0, "lualine_x_diagnostics_hint_0_inactive", { bg = "#1c1a21", fg = "#a78fc3" })
hi(0, "lualine_x_diagnostics_hint_0_insert", { bg = "#1c1a21", fg = "#a78fc3" })
hi(0, "lualine_x_diagnostics_hint_0_normal", { bg = "#1c1a21", fg = "#a78fc3" })
hi(0, "lualine_x_diagnostics_hint_0_replace", { bg = "#1c1a21", fg = "#a78fc3" })
hi(0, "lualine_x_diagnostics_hint_0_terminal", { bg = "#1c1a21", fg = "#a78fc3" })
hi(0, "lualine_x_diagnostics_hint_0_visual", { bg = "#1c1a21", fg = "#a78fc3" })
hi(0, "lualine_x_diagnostics_hint_command", { bg = "#1c1a21", fg = "#a78fc3" })
hi(0, "lualine_x_diagnostics_hint_inactive", { bg = "#1c1a21", fg = "#a78fc3" })
hi(0, "lualine_x_diagnostics_hint_insert", { bg = "#1c1a21", fg = "#a78fc3" })
hi(0, "lualine_x_diagnostics_hint_normal", { bg = "#1c1a21", fg = "#a78fc3" })
hi(0, "lualine_x_diagnostics_hint_replace", { bg = "#1c1a21", fg = "#a78fc3" })
hi(0, "lualine_x_diagnostics_hint_terminal", { bg = "#1c1a21", fg = "#a78fc3" })
hi(0, "lualine_x_diagnostics_hint_visual", { bg = "#1c1a21", fg = "#a78fc3" })
hi(0, "lualine_x_diagnostics_info_0_command", { bg = "#1c1a21", fg = "#8db1b7" })
hi(0, "lualine_x_diagnostics_info_0_inactive", { bg = "#1c1a21", fg = "#8db1b7" })
hi(0, "lualine_x_diagnostics_info_0_insert", { bg = "#1c1a21", fg = "#8db1b7" })
hi(0, "lualine_x_diagnostics_info_0_normal", { bg = "#1c1a21", fg = "#8db1b7" })
hi(0, "lualine_x_diagnostics_info_0_replace", { bg = "#1c1a21", fg = "#8db1b7" })
hi(0, "lualine_x_diagnostics_info_0_terminal", { bg = "#1c1a21", fg = "#8db1b7" })
hi(0, "lualine_x_diagnostics_info_0_visual", { bg = "#1c1a21", fg = "#8db1b7" })
hi(0, "lualine_x_diagnostics_info_command", { bg = "#1c1a21", fg = "#8db1b7" })
hi(0, "lualine_x_diagnostics_info_inactive", { bg = "#1c1a21", fg = "#8db1b7" })
hi(0, "lualine_x_diagnostics_info_insert", { bg = "#1c1a21", fg = "#8db1b7" })
hi(0, "lualine_x_diagnostics_info_normal", { bg = "#1c1a21", fg = "#8db1b7" })
hi(0, "lualine_x_diagnostics_info_replace", { bg = "#1c1a21", fg = "#8db1b7" })
hi(0, "lualine_x_diagnostics_info_terminal", { bg = "#1c1a21", fg = "#8db1b7" })
hi(0, "lualine_x_diagnostics_info_visual", { bg = "#1c1a21", fg = "#8db1b7" })
hi(0, "lualine_x_diagnostics_warn_0_command", { bg = "#1c1a21", fg = "#d4a868" })
hi(0, "lualine_x_diagnostics_warn_0_inactive", { bg = "#1c1a21", fg = "#d4a868" })
hi(0, "lualine_x_diagnostics_warn_0_insert", { bg = "#1c1a21", fg = "#d4a868" })
hi(0, "lualine_x_diagnostics_warn_0_normal", { bg = "#1c1a21", fg = "#d4a868" })
hi(0, "lualine_x_diagnostics_warn_0_replace", { bg = "#1c1a21", fg = "#d4a868" })
hi(0, "lualine_x_diagnostics_warn_0_terminal", { bg = "#1c1a21", fg = "#d4a868" })
hi(0, "lualine_x_diagnostics_warn_0_visual", { bg = "#1c1a21", fg = "#d4a868" })
hi(0, "lualine_x_diagnostics_warn_command", { bg = "#1c1a21", fg = "#d4a868" })
hi(0, "lualine_x_diagnostics_warn_inactive", { bg = "#1c1a21", fg = "#d4a868" })
hi(0, "lualine_x_diagnostics_warn_insert", { bg = "#1c1a21", fg = "#d4a868" })
hi(0, "lualine_x_diagnostics_warn_normal", { bg = "#1c1a21", fg = "#d4a868" })
hi(0, "lualine_x_diagnostics_warn_replace", { bg = "#1c1a21", fg = "#d4a868" })
hi(0, "lualine_x_diagnostics_warn_terminal", { bg = "#1c1a21", fg = "#d4a868" })
hi(0, "lualine_x_diagnostics_warn_visual", { bg = "#1c1a21", fg = "#d4a868" })
hi(0, "lualine_x_filetype_DevIconDefault_command", { bg = "#1c1a21", fg = "#5b6569" })
hi(0, "lualine_x_filetype_DevIconDefault_inactive", { bg = "#1c1a21", fg = "#5b6569" })
hi(0, "lualine_x_filetype_DevIconDefault_insert", { bg = "#1c1a21", fg = "#5b6569" })
hi(0, "lualine_x_filetype_DevIconDefault_normal", { bg = "#1c1a21", fg = "#5b6569" })
hi(0, "lualine_x_filetype_DevIconDefault_replace", { bg = "#1c1a21", fg = "#5b6569" })
hi(0, "lualine_x_filetype_DevIconDefault_terminal", { bg = "#1c1a21", fg = "#5b6569" })
hi(0, "lualine_x_filetype_DevIconDefault_visual", { bg = "#1c1a21", fg = "#5b6569" })
hi(0, "lualine_x_filetype_DevIconHtml_command", { bg = "#1c1a21", fg = "#bd3a19" })
hi(0, "lualine_x_filetype_DevIconHtml_inactive", { bg = "#1c1a21", fg = "#bd3a19" })
hi(0, "lualine_x_filetype_DevIconHtml_insert", { bg = "#1c1a21", fg = "#bd3a19" })
hi(0, "lualine_x_filetype_DevIconHtml_normal", { bg = "#1c1a21", fg = "#bd3a19" })
hi(0, "lualine_x_filetype_DevIconHtml_replace", { bg = "#1c1a21", fg = "#bd3a19" })
hi(0, "lualine_x_filetype_DevIconHtml_terminal", { bg = "#1c1a21", fg = "#bd3a19" })
hi(0, "lualine_x_filetype_DevIconHtml_visual", { bg = "#1c1a21", fg = "#bd3a19" })
hi(0, "lualine_x_filetype_DevIconScss_command", { bg = "#1c1a21", fg = "#cd436e" })
hi(0, "lualine_x_filetype_DevIconScss_inactive", { bg = "#1c1a21", fg = "#cd436e" })
hi(0, "lualine_x_filetype_DevIconScss_insert", { bg = "#1c1a21", fg = "#cd436e" })
hi(0, "lualine_x_filetype_DevIconScss_normal", { bg = "#1c1a21", fg = "#cd436e" })
hi(0, "lualine_x_filetype_DevIconScss_replace", { bg = "#1c1a21", fg = "#cd436e" })
hi(0, "lualine_x_filetype_DevIconScss_terminal", { bg = "#1c1a21", fg = "#cd436e" })
hi(0, "lualine_x_filetype_DevIconScss_visual", { bg = "#1c1a21", fg = "#cd436e" })
hi(0, "lualine_x_filetype_DevIconTypeScript_command", { bg = "#1c1a21", fg = "#437f99" })
hi(0, "lualine_x_filetype_DevIconTypeScript_inactive", { bg = "#1c1a21", fg = "#437f99" })
hi(0, "lualine_x_filetype_DevIconTypeScript_insert", { bg = "#1c1a21", fg = "#437f99" })
hi(0, "lualine_x_filetype_DevIconTypeScript_normal", { bg = "#1c1a21", fg = "#437f99" })
hi(0, "lualine_x_filetype_DevIconTypeScript_replace", { bg = "#1c1a21", fg = "#437f99" })
hi(0, "lualine_x_filetype_DevIconTypeScript_terminal", { bg = "#1c1a21", fg = "#437f99" })
hi(0, "lualine_x_filetype_DevIconTypeScript_visual", { bg = "#1c1a21", fg = "#437f99" })
hi(0, "lualine_z_progress_0_command", { bg = "#e87a87", fg = "#000001" })
hi(0, "lualine_z_progress_0_inactive", { bg = "#1c1a21", fg = "#55545e" })
hi(0, "lualine_z_progress_0_insert", { bg = "#abd0d2", fg = "#000001" })
hi(0, "lualine_z_progress_0_normal", { bg = "#e7c3bb", fg = "#000001" })
hi(0, "lualine_z_progress_0_replace", { bg = "#3a7888", fg = "#000001" })
hi(0, "lualine_z_progress_0_terminal", { bg = "#e7c3bb", fg = "#000001" })
hi(0, "lualine_z_progress_0_visual", { bg = "#cdabdc", fg = "#000001" })
hi(0, "lualine_z_progress_command", { bg = "#e87a87", fg = "#000001" })
hi(0, "lualine_z_progress_inactive", { bg = "#1c1a21", fg = "#55545e" })
hi(0, "lualine_z_progress_insert", { bg = "#abd0d2", fg = "#000001" })
hi(0, "lualine_z_progress_normal", { bg = "#e7c3bb", fg = "#000001" })
hi(0, "lualine_z_progress_replace", { bg = "#3a7888", fg = "#000001" })
hi(0, "lualine_z_progress_terminal", { bg = "#e7c3bb", fg = "#000001" })
hi(0, "lualine_z_progress_visual", { bg = "#cdabdc", fg = "#000001" })
hi(0, "markdownDelimiter", { fg = "#767484" })
hi(0, "markdownH1", { bold = true, fg = "#a78fc3" })
hi(0, "markdownH1Delimiter", { link = "markdownH1" })
hi(0, "markdownH2", { bold = true, fg = "#8db1b7" })
hi(0, "markdownH2Delimiter", { link = "markdownH2" })
hi(0, "markdownH3", { bold = true, fg = "#c8a4a2" })
hi(0, "markdownH3Delimiter", { link = "markdownH3" })
hi(0, "markdownH4", { bold = true, fg = "#d4a868" })
hi(0, "markdownH4Delimiter", { link = "markdownH4" })
hi(0, "markdownH5", { bold = true, fg = "#215a70" })
hi(0, "markdownH5Delimiter", { link = "markdownH5" })
hi(0, "markdownH6", { bold = true, fg = "#849390" })
hi(0, "markdownH6Delimiter", { link = "markdownH6" })
hi(0, "markdownLinkText", { link = "markdownUrl" })
hi(0, "markdownUrl", { fg = "#a78fc3", sp = "#c4a7e7", underline = true })
hi(0, "mkdCode", { fg = "#8db1b7", italic = true })
hi(0, "mkdCodeDelimiter", { fg = "#c8a4a2" })
hi(0, "mkdCodeEnd", { fg = "#8db1b7" })
hi(0, "mkdCodeStart", { fg = "#8db1b7" })
hi(0, "mkdFootnotes", { fg = "#8db1b7" })
hi(0, "mkdID", { fg = "#8db1b7", underline = true })
hi(0, "mkdInlineURL", { link = "markdownUrl" })
hi(0, "mkdLink", { link = "markdownUrl" })
hi(0, "mkdLinkDef", { link = "markdownUrl" })
hi(0, "mkdListItemLine", { fg = "#c4c3d4" })
hi(0, "mkdRule", { fg = "#767484" })
hi(0, "mkdURL", { link = "markdownUrl" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#26233a"
g.terminal_color_1 = "#eb6f92"
g.terminal_color_2 = "#31748f"
g.terminal_color_3 = "#f6c177"
g.terminal_color_4 = "#9ccfd8"
g.terminal_color_5 = "#c4a7e7"
g.terminal_color_6 = "#ebbcba"
g.terminal_color_7 = "#e0def4"
g.terminal_color_8 = "#908caa"
g.terminal_color_9 = "#eb6f92"
g.terminal_color_10 = "#31748f"
g.terminal_color_11 = "#f6c177"
g.terminal_color_12 = "#9ccfd8"
g.terminal_color_13 = "#c4a7e7"
g.terminal_color_14 = "#ebbcba"
g.terminal_color_15 = "#e0def4"
