-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "rose-pine"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@attribute.diff", { fg = "#e3bc87" })
hi(0, "@character.special", { link = "Character" })
hi(0, "@class", { fg = "#aac2c6" })
hi(0, "@comment.error", { fg = "#cf778d" })
hi(0, "@comment.hint", { bg = "#3c3b40", blend = 20, fg = "#b7a4cf" })
hi(0, "@comment.info", { bg = "#3f3f3f", blend = 20, fg = "#aac2c6" })
hi(0, "@comment.note", { bg = "#2b323c", blend = 20, fg = "#4e859d" })
hi(0, "@comment.todo", { bg = "#3b3a3b", blend = 20, fg = "#d09b98" })
hi(0, "@comment.warning", { fg = "#e3bc87" })
hi(0, "@conceal", { link = "Conceal" })
hi(0, "@conceal.markdown", { fg = "#888889" })
hi(0, "@conditional", { link = "Conditional" })
hi(0, "@constant", { fg = "#e3bc87" })
hi(0, "@constant.builtin", { bold = true, fg = "#e3bc87" })
hi(0, "@constant.macro", { fg = "#e3bc87" })
hi(0, "@constructor", { fg = "#aac2c6" })
hi(0, "@diff.delta", { bg = "#3b3a3b", blend = 20 })
hi(0, "@diff.minus", { bg = "#3d333b", blend = 20, fg = "#cf778d" })
hi(0, "@diff.plus", { bg = "#3f3f3f", blend = 20, fg = "#aac2c6" })
hi(0, "@field", { fg = "#aac2c6" })
hi(0, "@float", { link = "Number" })
hi(0, "@function", { fg = "#d09b98" })
hi(0, "@function.builtin", { bold = true, fg = "#d09b98" })
hi(0, "@function.macro", { link = "Function" })
hi(0, "@function.method", { fg = "#d09b98" })
hi(0, "@function.method.call", { fg = "#b7a4cf" })
hi(0, "@ibl.indent.char.1", { fg = "#64645e", nocombine = true })
hi(0, "@ibl.indent.char.2", { fg = "#434e4e", nocombine = true })
hi(0, "@ibl.indent.char.3", { fg = "#464646", nocombine = true })
hi(0, "@ibl.indent.char.4", { fg = "#383838", nocombine = true })
hi(0, "@ibl.scope.char.1", { fg = "#d09b98", nocombine = true })
hi(0, "@ibl.scope.char.2", { fg = "#aac2c6", nocombine = true })
hi(0, "@ibl.scope.underline.1", { sp = "#ea9a97", underline = true })
hi(0, "@ibl.scope.underline.2", { sp = "#9ccfd8", underline = true })
hi(0, "@ibl.whitespace.char.1", { fg = "#323238", nocombine = true })
hi(0, "@include", { link = "Include" })
hi(0, "@interface", { fg = "#aac2c6" })
hi(0, "@keyword.conditional", { fg = "#4e859d" })
hi(0, "@keyword.conditional.ternary", { fg = "#4e859d" })
hi(0, "@keyword.debug", { fg = "#d09b98" })
hi(0, "@keyword.directive", { fg = "#b7a4cf" })
hi(0, "@keyword.directive.define", { fg = "#b7a4cf" })
hi(0, "@keyword.exception", { fg = "#4e859d" })
hi(0, "@keyword.import", { fg = "#4e859d" })
hi(0, "@keyword.operator", { fg = "#888889" })
hi(0, "@keyword.repeat", { fg = "#4e859d" })
hi(0, "@keyword.return", { fg = "#4e859d" })
hi(0, "@keyword.storage", { fg = "#aac2c6" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", {})
hi(0, "@lsp.type.comment.c", { link = "@comment" })
hi(0, "@lsp.type.comment.cpp", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@interface" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.namespace.python", { link = "@variable" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.type.variable.svelte", { link = "@variable" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.variable.constant", { link = "@constant" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@macro", { link = "Macro" })
hi(0, "@markup.environment", { link = "Macro" })
hi(0, "@markup.environment.name", { link = "@type" })
hi(0, "@markup.heading", { bold = true, fg = "#aac2c6" })
hi(0, "@markup.heading.1.markdown", { link = "markdownH1" })
hi(0, "@markup.heading.1.marker.markdown", { link = "markdownH1Delimiter" })
hi(0, "@markup.heading.2.markdown", { link = "markdownH2" })
hi(0, "@markup.heading.2.marker.markdown", { link = "markdownH2Delimiter" })
hi(0, "@markup.heading.3.markdown", { link = "markdownH3" })
hi(0, "@markup.heading.3.marker.markdown", { link = "markdownH3Delimiter" })
hi(0, "@markup.heading.4.markdown", { link = "markdownH4" })
hi(0, "@markup.heading.4.marker.markdown", { link = "markdownH4Delimiter" })
hi(0, "@markup.heading.5.markdown", { link = "markdownH5" })
hi(0, "@markup.heading.5.marker.markdown", { link = "markdownH5Delimiter" })
hi(0, "@markup.heading.6.markdown", { link = "markdownH6" })
hi(0, "@markup.heading.6.marker.markdown", { link = "markdownH6Delimiter" })
hi(0, "@markup.link", { link = "Underlined" })
hi(0, "@markup.link.label.markdown_inline", { fg = "#aac2c6" })
hi(0, "@markup.link.markdown_inline", { fg = "#888889" })
hi(0, "@markup.link.url", { fg = "#b7a4cf" })
hi(0, "@markup.list", { fg = "#4e859d" })
hi(0, "@markup.list.checked", { bg = "#2f2f2f", blend = 10, fg = "#aac2c6" })
hi(0, "@markup.list.unchecked", { fg = "#d8d7e4" })
hi(0, "@markup.math", { link = "Special" })
hi(0, "@markup.quote", { fg = "#d8d7e4" })
hi(0, "@markup.raw.delimiter.markdown", { fg = "#888889" })
hi(0, "@method", { fg = "#d09b98" })
hi(0, "@module", { fg = "#d8d7e4" })
hi(0, "@module.builtin", { bold = true, fg = "#d8d7e4" })
hi(0, "@namespace", { link = "Include" })
hi(0, "@number.float", { link = "Number" })
hi(0, "@parameter", { fg = "#b7a4cf", italic = true })
hi(0, "@preproc", { link = "PreProc" })
hi(0, "@property", { fg = "#aac2c6", italic = true })
hi(0, "@punctuation", { fg = "#888889" })
hi(0, "@punctuation.bracket", { fg = "#888889" })
hi(0, "@punctuation.delimiter", { fg = "#888889" })
hi(0, "@punctuation.special", { fg = "#888889" })
hi(0, "@regexp", { link = "String" })
hi(0, "@repeat", { link = "Repeat" })
hi(0, "@storageclass", { link = "StorageClass" })
hi(0, "@string.escape", { fg = "#4e859d" })
hi(0, "@string.regexp", { fg = "#b7a4cf" })
hi(0, "@string.special", { link = "String" })
hi(0, "@string.special.symbol", { link = "Identifier" })
hi(0, "@string.special.url", { fg = "#b7a4cf" })
hi(0, "@symbol", { link = "Identifier" })
hi(0, "@tag.attribute", { fg = "#b7a4cf" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { fg = "#888889" })
hi(0, "@text", { fg = "#d8d7e4" })
hi(0, "@text.danger", { fg = "#cf778d" })
hi(0, "@text.diff.add", { bg = "#3f3f3f", blend = 20, fg = "#aac2c6" })
hi(0, "@text.diff.delete", { bg = "#3d333b", blend = 20, fg = "#cf778d" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.environment", { link = "Macro" })
hi(0, "@text.environment.name", { link = "Type" })
hi(0, "@text.math", { link = "Special" })
hi(0, "@text.note", { link = "SpecialComment" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.title.1.markdown", { link = "markdownH1" })
hi(0, "@text.title.1.marker.markdown", { link = "markdownH1Delimiter" })
hi(0, "@text.title.2.markdown", { link = "markdownH2" })
hi(0, "@text.title.2.marker.markdown", { link = "markdownH2Delimiter" })
hi(0, "@text.title.3.markdown", { link = "markdownH3" })
hi(0, "@text.title.3.marker.markdown", { link = "markdownH3Delimiter" })
hi(0, "@text.title.4.markdown", { link = "markdownH4" })
hi(0, "@text.title.4.marker.markdown", { link = "markdownH4Delimiter" })
hi(0, "@text.title.5.markdown", { link = "markdownH5" })
hi(0, "@text.title.5.marker.markdown", { link = "markdownH5Delimiter" })
hi(0, "@text.title.6.markdown", { link = "markdownH6" })
hi(0, "@text.title.6.marker.markdown", { link = "markdownH6Delimiter" })
hi(0, "@text.underline", { underline = true })
hi(0, "@text.uri", { fg = "#b7a4cf" })
hi(0, "@text.warning", { fg = "#e3bc87" })
hi(0, "@todo", { link = "Todo" })
hi(0, "@type", { fg = "#aac2c6" })
hi(0, "@type.builtin", { bold = true, fg = "#aac2c6" })
hi(0, "@variable", { fg = "#d8d7e4", italic = true })
hi(0, "@variable.builtin", { bold = true, fg = "#cf778d" })
hi(0, "@variable.member", { fg = "#aac2c6" })
hi(0, "@variable.parameter", { fg = "#b7a4cf", italic = true })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "Added", { ctermfg = 10, fg = "#bce7c4" })
hi(0, "AlphaButtons", { fg = "#aac2c6" })
hi(0, "AlphaFooter", { fg = "#e3bc87" })
hi(0, "AlphaHeader", { fg = "#4e859d" })
hi(0, "AlphaShortcut", { fg = "#d09b98" })
hi(0, "AvanteAnnotation", { link = "Comment" })
hi(0, "AvanteConflictAncestor", { bg = "#5b2a69", bold = true })
hi(0, "AvanteConflictAncestorLabel", { bg = "#9646aa" })
hi(0, "AvanteConflictCurrent", { bg = "#5c5557", bold = true })
hi(0, "AvanteConflictCurrentLabel", { bg = "#9a898e" })
hi(0, "AvanteConflictIncoming", { bg = "#3f3f3f", bold = true })
hi(0, "AvanteConflictIncomingLabel", { bg = "#676767" })
hi(0, "AvanteInlineHint", { link = "Keyword" })
hi(0, "AvantePopupHint", { link = "NormalFloat" })
hi(0, "AvanteReversedSubtitle", { fg = "#aac2c6" })
hi(0, "AvanteReversedThirdTitle", { fg = "#b7a4cf" })
hi(0, "AvanteReversedTitle", { fg = "#d09b98" })
hi(0, "AvanteSubtitle", { bg = "#adc4c8", fg = "#3e3e3e" })
hi(0, "AvanteSuggestion", { link = "Comment" })
hi(0, "AvanteThirdTitle", { bg = "#baa7d1", fg = "#3e3e3e" })
hi(0, "AvanteTitle", { bg = "#d39e9b", fg = "#4f4f4f" })
hi(0, "AvanteToBeDeleted", { bg = "#f0caca", strikethrough = true })
hi(0, "BlinkCmpDefault", { fg = "#3e3e3e" })
hi(0, "BlinkCmpDoc", { fg = "#d8d7e4" })
hi(0, "BlinkCmpDocBorder", { fg = "#4f4f4f" })
hi(0, "BlinkCmpGhostText", { fg = "#666666" })
hi(0, "BlinkCmpKindClass", { fg = "#e3bc87" })
hi(0, "BlinkCmpKindCodeium", { fg = "#aac2c6" })
hi(0, "BlinkCmpKindColor", { fg = "#cf778d" })
hi(0, "BlinkCmpKindConstant", { fg = "#e3bc87" })
hi(0, "BlinkCmpKindConstructor", { fg = "#aac2c6" })
hi(0, "BlinkCmpKindCopilot", { fg = "#aac2c6" })
hi(0, "BlinkCmpKindEnum", { fg = "#aac2c6" })
hi(0, "BlinkCmpKindEnumMember", { fg = "#aac2c6" })
hi(0, "BlinkCmpKindEvent", { fg = "#aac2c6" })
hi(0, "BlinkCmpKindField", { fg = "#4e859d" })
hi(0, "BlinkCmpKindFile", { fg = "#aac2c6" })
hi(0, "BlinkCmpKindFolder", { fg = "#aac2c6" })
hi(0, "BlinkCmpKindFunction", { fg = "#aac2c6" })
hi(0, "BlinkCmpKindInterface", { fg = "#e3bc87" })
hi(0, "BlinkCmpKindKeyword", { fg = "#b7a4cf" })
hi(0, "BlinkCmpKindMethod", { fg = "#aac2c6" })
hi(0, "BlinkCmpKindModule", { fg = "#aac2c6" })
hi(0, "BlinkCmpKindOperator", { fg = "#aac2c6" })
hi(0, "BlinkCmpKindProperty", { fg = "#aac2c6" })
hi(0, "BlinkCmpKindReference", { fg = "#cf778d" })
hi(0, "BlinkCmpKindSnippet", { fg = "#d09b98" })
hi(0, "BlinkCmpKindStruct", { fg = "#aac2c6" })
hi(0, "BlinkCmpKindSupermaven", { fg = "#aac2c6" })
hi(0, "BlinkCmpKindTabNine", { fg = "#aac2c6" })
hi(0, "BlinkCmpKindText", { fg = "#4e859d" })
hi(0, "BlinkCmpKindTypeParameter", { fg = "#b7a4cf" })
hi(0, "BlinkCmpKindUnit", { fg = "#4e859d" })
hi(0, "BlinkCmpKindValue", { fg = "#cf778d" })
hi(0, "BlinkCmpKindVariable", { fg = "#d09b98" })
hi(0, "BlinkCmpLabel", { fg = "#666666" })
hi(0, "BlinkCmpLabelDeprecated", { fg = "#666666", strikethrough = true })
hi(0, "BlinkCmpLabelMatch", { bold = true, fg = "#d8d7e4" })
hi(0, "Boolean", { fg = "#d09b98" })
hi(0, "BufferCurrent", { bg = "#34343a", fg = "#d8d7e4" })
hi(0, "BufferCurrentIndex", { bg = "#34343a", fg = "#d8d7e4" })
hi(0, "BufferCurrentMod", { bg = "#34343a", fg = "#aac2c6" })
hi(0, "BufferCurrentSign", { bg = "#34343a", fg = "#888889" })
hi(0, "BufferCurrentTarget", { bg = "#34343a", fg = "#e3bc87" })
hi(0, "BufferInactive", { fg = "#888889" })
hi(0, "BufferInactiveIndex", { fg = "#888889" })
hi(0, "BufferInactiveMod", { fg = "#aac2c6" })
hi(0, "BufferInactiveSign", { fg = "#666666" })
hi(0, "BufferInactiveTarget", { fg = "#e3bc87" })
hi(0, "BufferVisible", { fg = "#888889" })
hi(0, "BufferVisibleIndex", { fg = "#888889" })
hi(0, "BufferVisibleMod", { fg = "#aac2c6" })
hi(0, "BufferVisibleSign", { fg = "#666666" })
hi(0, "BufferVisibleTarget", { fg = "#e3bc87" })
hi(0, "Changed", { ctermfg = 14, fg = "#a1e9e8" })
hi(0, "Character", { fg = "#e3bc87" })
hi(0, "CmpItemAbbr", { fg = "#888889" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#888889", strikethrough = true })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#d8d7e4" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#d8d7e4" })
hi(0, "CmpItemKind", { fg = "#888889" })
hi(0, "CmpItemKindClass", { link = "StorageClass" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindInterface", { link = "Type" })
hi(0, "CmpItemKindMethod", { link = "PreProc" })
hi(0, "CmpItemKindSnippet", { link = "String" })
hi(0, "CmpItemKindVariable", { link = "Identifier" })
hi(0, "ColorColumn", { bg = "#25252b" })
hi(0, "Comment", { fg = "#666666", italic = true })
hi(0, "Conceal", {})
hi(0, "Conditional", { fg = "#4e859d" })
hi(0, "Constant", { fg = "#e3bc87" })
hi(0, "CopilotSuggestion", { fg = "#666666", italic = true })
hi(0, "CurSearch", { bg = "#e6be8a", fg = "#1d1c21" })
hi(0, "Cursor", { bg = "#515151", fg = "#d8d7e4" })
hi(0, "CursorColumn", { bg = "#34343a" })
hi(0, "CursorLine", { bg = "#34343a" })
hi(0, "CursorLineNr", { bold = true, fg = "#d8d7e4" })
hi(0, "CursorLineSign", { bg = "#34343a" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#e3bc87" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#666666" })
hi(0, "DapUIBreakpointsInfo", { link = "DapUIThread" })
hi(0, "DapUIBreakpointsLine", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIBreakpointsPath", { fg = "#aac2c6" })
hi(0, "DapUIDecoration", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIFloatBorder", { fg = "#666666" })
hi(0, "DapUIFrameName", { fg = "#d8d7e4" })
hi(0, "DapUILineNumber", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#aac2c6" })
hi(0, "DapUINormalNC", { bg = "#000000", fg = "#d8d7e4" })
hi(0, "DapUIPlayPause", { fg = "#aff181" })
hi(0, "DapUIPlayPauseNC", { bg = "#232327", fg = "#aff181" })
hi(0, "DapUIRestart", { fg = "#aff181" })
hi(0, "DapUIRestartNC", { bg = "#232327", fg = "#aff181" })
hi(0, "DapUIScope", { link = "DapUIBreakpointsPath" })
hi(0, "DapUISource", { fg = "#b7a4cf" })
hi(0, "DapUIStepBack", { fg = "#59e3e5" })
hi(0, "DapUIStepBackNC", { bg = "#232327", fg = "#59e3e5" })
hi(0, "DapUIStepInto", { fg = "#59e3e5" })
hi(0, "DapUIStepIntoNC", { bg = "#232327", fg = "#59e3e5" })
hi(0, "DapUIStepOut", { fg = "#59e3e5" })
hi(0, "DapUIStepOutNC", { bg = "#232327", fg = "#59e3e5" })
hi(0, "DapUIStepOver", { fg = "#59e3e5" })
hi(0, "DapUIStepOverNC", { bg = "#232327", fg = "#59e3e5" })
hi(0, "DapUIStop", { fg = "#db3767" })
hi(0, "DapUIStopNC", { bg = "#232327", fg = "#db3767" })
hi(0, "DapUIStoppedThread", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIThread", { fg = "#e3bc87" })
hi(0, "DapUIType", { fg = "#c487e5" })
hi(0, "DapUIUnavailable", { fg = "#3b3b3b" })
hi(0, "DapUIUnavailableNC", { bg = "#232327", fg = "#3b3b3b" })
hi(0, "DapUIValue", { fg = "#d8d7e4" })
hi(0, "DapUIVariable", { fg = "#d8d7e4" })
hi(0, "DapUIWatchesEmpty", { fg = "#cf778d" })
hi(0, "DapUIWatchesError", { link = "DapUIWatchesEmpty" })
hi(0, "DapUIWatchesValue", { link = "DapUIThread" })
hi(0, "DapUIWinSelect", { bold = true, ctermfg = 14, fg = "#59e3e5" })
hi(0, "DashboardCenter", { fg = "#e3bc87" })
hi(0, "DashboardFooter", { fg = "#b7a4cf" })
hi(0, "DashboardHeader", { fg = "#4e859d" })
hi(0, "DashboardShortcut", { fg = "#cf778d" })
hi(0, "Debug", { fg = "#d09b98" })
hi(0, "Define", { fg = "#b7a4cf" })
hi(0, "DefinitionCount", { fg = "#d09b98" })
hi(0, "DefinitionIcon", { fg = "#d09b98" })
hi(0, "DefinitionPreviewTitle", { bold = true, fg = "#d09b98" })
hi(0, "Delimiter", { fg = "#888889" })
hi(0, "DiagnosticDefaultError", { link = "DiagnosticError" })
hi(0, "DiagnosticDefaultHint", { link = "DiagnosticHint" })
hi(0, "DiagnosticDefaultInfo", { link = "DiagnosticInfo" })
hi(0, "DiagnosticDefaultOk", { link = "DiagnosticOk" })
hi(0, "DiagnosticDefaultWarn", { link = "DiagnosticWarn" })
hi(0, "DiagnosticERRORReverse", { bg = "#d27a90", fg = "#000000" })
hi(0, "DiagnosticError", { fg = "#cf778d" })
hi(0, "DiagnosticHINTReverse", { bg = "#baa7d1", fg = "#000000" })
hi(0, "DiagnosticHint", { fg = "#b7a4cf" })
hi(0, "DiagnosticINFOReverse", { bg = "#adc4c8", fg = "#000000" })
hi(0, "DiagnosticInfo", { fg = "#aac2c6" })
hi(0, "DiagnosticOk", { fg = "#9fa3a2" })
hi(0, "DiagnosticUnderlineError", { sp = "#eb6f92", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#c4a7e7", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#9ccfd8", undercurl = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#95b1ac", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#f6c177", undercurl = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#2d292f", blend = 10, fg = "#cf778d" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#2d2d33", blend = 10, fg = "#b7a4cf" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#2f2f2f", blend = 10, fg = "#aac2c6" })
hi(0, "DiagnosticVirtualTextOk", { bg = "#2c2c2c", blend = 10, fg = "#9fa3a2" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#2f2f2f", blend = 10, fg = "#e3bc87" })
hi(0, "DiagnosticWARNReverse", { bg = "#e6be8a", fg = "#000000" })
hi(0, "DiagnosticWarn", { fg = "#e3bc87" })
hi(0, "DiffAdd", { bg = "#3f3f3f", blend = 20 })
hi(0, "DiffChange", { bg = "#3b3a3b", blend = 20 })
hi(0, "DiffDelete", { bg = "#3d333b", blend = 20 })
hi(0, "DiffText", { bg = "#5c5557", blend = 40 })
hi(0, "DiffviewDiffAddAsDelete", { bg = "#3d333b" })
hi(0, "DiffviewDim1", { fg = "#666666" })
hi(0, "DiffviewFilePanelCounter", { bold = true, fg = "#d8d7e4" })
hi(0, "DiffviewFilePanelFileName", { fg = "#d8d7e4" })
hi(0, "DiffviewFilePanelTitle", { bold = true, fg = "#aac2c6" })
hi(0, "DiffviewPrimary", { fg = "#d09b98" })
hi(0, "DiffviewSecondary", { fg = "#e3bc87" })
hi(0, "Directory", { bold = true, fg = "#aac2c6" })
hi(0, "DressingSelectIdx", { link = "Special" })
hi(0, "Error", { fg = "#cf778d" })
hi(0, "ErrorMsg", { bold = true, fg = "#cf778d" })
hi(0, "Exception", { fg = "#4e859d" })
hi(0, "FlashLabel", { bg = "#d27a90", fg = "#1d1c21" })
hi(0, "Float", { fg = "#e3bc87" })
hi(0, "FloatBorder", { fg = "#666666" })
hi(0, "FloatShadow", { bg = "#4d4d4d", blend = 80, ctermbg = 0 })
hi(0, "FloatShadowThrough", { bg = "#4d4d4d", blend = 100, ctermbg = 0 })
hi(0, "FloatTitle", { bg = "#25252b", bold = true, fg = "#aac2c6" })
hi(0, "FoldColumn", { fg = "#666666" })
hi(0, "Folded", { bg = "#25252b", fg = "#d8d7e4" })
hi(0, "Function", { fg = "#d09b98" })
hi(0, "FzfLuaBorder", { fg = "#666666" })
hi(0, "FzfLuaBufFlagAlt", { fg = "#888889" })
hi(0, "FzfLuaBufFlagCur", { fg = "#888889" })
hi(0, "FzfLuaCursorLine", { bg = "#34343a", fg = "#d8d7e4" })
hi(0, "FzfLuaFilePart", { fg = "#d8d7e4" })
hi(0, "FzfLuaHeaderBind", { fg = "#d09b98" })
hi(0, "FzfLuaHeaderText", { fg = "#cf778d" })
hi(0, "FzfLuaNormal", { link = "NormalFloat" })
hi(0, "FzfLuaTitle", { link = "FloatTitle" })
hi(0, "GitSignsAdd", { link = "SignAdd" })
hi(0, "GitSignsChange", { link = "SignChange" })
hi(0, "GitSignsDelete", { link = "SignDelete" })
hi(0, "GitSignsStagedAdd", { fg = "#535d5f" })
hi(0, "GitSignsStagedAddCul", { fg = "#535d5f" })
hi(0, "GitSignsStagedAddLn", { bg = "#3f3f3f" })
hi(0, "GitSignsStagedAddNr", { fg = "#535d5f" })
hi(0, "GitSignsStagedChange", { fg = "#5c4f4e" })
hi(0, "GitSignsStagedChangeCul", { fg = "#5c4f4e" })
hi(0, "GitSignsStagedChangeLn", { bg = "#3b3a3b" })
hi(0, "GitSignsStagedChangeNr", { fg = "#5c4f4e" })
hi(0, "GitSignsStagedChangedelete", { fg = "#5c4f4e" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#5c4f4e" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#3b3a3b" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#5c4f4e" })
hi(0, "GitSignsStagedDelete", { fg = "#603a44" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#603a44" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#603a44" })
hi(0, "GitSignsStagedTopdelete", { fg = "#603a44" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#603a44" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#603a44" })
hi(0, "GitSignsStagedUntracked", { fg = "#535d5f" })
hi(0, "GitSignsStagedUntrackedCul", { fg = "#535d5f" })
hi(0, "GitSignsStagedUntrackedLn", { bg = "#3f3f3f" })
hi(0, "GitSignsStagedUntrackedNr", { fg = "#535d5f" })
hi(0, "GrugFarHelpHeader", { fg = "#4e859d" })
hi(0, "GrugFarHelpHeaderKey", { fg = "#e3bc87" })
hi(0, "GrugFarHelpWinActionKey", { fg = "#e3bc87" })
hi(0, "GrugFarHelpWinActionPrefix", { fg = "#aac2c6" })
hi(0, "GrugFarHelpWinActionText", { fg = "#4e859d" })
hi(0, "GrugFarHelpWinHeader", { link = "FloatTitle" })
hi(0, "GrugFarInputLabel", { fg = "#aac2c6" })
hi(0, "GrugFarInputPlaceholder", { link = "Comment" })
hi(0, "GrugFarResultsActionMessage", { fg = "#aac2c6" })
hi(0, "GrugFarResultsChangeIndicator", { fg = "#d09b98" })
hi(0, "GrugFarResultsHeader", { fg = "#4e859d" })
hi(0, "GrugFarResultsLineColumn", { link = "GrugFarResultsLineNo" })
hi(0, "GrugFarResultsLineNo", { fg = "#b7a4cf" })
hi(0, "GrugFarResultsMatch", { link = "CurSearch" })
hi(0, "GrugFarResultsPath", { fg = "#aac2c6" })
hi(0, "GrugFarResultsStats", { fg = "#b7a4cf" })
hi(0, "HopNextKey", { bg = "#3d333b", blend = 20, fg = "#cf778d" })
hi(0, "HopNextKey1", { bg = "#3f3f3f", blend = 20, fg = "#aac2c6" })
hi(0, "HopNextKey2", { bg = "#2b323c", blend = 20, fg = "#4e859d" })
hi(0, "HopUnmatched", { fg = "#666666" })
hi(0, "IblIndent", { fg = "#323238" })
hi(0, "IblScope", { fg = "#aac2c6" })
hi(0, "IblWhitespace", { fg = "#323238" })
hi(0, "Identifier", { fg = "#d8d7e4" })
hi(0, "IlluminatedWordRead", { link = "LspReferenceRead" })
hi(0, "IlluminatedWordText", { link = "LspReferenceText" })
hi(0, "IlluminatedWordWrite", { link = "LspReferenceWrite" })
hi(0, "Include", { fg = "#4e859d" })
hi(0, "IndentBlanklineChar", { fg = "#666666", nocombine = true })
hi(0, "IndentBlanklineIndent1", { bg = "#272721", fg = "#25251f" })
hi(0, "IndentBlanklineIndent2", { bg = "#212525", fg = "#1f2323" })
hi(0, "IndentBlanklineIndent3", { bg = "#222222", fg = "#202020" })
hi(0, "IndentBlanklineIndent4", { bg = "#242524", fg = "#222322" })
hi(0, "IndentBlanklineIndentChar1", { fg = "#64645e" })
hi(0, "IndentBlanklineIndentChar2", { fg = "#434e4e" })
hi(0, "IndentBlanklineIndentChar3", { fg = "#464646" })
hi(0, "IndentBlanklineIndentChar4", { fg = "#383838" })
hi(0, "IndentBlanklineSpaceChar", { fg = "#666666", nocombine = true })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#666666", nocombine = true })
hi(0, "Keyword", { fg = "#4e859d" })
hi(0, "Label", { fg = "#aac2c6" })
hi(0, "LeapLabelPrimary", { link = "IncSearch" })
hi(0, "LeapLabelSecondary", { link = "StatusLineTerm" })
hi(0, "LeapMatch", { link = "MatchParen" })
hi(0, "LineNr", { fg = "#666666" })
hi(0, "LspCodeLens", { fg = "#888889" })
hi(0, "LspCodeLensSeparator", { fg = "#666666" })
hi(0, "LspFloatWinBorder", { fg = "#666666" })
hi(0, "LspFloatWinNormal", { bg = "#25252b" })
hi(0, "LspInlayHint", { bg = "#26262a", blend = 10, fg = "#666666" })
hi(0, "LspReferenceRead", { bg = "#404040" })
hi(0, "LspReferenceText", { bg = "#404040" })
hi(0, "LspReferenceWrite", { bg = "#404040" })
hi(0, "LspSagaAutoPreview", { fg = "#888889" })
hi(0, "LspSagaCodeActionBorder", { fg = "#d09b98" })
hi(0, "LspSagaCodeActionContent", { fg = "#aac2c6" })
hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#e3bc87" })
hi(0, "LspSagaCodeActionTruncateLine", { link = "LspSagaCodeActionBorder" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#666666" })
hi(0, "LspSagaDiagnosticBorder", { fg = "#e3bc87" })
hi(0, "LspSagaDiagnosticHeader", { bold = true, fg = "#aac2c6" })
hi(0, "LspSagaDiagnosticTruncateLine", { link = "LspSagaDiagnosticBorder" })
hi(0, "LspSagaDocTruncateLine", { link = "LspSagaHoverBorder" })
hi(0, "LspSagaFinderSelection", { fg = "#e3bc87" })
hi(0, "LspSagaHoverBorder", { link = "LspFloatWinBorder" })
hi(0, "LspSagaLspFinderBorder", { link = "LspFloatWinBorder" })
hi(0, "LspSagaRenameBorder", { fg = "#4e859d" })
hi(0, "LspSagaRenamePromptPrefix", { fg = "#cf778d" })
hi(0, "LspSagaShTruncateLine", { link = "LspSagaSignatureHelpBorder" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#aac2c6" })
hi(0, "LspSignatureActiveParameter", { bg = "#34343a" })
hi(0, "Macro", { fg = "#b7a4cf" })
hi(0, "MatchParen", { bg = "#2e3844", blend = 25, fg = "#4e859d" })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { bg = "#25252b", bold = true })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniDepsChangeAdded", { fg = "#aac2c6" })
hi(0, "MiniDepsChangeRemoved", { fg = "#cf778d" })
hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
hi(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
hi(0, "MiniDepsPlaceholder", { link = "Comment" })
hi(0, "MiniDepsTitle", { link = "Title" })
hi(0, "MiniDepsTitleError", { link = "DiffDelete" })
hi(0, "MiniDepsTitleSame", { link = "DiffText" })
hi(0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
hi(0, "MiniDiffOverAdd", { bg = "#3f3f3f", blend = 20, fg = "#aac2c6" })
hi(0, "MiniDiffOverChange", { bg = "#3b3a3b", blend = 20, fg = "#d09b98" })
hi(0, "MiniDiffOverContext", { bg = "#25252b" })
hi(0, "MiniDiffOverDelete", { bg = "#3d333b", blend = 20, fg = "#cf778d" })
hi(0, "MiniDiffSignAdd", { fg = "#aac2c6" })
hi(0, "MiniDiffSignChange", { fg = "#d09b98" })
hi(0, "MiniDiffSignDelete", { fg = "#cf778d" })
hi(0, "MiniFilesBorder", { link = "FloatBorder" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesCursorLine", { link = "CursorLine" })
hi(0, "MiniFilesDirectory", { link = "Directory" })
hi(0, "MiniFilesFile", { fg = "#d8d7e4" })
hi(0, "MiniFilesNormal", { link = "NormalFloat" })
hi(0, "MiniFilesTitle", { link = "FloatTitle" })
hi(0, "MiniFilesTitleFocused", { bg = "#25252b", bold = true, fg = "#d09b98" })
hi(0, "MiniHipatternsFixme", { bg = "#d27a90", bold = true, fg = "#1d1c21" })
hi(0, "MiniHipatternsHack", { bg = "#e6be8a", bold = true, fg = "#1d1c21" })
hi(0, "MiniHipatternsNote", { bg = "#adc4c8", bold = true, fg = "#1d1c21" })
hi(0, "MiniHipatternsTodo", { bg = "#baa7d1", bold = true, fg = "#1d1c21" })
hi(0, "MiniIconsAzure", { fg = "#aac2c6" })
hi(0, "MiniIconsBlue", { fg = "#4e859d" })
hi(0, "MiniIconsCyan", { fg = "#aac2c6" })
hi(0, "MiniIconsGreen", { fg = "#9fa3a2" })
hi(0, "MiniIconsGrey", { fg = "#888889" })
hi(0, "MiniIconsOrange", { fg = "#d09b98" })
hi(0, "MiniIconsPurple", { fg = "#b7a4cf" })
hi(0, "MiniIconsRed", { fg = "#cf778d" })
hi(0, "MiniIconsYellow", { fg = "#e3bc87" })
hi(0, "MiniIndentscopeSymbol", { fg = "#666666" })
hi(0, "MiniIndentscopeSymbolOff", { fg = "#e3bc87" })
hi(0, "MiniJump", { sp = "#f6c177", undercurl = true })
hi(0, "MiniJump2dDim", { fg = "#888889" })
hi(0, "MiniJump2dSpot", { bold = true, fg = "#e3bc87", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#25252b", fg = "#aac2c6", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { bold = true, fg = "#d09b98", nocombine = true })
hi(0, "MiniMapNormal", { link = "NormalFloat" })
hi(0, "MiniMapSymbolCount", { link = "Special" })
hi(0, "MiniMapSymbolLine", { link = "Title" })
hi(0, "MiniMapSymbolView", { link = "Delimiter" })
hi(0, "MiniNotifyBorder", { link = "FloatBorder" })
hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
hi(0, "MiniNotifyTitle", { link = "FloatTitle" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { link = "FloatBorder" })
hi(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniPickBorderText", { bg = "#25252b" })
hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { link = "MiniPickNormal" })
hi(0, "MiniPickMatchCurrent", { link = "CursorLine" })
hi(0, "MiniPickMatchMarked", { link = "Visual" })
hi(0, "MiniPickMatchRanges", { fg = "#aac2c6" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPreviewLine", { link = "CursorLine" })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { bg = "#25252b", bold = true })
hi(0, "MiniStarterCurrent", { nocombine = true })
hi(0, "MiniStarterFooter", { fg = "#888889" })
hi(0, "MiniStarterHeader", { link = "Title" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItem", { link = "Normal" })
hi(0, "MiniStarterItemBullet", { link = "Delimiter" })
hi(0, "MiniStarterItemPrefix", { link = "WarningMsg" })
hi(0, "MiniStarterQuery", { link = "MoreMsg" })
hi(0, "MiniStarterSection", { fg = "#d09b98" })
hi(0, "MiniStatuslineDevinfo", { bg = "#34343a", fg = "#888889" })
hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
hi(0, "MiniStatuslineFilename", { bg = "#25252b", fg = "#666666" })
hi(0, "MiniStatuslineInactive", { link = "MiniStatuslineFilename" })
hi(0, "MiniStatuslineModeCommand", { bg = "#d27a90", bold = true, fg = "#1d1c21" })
hi(0, "MiniStatuslineModeInsert", { bg = "#adc4c8", bold = true, fg = "#1d1c21" })
hi(0, "MiniStatuslineModeNormal", { bg = "#d39e9b", bold = true, fg = "#1d1c21" })
hi(0, "MiniStatuslineModeOther", { bg = "#d39e9b", bold = true, fg = "#1d1c21" })
hi(0, "MiniStatuslineModeReplace", { bg = "#5188a0", bold = true, fg = "#1d1c21" })
hi(0, "MiniStatuslineModeVisual", { bg = "#baa7d1", bold = true, fg = "#1d1c21" })
hi(0, "MiniSurround", { link = "IncSearch" })
hi(0, "MiniTablineCurrent", { bg = "#34343a", bold = true, fg = "#d8d7e4" })
hi(0, "MiniTablineFill", { link = "TabLineFill" })
hi(0, "MiniTablineHidden", { bg = "#25252b", fg = "#888889" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#dad9e7", bold = true, fg = "#323238" })
hi(0, "MiniTablineModifiedHidden", { bg = "#8b8b8c", fg = "#232329" })
hi(0, "MiniTablineModifiedVisible", { bg = "#dad9e7", fg = "#232329" })
hi(0, "MiniTablineTabpagesection", { link = "Search" })
hi(0, "MiniTablineVisible", { bg = "#25252b", fg = "#d8d7e4" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#cf778d" })
hi(0, "MiniTestPass", { bold = true, fg = "#aac2c6" })
hi(0, "MiniTrailspace", { bg = "#d27a90" })
hi(0, "ModeMsg", { fg = "#888889" })
hi(0, "ModesCopy", { bg = "#e6be8a" })
hi(0, "ModesCopyCursorLine", { bg = "#1d1913" })
hi(0, "ModesCopyCursorLineFold", { bg = "#1d1913" })
hi(0, "ModesCopyCursorLineNr", { bg = "#1d1913" })
hi(0, "ModesCopyCursorLineSign", { bg = "#1d1913" })
hi(0, "ModesDelete", { bg = "#d27a90" })
hi(0, "ModesDeleteCursorLine", { bg = "#181012" })
hi(0, "ModesDeleteCursorLineFold", { bg = "#181012" })
hi(0, "ModesDeleteCursorLineNr", { bg = "#181012" })
hi(0, "ModesDeleteCursorLineSign", { bg = "#181012" })
hi(0, "ModesInsert", { bg = "#adc4c8" })
hi(0, "ModesInsertCursorLine", { bg = "#161919" })
hi(0, "ModesInsertCursorLineFold", { bg = "#161919" })
hi(0, "ModesInsertCursorLineNr", { bg = "#161919" })
hi(0, "ModesInsertCursorLineSign", { bg = "#161919" })
hi(0, "ModesInsertModeMsg", { fg = "#aac2c6" })
hi(0, "ModesReplace", { bg = "#5188a0" })
hi(0, "ModesVisual", { bg = "#baa7d1" })
hi(0, "ModesVisualCursorLine", { bg = "#161616" })
hi(0, "ModesVisualCursorLineFold", { bg = "#161616" })
hi(0, "ModesVisualCursorLineNr", { bg = "#161616" })
hi(0, "ModesVisualCursorLineSign", { bg = "#161616" })
hi(0, "ModesVisualModeMsg", { fg = "#b7a4cf" })
hi(0, "ModesVisualVisual", { bg = "#161616" })
hi(0, "MoreMsg", { fg = "#b7a4cf" })
hi(0, "NavicIconsArray", { fg = "#e3bc87" })
hi(0, "NavicIconsBoolean", { fg = "#d09b98" })
hi(0, "NavicIconsClass", { fg = "#aac2c6" })
hi(0, "NavicIconsConstant", { fg = "#e3bc87" })
hi(0, "NavicIconsConstructor", { fg = "#e3bc87" })
hi(0, "NavicIconsEnum", { fg = "#e3bc87" })
hi(0, "NavicIconsEnumMember", { fg = "#aac2c6" })
hi(0, "NavicIconsEvent", { fg = "#e3bc87" })
hi(0, "NavicIconsField", { fg = "#aac2c6" })
hi(0, "NavicIconsFile", { fg = "#666666" })
hi(0, "NavicIconsFunction", { fg = "#4e859d" })
hi(0, "NavicIconsInterface", { fg = "#aac2c6" })
hi(0, "NavicIconsKey", { fg = "#b7a4cf" })
hi(0, "NavicIconsKeyword", { fg = "#4e859d" })
hi(0, "NavicIconsMethod", { fg = "#b7a4cf" })
hi(0, "NavicIconsModule", { fg = "#d09b98" })
hi(0, "NavicIconsNamespace", { fg = "#666666" })
hi(0, "NavicIconsNull", { fg = "#cf778d" })
hi(0, "NavicIconsNumber", { fg = "#e3bc87" })
hi(0, "NavicIconsObject", { fg = "#e3bc87" })
hi(0, "NavicIconsOperator", { fg = "#888889" })
hi(0, "NavicIconsPackage", { fg = "#666666" })
hi(0, "NavicIconsProperty", { fg = "#aac2c6" })
hi(0, "NavicIconsString", { fg = "#e3bc87" })
hi(0, "NavicIconsStruct", { fg = "#aac2c6" })
hi(0, "NavicIconsTypeParameter", { fg = "#aac2c6" })
hi(0, "NavicIconsVariable", { fg = "#d8d7e4" })
hi(0, "NavicSeparator", { fg = "#888889" })
hi(0, "NavicText", { fg = "#888889" })
hi(0, "NeoTreeGitAdded", { fg = "#aac2c6" })
hi(0, "NeoTreeGitConflict", { fg = "#b7a4cf" })
hi(0, "NeoTreeGitDeleted", { fg = "#cf778d" })
hi(0, "NeoTreeGitIgnored", { fg = "#666666" })
hi(0, "NeoTreeGitModified", { fg = "#d09b98" })
hi(0, "NeoTreeGitRenamed", { fg = "#4e859d" })
hi(0, "NeoTreeGitUntracked", { fg = "#888889" })
hi(0, "NeoTreeTabActive", { bg = "#34343a", fg = "#d8d7e4" })
hi(0, "NeoTreeTabInactive", { fg = "#888889" })
hi(0, "NeoTreeTabSeparatorActive", { link = "WinSeparator" })
hi(0, "NeoTreeTabSeparatorInactive", { link = "WinSeparator" })
hi(0, "NeoTreeTitleBar", { link = "StatusLineTerm" })
hi(0, "NeogitActiveItem", { bg = "#8fa3a6", bold = true, fg = "#000000" })
hi(0, "NeogitBranch", { bold = true, fg = "#b7a4cf" })
hi(0, "NeogitBranchHead", { bold = true, fg = "#b7a4cf", underline = true })
hi(0, "NeogitChangeAdded", { bold = true, fg = "#aac2c6", italic = true })
hi(0, "NeogitChangeBothModified", { bold = true, fg = "#d09b98", italic = true })
hi(0, "NeogitChangeCopied", { bold = true, fg = "#888889", italic = true })
hi(0, "NeogitChangeDeleted", { bold = true, fg = "#cf778d", italic = true })
hi(0, "NeogitChangeModified", { bold = true, fg = "#d09b98", italic = true })
hi(0, "NeogitChangeNewFile", { bold = true, fg = "#b7a4cf", italic = true })
hi(0, "NeogitChangeRenamed", { bold = true, fg = "#4e859d", italic = true })
hi(0, "NeogitChangeUnmerged", { bold = true, fg = "#948aa2", italic = true })
hi(0, "NeogitChangeUpdated", { bold = true, fg = "#d09b98", italic = true })
hi(0, "NeogitCommitViewHeader", { bg = "#717171", fg = "#000000" })
hi(0, "NeogitDiffAdd", { bg = "#3f3f3f", fg = "#b79973" })
hi(0, "NeogitDiffAddCursor", { bg = "#010101", fg = "#e3bc87" })
hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
hi(0, "NeogitDiffAdditions", { fg = "#b79973" })
hi(0, "NeogitDiffContext", { bg = "#010101" })
hi(0, "NeogitDiffContextCursor", { bg = "#010101" })
hi(0, "NeogitDiffContextHighlight", { bg = "#25252b" })
hi(0, "NeogitDiffDelete", { bg = "#3d333b", fg = "#a46373" })
hi(0, "NeogitDiffDeleteCursor", { bg = "#010101", fg = "#cf778d" })
hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
hi(0, "NeogitDiffDeletions", { fg = "#a46373" })
hi(0, "NeogitDiffHeader", { bg = "#171717", bold = true, fg = "#b7a4cf" })
hi(0, "NeogitDiffHeaderHighlight", { bg = "#171717", bold = true, fg = "#aac2c6" })
hi(0, "NeogitFilePath", { fg = "#aac2c6", italic = true })
hi(0, "NeogitFloatHeader", { bg = "#000000", bold = true })
hi(0, "NeogitFloatHeaderHighlight", { bg = "#0b0b0b", bold = true, fg = "#888889" })
hi(0, "NeogitGraphAuthor", { fg = "#aac2c6" })
hi(0, "NeogitGraphBlue", { fg = "#b7a4cf" })
hi(0, "NeogitGraphBoldBlue", { bold = true, fg = "#b7a4cf" })
hi(0, "NeogitGraphBoldCyan", { bold = true, fg = "#888889" })
hi(0, "NeogitGraphBoldGray", { bold = true, fg = "#5f5f5f" })
hi(0, "NeogitGraphBoldGreen", { bold = true, fg = "#e3bc87" })
hi(0, "NeogitGraphBoldOrange", { bold = true, fg = "#aac2c6" })
hi(0, "NeogitGraphBoldPurple", { bold = true, fg = "#4e859d" })
hi(0, "NeogitGraphBoldRed", { bold = true, fg = "#cf778d" })
hi(0, "NeogitGraphBoldWhite", { bold = true, fg = "#f3f3f3" })
hi(0, "NeogitGraphBoldYellow", { bold = true, fg = "#b7a4cf" })
hi(0, "NeogitGraphCyan", { fg = "#888889" })
hi(0, "NeogitGraphGray", { fg = "#5f5f5f" })
hi(0, "NeogitGraphGreen", { fg = "#e3bc87" })
hi(0, "NeogitGraphOrange", { fg = "#aac2c6" })
hi(0, "NeogitGraphPurple", { fg = "#4e859d" })
hi(0, "NeogitGraphRed", { fg = "#cf778d" })
hi(0, "NeogitGraphWhite", { fg = "#f3f3f3" })
hi(0, "NeogitGraphYellow", { fg = "#b7a4cf" })
hi(0, "NeogitHunkHeader", { bg = "#25252b" })
hi(0, "NeogitHunkHeaderCursor", { bg = "#729bad", bold = true, fg = "#000000" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#25252b" })
hi(0, "NeogitHunkMergeHeader", { bg = "#616161", bold = true, fg = "#080808" })
hi(0, "NeogitHunkMergeHeaderCursor", { bg = "#717171", bold = true, fg = "#000000" })
hi(0, "NeogitHunkMergeHeaderHighlight", { bg = "#717171", bold = true, fg = "#000000" })
hi(0, "NeogitPopupActionKey", { fg = "#4e859d" })
hi(0, "NeogitPopupBold", { bold = true })
hi(0, "NeogitPopupConfigKey", { fg = "#4e859d" })
hi(0, "NeogitPopupOptionKey", { fg = "#4e859d" })
hi(0, "NeogitPopupSwitchKey", { fg = "#4e859d" })
hi(0, "NeogitRemote", { bold = true, fg = "#e3bc87" })
hi(0, "NeogitSectionHeader", { bold = true, fg = "#3e6b7f" })
hi(0, "NeogitTagDistance", { fg = "#888889" })
hi(0, "NeogitTagName", { fg = "#b7a4cf" })
hi(0, "NeogitUnmergedInto", { bold = true, fg = "#3e6b7f" })
hi(0, "NeogitUnpulledFrom", { bold = true, fg = "#3e6b7f" })
hi(0, "NeogitUnpushedTo", { bold = true, fg = "#3e6b7f" })
hi(0, "NeorgHeading1Prefix", { link = "markdownH1Delimiter" })
hi(0, "NeorgHeading1Title", { link = "markdownH1" })
hi(0, "NeorgHeading2Prefix", { link = "markdownH2Delimiter" })
hi(0, "NeorgHeading2Title", { link = "markdownH2" })
hi(0, "NeorgHeading3Prefix", { link = "markdownH3Delimiter" })
hi(0, "NeorgHeading3Title", { link = "markdownH3" })
hi(0, "NeorgHeading4Prefix", { link = "markdownH4Delimiter" })
hi(0, "NeorgHeading4Title", { link = "markdownH4" })
hi(0, "NeorgHeading5Prefix", { link = "markdownH5Delimiter" })
hi(0, "NeorgHeading5Title", { link = "markdownH5" })
hi(0, "NeorgHeading6Prefix", { link = "markdownH6Delimiter" })
hi(0, "NeorgHeading6Title", { link = "markdownH6" })
hi(0, "NeorgMarkerTitle", { bold = true, fg = "#aac2c6" })
hi(0, "NeotestAdapterName", { fg = "#b7a4cf" })
hi(0, "NeotestBorder", { fg = "#3e3e3e" })
hi(0, "NeotestDir", { fg = "#aac2c6" })
hi(0, "NeotestExpandMarker", { fg = "#3e3e3e" })
hi(0, "NeotestFailed", { fg = "#cf778d" })
hi(0, "NeotestFile", { fg = "#d8d7e4" })
hi(0, "NeotestFocused", { bg = "#404040", fg = "#e3bc87" })
hi(0, "NeotestIndent", { fg = "#3e3e3e" })
hi(0, "NeotestMarked", { bold = true, fg = "#d09b98" })
hi(0, "NeotestNamespace", { fg = "#e3bc87" })
hi(0, "NeotestPassed", { fg = "#4e859d" })
hi(0, "NeotestRunning", { fg = "#e3bc87" })
hi(0, "NeotestSkipped", { fg = "#888889" })
hi(0, "NeotestTarget", { fg = "#cf778d" })
hi(0, "NeotestTest", { fg = "#e3bc87" })
hi(0, "NeotestUnknown", { fg = "#888889" })
hi(0, "NeotestWatching", { fg = "#b7a4cf" })
hi(0, "NeotestWinSelect", { fg = "#666666" })
hi(0, "NoiceCursor", { bg = "#dad9e7", fg = "#4f4f4f" })
hi(0, "NoiceFormatProgressDone", { bg = "#3f3f3f", blend = 20, fg = "#d8d7e4" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { fg = "#666666" })
hi(0, "Normal", { bg = "#000000", fg = "#d8d7e4" })
hi(0, "NormalFloat", { bg = "#25252b" })
hi(0, "NormalNC", { bg = "#000000", fg = "#d8d7e4" })
hi(0, "NotifyBackground", { bg = "#25252b" })
hi(0, "NotifyDEBUGBorder", { fg = "#666666" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGTitle" })
hi(0, "NotifyDEBUGTitle", { fg = "#666666" })
hi(0, "NotifyERRORBorder", { fg = "#cf778d" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORTitle" })
hi(0, "NotifyERRORTitle", { fg = "#cf778d" })
hi(0, "NotifyINFOBorder", { fg = "#aac2c6" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOTitle" })
hi(0, "NotifyINFOTitle", { fg = "#aac2c6" })
hi(0, "NotifyTRACEBorder", { fg = "#b7a4cf" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACETitle" })
hi(0, "NotifyTRACETitle", { fg = "#b7a4cf" })
hi(0, "NotifyWARNBorder", { fg = "#e3bc87" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNTitle" })
hi(0, "NotifyWARNTitle", { fg = "#e3bc87" })
hi(0, "Number", { fg = "#e3bc87" })
hi(0, "NvimInternalError", { link = "ErrorMsg" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#666666" })
hi(0, "NvimTreeFileDeleted", { fg = "#cf778d" })
hi(0, "NvimTreeFileDirty", { fg = "#d09b98" })
hi(0, "NvimTreeFileMerge", { fg = "#b7a4cf" })
hi(0, "NvimTreeFileNew", { fg = "#aac2c6" })
hi(0, "NvimTreeFileRenamed", { fg = "#4e859d" })
hi(0, "NvimTreeFileStaged", { fg = "#b7a4cf" })
hi(0, "NvimTreeFolderIcon", { fg = "#888889" })
hi(0, "NvimTreeFolderName", { fg = "#aac2c6" })
hi(0, "NvimTreeGitDeleted", { fg = "#cf778d" })
hi(0, "NvimTreeGitDeletedIcon", { link = "NvimTreeGitDeleted" })
hi(0, "NvimTreeGitDirty", { fg = "#d09b98" })
hi(0, "NvimTreeGitDirtyIcon", { link = "NvimTreeGitDirty" })
hi(0, "NvimTreeGitFileDeletedHL", { link = "NvimTreeFileDeleted" })
hi(0, "NvimTreeGitFileDirtyHL", { link = "NvimTreeFileDirty" })
hi(0, "NvimTreeGitFileMergeHL", { link = "NvimTreeFileMerge" })
hi(0, "NvimTreeGitFileNewHL", { link = "NvimTreeFileNew" })
hi(0, "NvimTreeGitFileRenamedHL", { link = "NvimTreeFileRenamed" })
hi(0, "NvimTreeGitFileStagedHL", { link = "NvimTreeFileStaged" })
hi(0, "NvimTreeGitIgnored", { fg = "#666666" })
hi(0, "NvimTreeGitIgnoredIcon", { link = "NvimTreeGitIgnored" })
hi(0, "NvimTreeGitMerge", { fg = "#b7a4cf" })
hi(0, "NvimTreeGitMergeIcon", { link = "NvimTreeGitMerge" })
hi(0, "NvimTreeGitNew", { fg = "#aac2c6" })
hi(0, "NvimTreeGitNewIcon", { link = "NvimTreeGitNew" })
hi(0, "NvimTreeGitRenamed", { fg = "#4e859d" })
hi(0, "NvimTreeGitRenamedIcon", { link = "NvimTreeGitRenamed" })
hi(0, "NvimTreeGitStaged", { fg = "#b7a4cf" })
hi(0, "NvimTreeGitStagedIcon", { link = "NvimTreeGitStaged" })
hi(0, "NvimTreeImageFile", { fg = "#d8d7e4" })
hi(0, "NvimTreeOpenedFile", { bg = "#34343a", fg = "#d8d7e4" })
hi(0, "NvimTreeOpenedFolderName", { link = "NvimTreeFolderName" })
hi(0, "NvimTreeOpenedHL", { link = "NvimTreeOpenedFile" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#aac2c6" })
hi(0, "NvimTreeSpecialFile", { link = "NvimTreeNormal" })
hi(0, "NvimTreeWindowPicker", { link = "StatusLineTerm" })
hi(0, "Operator", { fg = "#888889" })
hi(0, "Pmenu", { bg = "#25252b", fg = "#888889" })
hi(0, "PmenuExtra", { bg = "#25252b", fg = "#666666" })
hi(0, "PmenuExtraSel", { bg = "#34343a", fg = "#888889" })
hi(0, "PmenuKind", { bg = "#25252b", fg = "#aac2c6" })
hi(0, "PmenuKindSel", { bg = "#34343a", fg = "#888889" })
hi(0, "PmenuSbar", { bg = "#25252b" })
hi(0, "PmenuSel", { bg = "#34343a", fg = "#d8d7e4" })
hi(0, "PmenuThumb", { bg = "#696969" })
hi(0, "PounceAccept", { bg = "#3d333b", blend = 20, fg = "#cf778d" })
hi(0, "PounceAcceptBest", { bg = "#3f3f3f", blend = 20, fg = "#e3bc87" })
hi(0, "PounceGap", { link = "Search" })
hi(0, "PounceMatch", { link = "Search" })
hi(0, "PreCondit", { fg = "#b7a4cf" })
hi(0, "PreProc", { link = "PreCondit" })
hi(0, "Question", { fg = "#e3bc87" })
hi(0, "QuickFixLine", { ctermfg = 14, fg = "#a1e9e8" })
hi(0, "RainbowDelimiterBlue", { fg = "#4e859d" })
hi(0, "RainbowDelimiterCyan", { fg = "#aac2c6" })
hi(0, "RainbowDelimiterGreen", { fg = "#9fa3a2" })
hi(0, "RainbowDelimiterOrange", { fg = "#d09b98" })
hi(0, "RainbowDelimiterRed", { fg = "#cf778d" })
hi(0, "RainbowDelimiterViolet", { fg = "#b7a4cf" })
hi(0, "RainbowDelimiterYellow", { fg = "#e3bc87" })
hi(0, "RedrawDebugClear", { bg = "#e6be8a", fg = "#1d1c21" })
hi(0, "RedrawDebugComposed", { bg = "#5188a0", fg = "#1d1c21" })
hi(0, "RedrawDebugRecompose", { bg = "#d27a90", fg = "#1d1c21" })
hi(0, "ReferencesCount", { fg = "#d09b98" })
hi(0, "ReferencesIcon", { fg = "#d09b98" })
hi(0, "Removed", { ctermfg = 9, fg = "#ebbdb7" })
hi(0, "RenderMarkdownBullet", { fg = "#d09b98" })
hi(0, "RenderMarkdownChecked", { fg = "#aac2c6" })
hi(0, "RenderMarkdownCode", { bg = "#34343a" })
hi(0, "RenderMarkdownCodeInline", { bg = "#34343a", fg = "#d8d7e4" })
hi(0, "RenderMarkdownDash", { fg = "#666666" })
hi(0, "RenderMarkdownH1Bg", { bg = "#3c3b40", blend = 20 })
hi(0, "RenderMarkdownH2Bg", { bg = "#3f3f3f", blend = 20 })
hi(0, "RenderMarkdownH3Bg", { bg = "#3b3a3b", blend = 20 })
hi(0, "RenderMarkdownH4Bg", { bg = "#3f3f3f", blend = 20 })
hi(0, "RenderMarkdownH5Bg", { bg = "#2b323c", blend = 20 })
hi(0, "RenderMarkdownH6Bg", { bg = "#3a3a3a", blend = 20 })
hi(0, "RenderMarkdownQuote", { fg = "#888889" })
hi(0, "RenderMarkdownTableFill", { link = "Conceal" })
hi(0, "RenderMarkdownTableHead", { fg = "#888889" })
hi(0, "RenderMarkdownTableRow", { fg = "#888889" })
hi(0, "RenderMarkdownUnchecked", { fg = "#888889" })
hi(0, "Repeat", { fg = "#4e859d" })
hi(0, "SagaActionTitle", { bg = "#baa7d1", fg = "#000000" })
hi(0, "SagaBeacon", { bg = "#ad4a62" })
hi(0, "SagaButton", { fg = "#b7a4cf" })
hi(0, "SagaCount", { bg = "#7b7b7b", bold = true, fg = "#f6f6f6" })
hi(0, "SagaShadow", { bg = "#34343a" })
hi(0, "SagaVirtLine", { fg = "#424242" })
hi(0, "SatelliteCursor", { fg = "#666666" })
hi(0, "SatelliteMark", { fg = "#d8d7e4" })
hi(0, "SatelliteSearch", { fg = "#3d3d3d" })
hi(0, "Search", { bg = "#3f3f3f", blend = 20, fg = "#d8d7e4" })
hi(0, "SignAdd", { fg = "#aac2c6" })
hi(0, "SignChange", { fg = "#d09b98" })
hi(0, "SignColumn", { fg = "#d8d7e4" })
hi(0, "SignDelete", { fg = "#cf778d" })
hi(0, "Special", { fg = "#aac2c6" })
hi(0, "SpecialComment", { fg = "#b7a4cf" })
hi(0, "SpecialKey", { fg = "#aac2c6" })
hi(0, "SpectreBody", { link = "String" })
hi(0, "SpectreBorder", { link = "Comment" })
hi(0, "SpectreDir", { link = "Comment" })
hi(0, "SpectreFile", { link = "Keyword" })
hi(0, "SpectreHeader", { link = "Comment" })
hi(0, "SpectreReplace", { link = "DiffDelete" })
hi(0, "SpectreSearch", { link = "DiffChange" })
hi(0, "SpellBad", { sp = "#908caa", undercurl = true })
hi(0, "SpellCap", { sp = "#908caa", undercurl = true })
hi(0, "SpellLocal", { sp = "#908caa", undercurl = true })
hi(0, "SpellRare", { sp = "#908caa", undercurl = true })
hi(0, "Statement", { bold = true, fg = "#4e859d" })
hi(0, "StatusLine", { bg = "#25252b", fg = "#888889" })
hi(0, "StatusLineNC", { bg = "#232327", blend = 60, fg = "#666666" })
hi(0, "StatusLineTerm", { bg = "#5188a0", fg = "#1d1c21" })
hi(0, "StatusLineTermNC", { bg = "#3d5d70", blend = 60, fg = "#1d1c21" })
hi(0, "StorageClass", { fg = "#aac2c6" })
hi(0, "String", { fg = "#e3bc87" })
hi(0, "Structure", { fg = "#aac2c6" })
hi(0, "Substitute", { link = "IncSearch" })
hi(0, "TabLine", { bg = "#25252b", fg = "#888889" })
hi(0, "TabLineFill", { bg = "#25252b" })
hi(0, "TabLineSel", { bg = "#34343a", bold = true, fg = "#d8d7e4" })
hi(0, "Tag", { fg = "#aac2c6" })
hi(0, "TargetWord", { fg = "#b7a4cf" })
hi(0, "TelescopeBorder", { fg = "#666666" })
hi(0, "TelescopeMatching", { bg = "#3f3f3f", blend = 20, fg = "#d8d7e4" })
hi(0, "TelescopeNormal", { link = "NormalFloat" })
hi(0, "TelescopePreviewLine", { link = "Search" })
hi(0, "TelescopePromptNormal", { link = "TelescopeNormal" })
hi(0, "TelescopePromptPrefix", { fg = "#888889" })
hi(0, "TelescopeSelection", { bg = "#34343a", fg = "#d8d7e4" })
hi(0, "TelescopeSelectionCaret", { bg = "#34343a", fg = "#d09b98" })
hi(0, "TelescopeTitle", { bold = true, fg = "#aac2c6" })
hi(0, "Title", { bold = true, fg = "#aac2c6" })
hi(0, "Todo", { bg = "#3b3a3b", blend = 20, fg = "#d09b98" })
hi(0, "TodoBgCURRENT", { bg = "#e6be8a", bold = true, fg = "#000000" })
hi(0, "TodoBgFIX", { bg = "#d27a90", bold = true, fg = "#000000" })
hi(0, "TodoBgHACK", { bg = "#e6be8a", bold = true, fg = "#000000" })
hi(0, "TodoBgIMP", { bg = "#d27a90", bold = true, fg = "#000000" })
hi(0, "TodoBgNOTE", { bg = "#baa7d1", bold = true, fg = "#000000" })
hi(0, "TodoBgPERF", { bg = "#dad9e7", bold = true, fg = "#000000" })
hi(0, "TodoBgSECURITY", { bg = "#d27a90", bold = true, fg = "#000000" })
hi(0, "TodoBgTEST", { bg = "#dad9e7", bold = true, fg = "#000000" })
hi(0, "TodoBgTODO", { bg = "#adc4c8", bold = true, fg = "#000000" })
hi(0, "TodoBgUSERINPUT", { bg = "#d27a90", bold = true, fg = "#000000" })
hi(0, "TodoBgVULNERABILITY", { bg = "#d27a90", bold = true, fg = "#000000" })
hi(0, "TodoBgWARN", { bg = "#e6be8a", bold = true, fg = "#000000" })
hi(0, "TodoFgCURRENT", { fg = "#e3bc87" })
hi(0, "TodoFgFIX", { fg = "#cf778d" })
hi(0, "TodoFgHACK", { fg = "#e3bc87" })
hi(0, "TodoFgIMP", { fg = "#cf778d" })
hi(0, "TodoFgNOTE", { fg = "#b7a4cf" })
hi(0, "TodoFgPERF", { fg = "#d8d7e4" })
hi(0, "TodoFgSECURITY", { fg = "#cf778d" })
hi(0, "TodoFgTEST", { fg = "#d8d7e4" })
hi(0, "TodoFgTODO", { fg = "#aac2c6" })
hi(0, "TodoFgUSERINPUT", { fg = "#cf778d" })
hi(0, "TodoFgVULNERABILITY", { fg = "#cf778d" })
hi(0, "TodoFgWARN", { fg = "#e3bc87" })
hi(0, "TodoSignCURRENT", { fg = "#e3bc87" })
hi(0, "TodoSignFIX", { fg = "#cf778d" })
hi(0, "TodoSignHACK", { fg = "#e3bc87" })
hi(0, "TodoSignIMP", { fg = "#cf778d" })
hi(0, "TodoSignNOTE", { fg = "#b7a4cf" })
hi(0, "TodoSignPERF", { fg = "#d8d7e4" })
hi(0, "TodoSignSECURITY", { fg = "#cf778d" })
hi(0, "TodoSignTEST", { fg = "#d8d7e4" })
hi(0, "TodoSignTODO", { fg = "#aac2c6" })
hi(0, "TodoSignUSERINPUT", { fg = "#cf778d" })
hi(0, "TodoSignVULNERABILITY", { fg = "#cf778d" })
hi(0, "TodoSignWARN", { fg = "#e3bc87" })
hi(0, "TreesitterContext", { bg = "#34343a" })
hi(0, "TreesitterContextLineNumber", { bg = "#34343a", fg = "#d09b98" })
hi(0, "TroubleCount", { bg = "#25252b", fg = "#b7a4cf" })
hi(0, "TroubleNormal", { bg = "#25252b", fg = "#d8d7e4" })
hi(0, "TroubleText", { fg = "#888889" })
hi(0, "Type", { fg = "#aac2c6" })
hi(0, "Underlined", { fg = "#b7a4cf", underline = true })
hi(0, "VertSplit", { fg = "#666666" })
hi(0, "VimwikiHR", { fg = "#888889" })
hi(0, "VimwikiHeader1", { link = "markdownH1" })
hi(0, "VimwikiHeader2", { link = "markdownH2" })
hi(0, "VimwikiHeader3", { link = "markdownH3" })
hi(0, "VimwikiHeader4", { link = "markdownH4" })
hi(0, "VimwikiHeader5", { link = "markdownH5" })
hi(0, "VimwikiHeader6", { link = "markdownH6" })
hi(0, "VimwikiHeaderChar", { fg = "#888889" })
hi(0, "VimwikiLink", { link = "markdownUrl" })
hi(0, "VimwikiList", { fg = "#b7a4cf" })
hi(0, "VimwikiNoExistsLink", { fg = "#cf778d" })
hi(0, "Visual", { bg = "#404040" })
hi(0, "WarningMsg", { bold = true, fg = "#e3bc87" })
hi(0, "WhichKey", { fg = "#b7a4cf" })
hi(0, "WhichKeyBorder", { fg = "#666666" })
hi(0, "WhichKeyDesc", { fg = "#e3bc87" })
hi(0, "WhichKeyFloat", { bg = "#25252b" })
hi(0, "WhichKeyGroup", { fg = "#aac2c6" })
hi(0, "WhichKeyIcon", { fg = "#4e859d" })
hi(0, "WhichKeyIconAzure", { fg = "#4e859d" })
hi(0, "WhichKeyIconBlue", { fg = "#4e859d" })
hi(0, "WhichKeyIconCyan", { fg = "#aac2c6" })
hi(0, "WhichKeyIconGreen", { fg = "#9fa3a2" })
hi(0, "WhichKeyIconGrey", { fg = "#888889" })
hi(0, "WhichKeyIconOrange", { fg = "#d09b98" })
hi(0, "WhichKeyIconPurple", { fg = "#b7a4cf" })
hi(0, "WhichKeyIconRed", { fg = "#cf778d" })
hi(0, "WhichKeyIconYellow", { fg = "#e3bc87" })
hi(0, "WhichKeyNormal", { link = "NormalFloat" })
hi(0, "WhichKeySeparator", { fg = "#888889" })
hi(0, "WhichKeyTitle", { link = "FloatTitle" })
hi(0, "WhichKeyValue", { fg = "#d09b98" })
hi(0, "WildMenu", { link = "IncSearch" })
hi(0, "WinBar", { bg = "#25252b", fg = "#888889" })
hi(0, "WinBarNC", { bg = "#232327", blend = 60, fg = "#666666" })
hi(0, "WinSeparator", { fg = "#666666" })
hi(0, "WinShiftCursorLineNr", { bg = "#404040", bold = true, fg = "#d8d7e4" })
hi(0, "WinShiftEndOfBuffer", { bg = "#404040", fg = "#3e3e3e" })
hi(0, "WinShiftFoldColumn", { bg = "#404040", fg = "#666666" })
hi(0, "WinShiftLineNr", { bg = "#404040", fg = "#666666" })
hi(0, "WinShiftNormal", { bg = "#404040" })
hi(0, "WinShiftSignColumn", { bg = "#404040", fg = "#d8d7e4" })
hi(0, "WinShiftWindowPicker", { bg = "#578db2", bold = true, fg = "#e4e4e4" })
hi(0, "diffAdded", { link = "DiffAdd" })
hi(0, "diffChanged", { link = "DiffChange" })
hi(0, "diffRemoved", { link = "DiffDelete" })
hi(0, "healthError", { fg = "#cf778d" })
hi(0, "healthSuccess", { fg = "#aac2c6" })
hi(0, "healthWarning", { fg = "#e3bc87" })
hi(0, "htmlArg", { fg = "#b7a4cf" })
hi(0, "htmlBold", { bold = true })
hi(0, "htmlEndTag", { fg = "#888889" })
hi(0, "htmlH1", { link = "markdownH1" })
hi(0, "htmlH2", { link = "markdownH2" })
hi(0, "htmlH3", { link = "markdownH3" })
hi(0, "htmlH4", { link = "markdownH4" })
hi(0, "htmlH5", { link = "markdownH5" })
hi(0, "htmlItalic", { italic = true })
hi(0, "htmlLink", { link = "markdownUrl" })
hi(0, "htmlTag", { fg = "#888889" })
hi(0, "htmlTagN", { fg = "#d8d7e4" })
hi(0, "htmlTagName", { fg = "#aac2c6" })
hi(0, "lCursor", { bg = "#dad9e7", fg = "#000000" })
hi(0, "lualine_a_14_command", { bg = "#d27a90", fg = "#1d1c21" })
hi(0, "lualine_a_14_inactive", { bg = "#1f1e23", fg = "#666666" })
hi(0, "lualine_a_14_insert", { bg = "#adc4c8", fg = "#1d1c21" })
hi(0, "lualine_a_14_normal", { bg = "#d39e9b", fg = "#1d1c21" })
hi(0, "lualine_a_14_replace", { bg = "#5188a0", fg = "#1d1c21" })
hi(0, "lualine_a_14_terminal", { bg = "#d39e9b", fg = "#1d1c21" })
hi(0, "lualine_a_14_visual", { bg = "#baa7d1", fg = "#1d1c21" })
hi(0, "lualine_a_2_command", { bg = "#d27a90", fg = "#1d1c21" })
hi(0, "lualine_a_2_inactive", { bg = "#1f1e23", fg = "#666666" })
hi(0, "lualine_a_2_insert", { bg = "#adc4c8", fg = "#1d1c21" })
hi(0, "lualine_a_2_normal", { bg = "#d39e9b", fg = "#1d1c21" })
hi(0, "lualine_a_2_replace", { bg = "#5188a0", fg = "#1d1c21" })
hi(0, "lualine_a_2_terminal", { bg = "#d39e9b", fg = "#1d1c21" })
hi(0, "lualine_a_2_visual", { bg = "#baa7d1", fg = "#1d1c21" })
hi(0, "lualine_a_command", { bg = "#d27a90", bold = true, fg = "#1d1c21" })
hi(0, "lualine_a_inactive", { bg = "#1f1e23", bold = true, fg = "#666666" })
hi(0, "lualine_a_insert", { bg = "#adc4c8", bold = true, fg = "#1d1c21" })
hi(0, "lualine_a_normal", { bg = "#d39e9b", bold = true, fg = "#1d1c21" })
hi(0, "lualine_a_replace", { bg = "#5188a0", bold = true, fg = "#1d1c21" })
hi(0, "lualine_a_visual", { bg = "#baa7d1", bold = true, fg = "#1d1c21" })
hi(0, "lualine_b_13_command", { bg = "#34343a", bold = true, fg = "#cf778d" })
hi(0, "lualine_b_13_inactive", { bg = "#1f1e23", bold = true, fg = "#666666" })
hi(0, "lualine_b_13_insert", { bg = "#34343a", bold = true, fg = "#aac2c6" })
hi(0, "lualine_b_13_normal", { bg = "#34343a", bold = true, fg = "#d09b98" })
hi(0, "lualine_b_13_replace", { bg = "#34343a", bold = true, fg = "#4e859d" })
hi(0, "lualine_b_13_terminal", { bg = "#34343a", bold = true, fg = "#d09b98" })
hi(0, "lualine_b_13_visual", { bg = "#34343a", bold = true, fg = "#b7a4cf" })
hi(0, "lualine_b_23_command", { bg = "#34343a", bold = true, fg = "#cf778d" })
hi(0, "lualine_b_23_inactive", { bg = "#1f1e23", bold = true, fg = "#666666" })
hi(0, "lualine_b_23_insert", { bg = "#34343a", bold = true, fg = "#aac2c6" })
hi(0, "lualine_b_23_normal", { bg = "#34343a", bold = true, fg = "#d09b98" })
hi(0, "lualine_b_23_replace", { bg = "#34343a", bold = true, fg = "#4e859d" })
hi(0, "lualine_b_23_terminal", { bg = "#34343a", bold = true, fg = "#d09b98" })
hi(0, "lualine_b_23_visual", { bg = "#34343a", bold = true, fg = "#b7a4cf" })
hi(0, "lualine_b_command", { bg = "#34343a", fg = "#cf778d" })
hi(0, "lualine_b_inactive", { bg = "#1f1e23", fg = "#666666" })
hi(0, "lualine_b_insert", { bg = "#34343a", fg = "#aac2c6" })
hi(0, "lualine_b_normal", { bg = "#34343a", fg = "#d09b98" })
hi(0, "lualine_b_replace", { bg = "#34343a", fg = "#4e859d" })
hi(0, "lualine_b_visual", { bg = "#34343a", fg = "#b7a4cf" })
hi(0, "lualine_c_12_command", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_12_inactive", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_12_insert", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_12_normal", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_12_replace", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_12_terminal", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_12_visual", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_22_command", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_22_inactive", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_22_insert", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_22_normal", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_22_replace", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_22_terminal", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_22_visual", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_command", { bg = "#1f1e23", fg = "#d8d7e4" })
hi(0, "lualine_c_diff_added_0_command", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_diff_added_0_inactive", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_diff_added_0_insert", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_diff_added_0_normal", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_diff_added_0_replace", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_diff_added_0_terminal", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_diff_added_0_visual", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_diff_added_command", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_diff_added_inactive", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_diff_added_insert", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_diff_added_normal", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_diff_added_replace", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_diff_added_terminal", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_diff_added_visual", { bg = "#1f1e23", fg = "#97b278" })
hi(0, "lualine_c_diff_modified_0_command", { bg = "#1f1e23", fg = "#d8b98d" })
hi(0, "lualine_c_diff_modified_0_inactive", { bg = "#1f1e23", fg = "#d8b98d" })
hi(0, "lualine_c_diff_modified_0_insert", { bg = "#1f1e23", fg = "#d8b98d" })
hi(0, "lualine_c_diff_modified_0_normal", { bg = "#1f1e23", fg = "#d8b98d" })
hi(0, "lualine_c_diff_modified_0_replace", { bg = "#1f1e23", fg = "#d8b98d" })
hi(0, "lualine_c_diff_modified_0_terminal", { bg = "#1f1e23", fg = "#d8b98d" })
hi(0, "lualine_c_diff_modified_0_visual", { bg = "#1f1e23", fg = "#d8b98d" })
hi(0, "lualine_c_diff_modified_command", { bg = "#1f1e23", fg = "#d8b98d" })
hi(0, "lualine_c_diff_modified_inactive", { bg = "#1f1e23", fg = "#d8b98d" })
hi(0, "lualine_c_diff_modified_insert", { bg = "#1f1e23", fg = "#d8b98d" })
hi(0, "lualine_c_diff_modified_normal", { bg = "#1f1e23", fg = "#d8b98d" })
hi(0, "lualine_c_diff_modified_replace", { bg = "#1f1e23", fg = "#d8b98d" })
hi(0, "lualine_c_diff_modified_terminal", { bg = "#1f1e23", fg = "#d8b98d" })
hi(0, "lualine_c_diff_modified_visual", { bg = "#1f1e23", fg = "#d8b98d" })
hi(0, "lualine_c_diff_removed_0_command", { bg = "#1f1e23", fg = "#cf696c" })
hi(0, "lualine_c_diff_removed_0_inactive", { bg = "#1f1e23", fg = "#cf696c" })
hi(0, "lualine_c_diff_removed_0_insert", { bg = "#1f1e23", fg = "#cf696c" })
hi(0, "lualine_c_diff_removed_0_normal", { bg = "#1f1e23", fg = "#cf696c" })
hi(0, "lualine_c_diff_removed_0_replace", { bg = "#1f1e23", fg = "#cf696c" })
hi(0, "lualine_c_diff_removed_0_terminal", { bg = "#1f1e23", fg = "#cf696c" })
hi(0, "lualine_c_diff_removed_0_visual", { bg = "#1f1e23", fg = "#cf696c" })
hi(0, "lualine_c_diff_removed_command", { bg = "#1f1e23", fg = "#cf696c" })
hi(0, "lualine_c_diff_removed_inactive", { bg = "#1f1e23", fg = "#cf696c" })
hi(0, "lualine_c_diff_removed_insert", { bg = "#1f1e23", fg = "#cf696c" })
hi(0, "lualine_c_diff_removed_normal", { bg = "#1f1e23", fg = "#cf696c" })
hi(0, "lualine_c_diff_removed_replace", { bg = "#1f1e23", fg = "#cf696c" })
hi(0, "lualine_c_diff_removed_terminal", { bg = "#1f1e23", fg = "#cf696c" })
hi(0, "lualine_c_diff_removed_visual", { bg = "#1f1e23", fg = "#cf696c" })
hi(0, "lualine_c_inactive", { bg = "#1f1e23", fg = "#666666" })
hi(0, "lualine_c_insert", { bg = "#1f1e23", fg = "#d8d7e4" })
hi(0, "lualine_c_normal", { bg = "#1f1e23", fg = "#d8d7e4" })
hi(0, "lualine_c_replace", { bg = "#1f1e23", fg = "#d8d7e4" })
hi(0, "lualine_c_visual", { bg = "#1f1e23", fg = "#d8d7e4" })
hi(0, "lualine_transitional_lualine_a_2_command_to_lualine_b_13_command", { bg = "#34343a", fg = "#cf778d" })
hi(0, "lualine_transitional_lualine_a_2_normal_to_lualine_b_13_normal", { bg = "#34343a", fg = "#d09b98" })
hi(0, "lualine_transitional_lualine_a_2_normal_to_lualine_c_normal", { bg = "#1f1e23", fg = "#d09b98" })
hi(0, "lualine_transitional_lualine_b_13_command_to_lualine_c_command", { bg = "#1f1e23", fg = "#323238" })
hi(0, "lualine_transitional_lualine_b_13_normal_to_lualine_c_normal", { bg = "#1f1e23", fg = "#323238" })
hi(0, "lualine_transitional_lualine_b_command_to_lualine_c_command", { bg = "#1f1e23", fg = "#323238" })
hi(0, "lualine_transitional_lualine_b_normal_to_lualine_c_normal", { bg = "#1f1e23", fg = "#323238" })
hi(0, "lualine_transitional_lualine_z_progress_command_to_lualine_b_command", { bg = "#34343a", fg = "#cf778d" })
hi(0, "lualine_transitional_lualine_z_progress_normal_to_lualine_b_normal", { bg = "#34343a", fg = "#d09b98" })
hi(0, "lualine_x_17_command", { bg = "#1f1e23", bold = true, fg = "#d8d7e4" })
hi(0, "lualine_x_17_inactive", { bg = "#1f1e23", bold = true, fg = "#666666" })
hi(0, "lualine_x_17_insert", { bg = "#1f1e23", bold = true, fg = "#d8d7e4" })
hi(0, "lualine_x_17_normal", { bg = "#1f1e23", bold = true, fg = "#d8d7e4" })
hi(0, "lualine_x_17_replace", { bg = "#1f1e23", bold = true, fg = "#d8d7e4" })
hi(0, "lualine_x_17_terminal", { bg = "#1f1e23", bold = true, fg = "#d8d7e4" })
hi(0, "lualine_x_17_visual", { bg = "#1f1e23", bold = true, fg = "#d8d7e4" })
hi(0, "lualine_x_5_command", { bg = "#1f1e23", bold = true, fg = "#d8d7e4" })
hi(0, "lualine_x_5_inactive", { bg = "#1f1e23", bold = true, fg = "#666666" })
hi(0, "lualine_x_5_insert", { bg = "#1f1e23", bold = true, fg = "#d8d7e4" })
hi(0, "lualine_x_5_normal", { bg = "#1f1e23", bold = true, fg = "#d8d7e4" })
hi(0, "lualine_x_5_replace", { bg = "#1f1e23", bold = true, fg = "#d8d7e4" })
hi(0, "lualine_x_5_terminal", { bg = "#1f1e23", bold = true, fg = "#d8d7e4" })
hi(0, "lualine_x_5_visual", { bg = "#1f1e23", bold = true, fg = "#d8d7e4" })
hi(0, "lualine_x_copilot_disabled_command", { bg = "#1f1e23", fg = "#666c7f" })
hi(0, "lualine_x_copilot_disabled_inactive", { bg = "#1f1e23", fg = "#666c7f" })
hi(0, "lualine_x_copilot_disabled_insert", { bg = "#1f1e23", fg = "#666c7f" })
hi(0, "lualine_x_copilot_disabled_normal", { bg = "#1f1e23", fg = "#666c7f" })
hi(0, "lualine_x_copilot_disabled_replace", { bg = "#1f1e23", fg = "#666c7f" })
hi(0, "lualine_x_copilot_disabled_terminal", { bg = "#1f1e23", fg = "#666c7f" })
hi(0, "lualine_x_copilot_disabled_visual", { bg = "#1f1e23", fg = "#666c7f" })
hi(0, "lualine_x_copilot_enabled_command", { bg = "#1f1e23", fg = "#75e98b" })
hi(0, "lualine_x_copilot_enabled_inactive", { bg = "#1f1e23", fg = "#75e98b" })
hi(0, "lualine_x_copilot_enabled_insert", { bg = "#1f1e23", fg = "#75e98b" })
hi(0, "lualine_x_copilot_enabled_normal", { bg = "#1f1e23", fg = "#75e98b" })
hi(0, "lualine_x_copilot_enabled_replace", { bg = "#1f1e23", fg = "#75e98b" })
hi(0, "lualine_x_copilot_enabled_terminal", { bg = "#1f1e23", fg = "#75e98b" })
hi(0, "lualine_x_copilot_enabled_visual", { bg = "#1f1e23", fg = "#75e98b" })
hi(0, "lualine_x_copilot_offline_command", { bg = "#1f1e23", fg = "#ebb47a" })
hi(0, "lualine_x_copilot_offline_inactive", { bg = "#1f1e23", fg = "#ebb47a" })
hi(0, "lualine_x_copilot_offline_insert", { bg = "#1f1e23", fg = "#ebb47a" })
hi(0, "lualine_x_copilot_offline_normal", { bg = "#1f1e23", fg = "#ebb47a" })
hi(0, "lualine_x_copilot_offline_replace", { bg = "#1f1e23", fg = "#ebb47a" })
hi(0, "lualine_x_copilot_offline_terminal", { bg = "#1f1e23", fg = "#ebb47a" })
hi(0, "lualine_x_copilot_offline_visual", { bg = "#1f1e23", fg = "#ebb47a" })
hi(0, "lualine_x_copilot_sleep_command", { bg = "#1f1e23", fg = "#acafb7" })
hi(0, "lualine_x_copilot_sleep_inactive", { bg = "#1f1e23", fg = "#acafb7" })
hi(0, "lualine_x_copilot_sleep_insert", { bg = "#1f1e23", fg = "#acafb7" })
hi(0, "lualine_x_copilot_sleep_normal", { bg = "#1f1e23", fg = "#acafb7" })
hi(0, "lualine_x_copilot_sleep_replace", { bg = "#1f1e23", fg = "#acafb7" })
hi(0, "lualine_x_copilot_sleep_terminal", { bg = "#1f1e23", fg = "#acafb7" })
hi(0, "lualine_x_copilot_sleep_visual", { bg = "#1f1e23", fg = "#acafb7" })
hi(0, "lualine_x_copilot_spinner_command", { bg = "#1f1e23", fg = "#666c7f" })
hi(0, "lualine_x_copilot_spinner_inactive", { bg = "#1f1e23", fg = "#666c7f" })
hi(0, "lualine_x_copilot_spinner_insert", { bg = "#1f1e23", fg = "#666c7f" })
hi(0, "lualine_x_copilot_spinner_normal", { bg = "#1f1e23", fg = "#666c7f" })
hi(0, "lualine_x_copilot_spinner_replace", { bg = "#1f1e23", fg = "#666c7f" })
hi(0, "lualine_x_copilot_spinner_terminal", { bg = "#1f1e23", fg = "#666c7f" })
hi(0, "lualine_x_copilot_spinner_visual", { bg = "#1f1e23", fg = "#666c7f" })
hi(0, "lualine_x_copilot_unknown_command", { bg = "#1f1e23", fg = "#e3625d" })
hi(0, "lualine_x_copilot_unknown_inactive", { bg = "#1f1e23", fg = "#e3625d" })
hi(0, "lualine_x_copilot_unknown_insert", { bg = "#1f1e23", fg = "#e3625d" })
hi(0, "lualine_x_copilot_unknown_normal", { bg = "#1f1e23", fg = "#e3625d" })
hi(0, "lualine_x_copilot_unknown_replace", { bg = "#1f1e23", fg = "#e3625d" })
hi(0, "lualine_x_copilot_unknown_terminal", { bg = "#1f1e23", fg = "#e3625d" })
hi(0, "lualine_x_copilot_unknown_visual", { bg = "#1f1e23", fg = "#e3625d" })
hi(0, "lualine_x_diagnostics_error_0_command", { bg = "#1f1e23", fg = "#cf778d" })
hi(0, "lualine_x_diagnostics_error_0_inactive", { bg = "#1f1e23", fg = "#cf778d" })
hi(0, "lualine_x_diagnostics_error_0_insert", { bg = "#1f1e23", fg = "#cf778d" })
hi(0, "lualine_x_diagnostics_error_0_normal", { bg = "#1f1e23", fg = "#cf778d" })
hi(0, "lualine_x_diagnostics_error_0_replace", { bg = "#1f1e23", fg = "#cf778d" })
hi(0, "lualine_x_diagnostics_error_0_terminal", { bg = "#1f1e23", fg = "#cf778d" })
hi(0, "lualine_x_diagnostics_error_0_visual", { bg = "#1f1e23", fg = "#cf778d" })
hi(0, "lualine_x_diagnostics_error_command", { bg = "#1f1e23", fg = "#cf778d" })
hi(0, "lualine_x_diagnostics_error_inactive", { bg = "#1f1e23", fg = "#cf778d" })
hi(0, "lualine_x_diagnostics_error_insert", { bg = "#1f1e23", fg = "#cf778d" })
hi(0, "lualine_x_diagnostics_error_normal", { bg = "#1f1e23", fg = "#cf778d" })
hi(0, "lualine_x_diagnostics_error_replace", { bg = "#1f1e23", fg = "#cf778d" })
hi(0, "lualine_x_diagnostics_error_terminal", { bg = "#1f1e23", fg = "#cf778d" })
hi(0, "lualine_x_diagnostics_error_visual", { bg = "#1f1e23", fg = "#cf778d" })
hi(0, "lualine_x_diagnostics_hint_0_command", { bg = "#1f1e23", fg = "#b7a4cf" })
hi(0, "lualine_x_diagnostics_hint_0_inactive", { bg = "#1f1e23", fg = "#b7a4cf" })
hi(0, "lualine_x_diagnostics_hint_0_insert", { bg = "#1f1e23", fg = "#b7a4cf" })
hi(0, "lualine_x_diagnostics_hint_0_normal", { bg = "#1f1e23", fg = "#b7a4cf" })
hi(0, "lualine_x_diagnostics_hint_0_replace", { bg = "#1f1e23", fg = "#b7a4cf" })
hi(0, "lualine_x_diagnostics_hint_0_terminal", { bg = "#1f1e23", fg = "#b7a4cf" })
hi(0, "lualine_x_diagnostics_hint_0_visual", { bg = "#1f1e23", fg = "#b7a4cf" })
hi(0, "lualine_x_diagnostics_hint_command", { bg = "#1f1e23", fg = "#b7a4cf" })
hi(0, "lualine_x_diagnostics_hint_inactive", { bg = "#1f1e23", fg = "#b7a4cf" })
hi(0, "lualine_x_diagnostics_hint_insert", { bg = "#1f1e23", fg = "#b7a4cf" })
hi(0, "lualine_x_diagnostics_hint_normal", { bg = "#1f1e23", fg = "#b7a4cf" })
hi(0, "lualine_x_diagnostics_hint_replace", { bg = "#1f1e23", fg = "#b7a4cf" })
hi(0, "lualine_x_diagnostics_hint_terminal", { bg = "#1f1e23", fg = "#b7a4cf" })
hi(0, "lualine_x_diagnostics_hint_visual", { bg = "#1f1e23", fg = "#b7a4cf" })
hi(0, "lualine_x_diagnostics_info_0_command", { bg = "#1f1e23", fg = "#aac2c6" })
hi(0, "lualine_x_diagnostics_info_0_inactive", { bg = "#1f1e23", fg = "#aac2c6" })
hi(0, "lualine_x_diagnostics_info_0_insert", { bg = "#1f1e23", fg = "#aac2c6" })
hi(0, "lualine_x_diagnostics_info_0_normal", { bg = "#1f1e23", fg = "#aac2c6" })
hi(0, "lualine_x_diagnostics_info_0_replace", { bg = "#1f1e23", fg = "#aac2c6" })
hi(0, "lualine_x_diagnostics_info_0_terminal", { bg = "#1f1e23", fg = "#aac2c6" })
hi(0, "lualine_x_diagnostics_info_0_visual", { bg = "#1f1e23", fg = "#aac2c6" })
hi(0, "lualine_x_diagnostics_info_command", { bg = "#1f1e23", fg = "#aac2c6" })
hi(0, "lualine_x_diagnostics_info_inactive", { bg = "#1f1e23", fg = "#aac2c6" })
hi(0, "lualine_x_diagnostics_info_insert", { bg = "#1f1e23", fg = "#aac2c6" })
hi(0, "lualine_x_diagnostics_info_normal", { bg = "#1f1e23", fg = "#aac2c6" })
hi(0, "lualine_x_diagnostics_info_replace", { bg = "#1f1e23", fg = "#aac2c6" })
hi(0, "lualine_x_diagnostics_info_terminal", { bg = "#1f1e23", fg = "#aac2c6" })
hi(0, "lualine_x_diagnostics_info_visual", { bg = "#1f1e23", fg = "#aac2c6" })
hi(0, "lualine_x_diagnostics_warn_0_command", { bg = "#1f1e23", fg = "#e3bc87" })
hi(0, "lualine_x_diagnostics_warn_0_inactive", { bg = "#1f1e23", fg = "#e3bc87" })
hi(0, "lualine_x_diagnostics_warn_0_insert", { bg = "#1f1e23", fg = "#e3bc87" })
hi(0, "lualine_x_diagnostics_warn_0_normal", { bg = "#1f1e23", fg = "#e3bc87" })
hi(0, "lualine_x_diagnostics_warn_0_replace", { bg = "#1f1e23", fg = "#e3bc87" })
hi(0, "lualine_x_diagnostics_warn_0_terminal", { bg = "#1f1e23", fg = "#e3bc87" })
hi(0, "lualine_x_diagnostics_warn_0_visual", { bg = "#1f1e23", fg = "#e3bc87" })
hi(0, "lualine_x_diagnostics_warn_command", { bg = "#1f1e23", fg = "#e3bc87" })
hi(0, "lualine_x_diagnostics_warn_inactive", { bg = "#1f1e23", fg = "#e3bc87" })
hi(0, "lualine_x_diagnostics_warn_insert", { bg = "#1f1e23", fg = "#e3bc87" })
hi(0, "lualine_x_diagnostics_warn_normal", { bg = "#1f1e23", fg = "#e3bc87" })
hi(0, "lualine_x_diagnostics_warn_replace", { bg = "#1f1e23", fg = "#e3bc87" })
hi(0, "lualine_x_diagnostics_warn_terminal", { bg = "#1f1e23", fg = "#e3bc87" })
hi(0, "lualine_x_diagnostics_warn_visual", { bg = "#1f1e23", fg = "#e3bc87" })
hi(0, "lualine_x_filetype_DevIconLua_command", { bg = "#1f1e23", fg = "#6296b7" })
hi(0, "lualine_x_filetype_DevIconLua_inactive", { bg = "#1f1e23", fg = "#6296b7" })
hi(0, "lualine_x_filetype_DevIconLua_insert", { bg = "#1f1e23", fg = "#6296b7" })
hi(0, "lualine_x_filetype_DevIconLua_normal", { bg = "#1f1e23", fg = "#6296b7" })
hi(0, "lualine_x_filetype_DevIconLua_replace", { bg = "#1f1e23", fg = "#6296b7" })
hi(0, "lualine_x_filetype_DevIconLua_terminal", { bg = "#1f1e23", fg = "#6296b7" })
hi(0, "lualine_x_filetype_DevIconLua_visual", { bg = "#1f1e23", fg = "#6296b7" })
hi(0, "lualine_z_progress_0_command", { bg = "#d27a90", fg = "#1d1c21" })
hi(0, "lualine_z_progress_0_inactive", { bg = "#1f1e23", fg = "#666666" })
hi(0, "lualine_z_progress_0_insert", { bg = "#adc4c8", fg = "#1d1c21" })
hi(0, "lualine_z_progress_0_normal", { bg = "#d39e9b", fg = "#1d1c21" })
hi(0, "lualine_z_progress_0_replace", { bg = "#5188a0", fg = "#1d1c21" })
hi(0, "lualine_z_progress_0_terminal", { bg = "#d39e9b", fg = "#1d1c21" })
hi(0, "lualine_z_progress_0_visual", { bg = "#baa7d1", fg = "#1d1c21" })
hi(0, "lualine_z_progress_command", { bg = "#d27a90", fg = "#1d1c21" })
hi(0, "lualine_z_progress_inactive", { bg = "#1f1e23", fg = "#666666" })
hi(0, "lualine_z_progress_insert", { bg = "#adc4c8", fg = "#1d1c21" })
hi(0, "lualine_z_progress_normal", { bg = "#d39e9b", fg = "#1d1c21" })
hi(0, "lualine_z_progress_replace", { bg = "#5188a0", fg = "#1d1c21" })
hi(0, "lualine_z_progress_terminal", { bg = "#d39e9b", fg = "#1d1c21" })
hi(0, "lualine_z_progress_visual", { bg = "#baa7d1", fg = "#1d1c21" })
hi(0, "markdownDelimiter", { fg = "#888889" })
hi(0, "markdownH1", { bold = true, fg = "#b7a4cf" })
hi(0, "markdownH1Delimiter", { link = "markdownH1" })
hi(0, "markdownH2", { bold = true, fg = "#aac2c6" })
hi(0, "markdownH2Delimiter", { link = "markdownH2" })
hi(0, "markdownH3", { bold = true, fg = "#d09b98" })
hi(0, "markdownH3Delimiter", { link = "markdownH3" })
hi(0, "markdownH4", { bold = true, fg = "#e3bc87" })
hi(0, "markdownH4Delimiter", { link = "markdownH4" })
hi(0, "markdownH5", { bold = true, fg = "#4e859d" })
hi(0, "markdownH5Delimiter", { link = "markdownH5" })
hi(0, "markdownH6", { bold = true, fg = "#9fa3a2" })
hi(0, "markdownH6Delimiter", { link = "markdownH6" })
hi(0, "markdownLinkText", { link = "markdownUrl" })
hi(0, "markdownUrl", { fg = "#b7a4cf", sp = "#c4a7e7", underline = true })
hi(0, "mkdCode", { fg = "#aac2c6", italic = true })
hi(0, "mkdCodeDelimiter", { fg = "#d09b98" })
hi(0, "mkdCodeEnd", { fg = "#aac2c6" })
hi(0, "mkdCodeStart", { fg = "#aac2c6" })
hi(0, "mkdFootnotes", { fg = "#aac2c6" })
hi(0, "mkdID", { fg = "#aac2c6", underline = true })
hi(0, "mkdInlineURL", { link = "markdownUrl" })
hi(0, "mkdLink", { link = "markdownUrl" })
hi(0, "mkdLinkDef", { link = "markdownUrl" })
hi(0, "mkdListItemLine", { fg = "#d8d7e4" })
hi(0, "mkdRule", { fg = "#888889" })
hi(0, "mkdURL", { link = "markdownUrl" })
hi(0, "nvim-highlight-colors-background000000000000", { bg = "#000000", fg = "#f6f6f6" })
hi(0, "nvim-highlight-colors-background171717171717", { bg = "#121212", fg = "#f6f6f6" })
hi(0, "nvim-highlight-colors-background39364a39364a", { bg = "#343434", fg = "#f6f6f6" })
hi(0, "nvim-highlight-colors-background3f3c523f3c52", { bg = "#3a3a3a", fg = "#f6f6f6" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#393552"
g.terminal_color_1 = "#eb6f92"
g.terminal_color_2 = "#3e8fb0"
g.terminal_color_3 = "#f6c177"
g.terminal_color_4 = "#9ccfd8"
g.terminal_color_5 = "#c4a7e7"
g.terminal_color_6 = "#ea9a97"
g.terminal_color_7 = "#e0def4"
g.terminal_color_8 = "#908caa"
g.terminal_color_9 = "#eb6f92"
g.terminal_color_10 = "#3e8fb0"
g.terminal_color_11 = "#f6c177"
g.terminal_color_12 = "#9ccfd8"
g.terminal_color_13 = "#c4a7e7"
g.terminal_color_14 = "#ea9a97"
g.terminal_color_15 = "#e0def4"
