return {
    -- ###############
    -- # AI chatgpt openai etc
    -- #############

    -- ##### COPILOT #####
    -- official plugin, we use copilot.lua instead
    -- {
    --     'github/copilot.vim',
    --     init = function()
    --         vim.g.copilot_assume_mapped = true
    --         vim.g.copilot_filetypes = {
    --             ["*"] = false,
    --             ["markdown"] = true,
    --             ["pandoc"] = true,
    --             ["javascript"] = true,
    --             ["typescript"] = true,
    --             ["lua"] = true,
    --             ["rust"] = true,
    --             ["c"] = true,
    --             ["c#"] = true,
    --             ["c++"] = true,
    --             ["go"] = true,
    --             ["python"] = true,
    --             ["astro"] = true,
    --             ["html"] = true,
    --             ["css"] = true,
    --             ["scss"] = true,
    --         }
    --         vim.g.copilot_no_tab_map = true
    --         vim.g.copilot_tab_fallback = ""
    --         vim.api.nvim_set_keymap("i", "<C-l>", 'copilot#Accept("<CR>")', { silent = true, expr = true })
    --     end
    -- },
    -- try Lua version after seeing chris

    -- {
    --     "james1236/backseat.nvim",
    --     config = function()
    --         require("backseat").setup({
    --             -- Alternatively, set the env var $OPENAI_API_KEY by putting "export OPENAI_API_KEY=sk-xxxxx" in your ~/.bashrc
    --             openai_api_key = os.getenv("OPENAI_API_KEY"), -- Get yours from platform.openai.com/account/api-keys
    --             -- openai_model_id = 'gpt-3.5-turbo',            --gpt-4 (If you do not have access to a model, it says "The model does not exist")
    --             openai_model_id = 'gpt-4',                    --gpt-4 (If you do not have access to a model, it says "The model does not exist")
    --             -- split_threshold = 100,
    --             -- additional_instruction = "Respond snarkily", -- (GPT-3 will probably deny this request, but GPT-4 complies)
    --             -- highlight = {
    --             --     icon = '', -- '' TODO: fix icon
    --             --     group = 'Comment',
    --             -- }
    --         })
    --     end
    -- },
    -- { 'aduros/ai.vim',
    --     config = function()
    --         require('ai').setup()
    --     end
    -- },
}
